### ISSUE TITLE
Not able to uninstall packages android 5.0.2

### ISSUE THREAD

**Issue by Twiggumps** [0x192/Universal-Android-Debloater#100]
Hello, I am trying to debloat a 4G tablet(VK810) running Android 5.0.2 but when I disable or uninstall a package with the gui it is still available on the tablet. 

after reading some threads with people getting similar issues I took to shell and ran `adb shell pm disable-user com.amazon.windowshop` and got back `Error: java.lang.SecurityException: Permission Denial: attempt to change component state from pid=20553, uid=2000, package uid=10114`
I also tried `pm hide com.amazon.windowshop` and got `Error: java.lang.SecurityException: Neither user 2000 nor current process has android.permission.MANAGE_USERS.`

I have also attached uad log here as well. I feel like I've made a stupid mistake here but I don't know what. Any advice appreciated!

[uad.log](https://github.com/0x192/universal-android-debloater/files/7850649/uad.log)

**Comment by lawson85** [comment]
Other seem to have issues similar: https://www.reddit.com/r/firetvstick/comments/q4auun/cant_disable_fire_tv_launcher

**Comment by 0x192** [comment]
Sorry for the late reply!

`v0.3` didn't work for older devices (< Android 8.0) (see #78). I fixed this in `v0.4`. Try again with the GUI. If that still doesn't work, upload the logs (you can locate the logs in the `About` page of the GUI)

This is the command used for Android 5.x (notice the `--user 0`) :
```bash
adb shell pm hide --user 0 com.amazon.windowshop
```
