### ISSUE TITLE
Google Play system update not working 

### ISSUE THREAD

**Issue by WPHorhe** [0x192/universal-android-debloater#1000]
**Your phone model**
Google Pixel 7a

**Describe the issue**
I used ShizuTools app to debloat my phone everything is nice and easy but I disabled something and since then when I go into device settings and I go to check for Google play system update I press on it and it tries to open the menu but it brings me back trying multiple times doesn't work I even disabled Google play store and enabled , clear data .. but it doesn't work I have this issue since I used shizu tools to debloat my phone about a month ago.
I was just asking if u can provide a package name so I cann go back and re-enable it since I disable so much apps and I don't know which may cause the issue .

Also I disabled an package named (Main Components , package name : com.google.mainline.adservices) marked as recommend to uninstall , which kicked me to the home screen and disabled wifi debugging and I had no developer options in the settings I just performed a restart and I got developer options back.

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/ygYJDf9YBn
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org

**Comment by WPHorhe** [comment]
Ohh ok I will try there
