### ISSUE TITLE
Prevent project data loss

### ISSUE THREAD

**Issue by lawson85** [0x192/Universal-Android-Debloater#101]
**Describe the feature you want**
A clear description of what you want to happen.
I've just seen this on r/opensource says that it should help prevent data loss. https://github.com/nikochiko/autosaved

**Comment by 0x192** [comment]
This is quite nice but this is not really useful for this project. My IDE saving my code in case of a sudden power failure is enough for me. I also make weekly backup of my computer and push my code to Github regularly.
