### ISSUE TITLE
Lenovo Bloatlist

### ISSUE THREAD

**Issue by DarkSkull91** [0x192/Universal-Android-Debloater#102]
Is it possible to add also a debloat list for Lenovo smartphone/tablets?

**Comment by KarlRamstedt** [comment]
Yes... if somebody with a Lenovo device contributes to the project.
If you have one then feel free to list the info on all relevant packages, or better yet, add them to the UAD list and make a pull request.

**Comment by 0x192** [comment]
https://github.com/0x192/universal-android-debloater/wiki#how-to-contribute :slightly_smiling_face:
