### ISSUE TITLE
Use `adb_client`

### ISSUE THREAD

**Issue by simonsan** [0x192/universal-android-debloater#1039]
https://github.com/cocool97/adb_client/ just got a new release and I wonder if using it in `UAB` could be nice to get independent of the `adb` dependency on each platform.

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/CzwbMCPEZa
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org

**Comment by simonsan** [comment]
Ref.: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/700
