### ISSUE TITLE
powergenie Huawei/EMUI

### ISSUE THREAD

**Issue by lawson85** [0x192/Universal-Android-Debloater#104]
**Your phone**: Honor 10 Lite HRY-LX1
**Packages documentation to update:**
```
com.huawei.powergenie
```
## Documentation change
**List**: `Oem`
**Removal**: `Recommended`

### com.huawei.powergenie
**List**:  Oem :arrow_right: Oem
**Removal**: Recommended :arrow_right: Recommended

**Current description**
> [No description]

**Proposed description**
> Safe and recommended to remove by https://dontkillmyapp.com/huawei. It causes apps to be killed in the background and is overzealous - it can cause emergency apps to fail

**Comment by KarlRamstedt** [comment]
Added this to a pull in the process of being merged.
You can close this now.
