### ISSUE TITLE
It won't open on Linux Wayland 

### ISSUE THREAD

**Issue by JoaoHCopetti** [0x192/universal-android-debloater#1052]
**Describe the bug**
When trying to open on Linux using Wayland, you get this error in the terminal:
> interface 'wl_surface' has no event 2

**Expected behavior**
It should open.

**You have a solution?**
Run the script with X11, if you're in Wayland it can be done using `WINIT_UNIX_BACKEND=x11 ./uad_gui_linux`

**UAD log**
I don't know where the log is located.

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the main function to check if the session is running on Wayland and set the WINIT_UNIX_BACKEND environment variable to 'x11' if it is. This allows the application to fall back to X11 when running on Wayland, addressing the reported issue.

You can review changes in this commit: https://github.com/wwqwq2313/0x192-universal-android-debloater-1052/commit/a7cc5c5f17d861f7466834e83f32705d7bc22546.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/CzwbMCPEZa
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org

**Comment by JoaoHCopetti** [comment]
@Obegg I'd suggest to add that new repo at the top in the README.md file, I had no idea about that.
