### ISSUE TITLE
black oval in fullscreen mode

### ISSUE THREAD

**Issue by nikitax44** [0x192/universal-android-debloater#1054]
**Your phone model**: POCO 2207117BPG

**Describe the issue**
after removal of `com.android.systemui.overlay.miui` :
if current app is opened in horisontal fullscreen layout (e.g. youtube video player) you will see small black oval in the top part of the screen. 

**You have a solution?**
do not uninstall `com.android.systemui.overlay.miui`

**UAD log**
none

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/CzwbMCPEZa
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org

**Comment by nikitax44** [comment]
my bad, forgot to reboot. package is not relevant.
