### ISSUE TITLE
add com.tblenovo.lenovotips

### ISSUE THREAD

**Issue by DarkSkull91** [0x192/Universal-Android-Debloater#115]
Lenovo Table P11 (TB-J606F)

com.tblenovo.lenovotips

Tips app. Tested on my tablet, useless.

**Comment by 0x192** [comment]
Thanks. [Apparently this app even displays ads in notifications](https://forums.lenovo.com/t5/Lenovo-Android-based-Tablets-and-Phablets/Lenovo-Tips-application-advertising-paid-services-via-notifications/m-p/5094365).

**Comment by DarkSkull91** [comment]
Excuse me @0x192  will you add in the next release? or did you reject my proposal?

**Comment by 0x192** [comment]
I added it. :)

You can see there is a commit (https://github.com/0x192/universal-android-debloater/commit/28e97e6a0de63e9bd1caf90a96a40ee993da8f16) referencing the issue closure.

By the way, from the next release (`v0.5`), UAD will directly download the debloat list ([`uad_list.json`](https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json)) from Github. This means you will no longer have to wait for the next release to benefit from the changes in the list.

FYI, I always add new packages even if it is not recommended to remove them, just for the documentation. One of the main goal of UAD is to document as much apps as possible.

**Comment by loonsies** [comment]
com.android.chrome
com.google.android.apps.books
com.google.android.apps.docs
com.google.android.apps.kids.home
com.google.android.apps.maps
com.google.android.apps.mediahome.launcher
com.google.android.apps.photos
com.google.android.apps.restore
com.google.android.apps.subscriptions.red
com.google.android.apps.tachyon
com.google.android.apps.wellbeing
com.google.android.apps.youtube.kids
com.google.android.apps.youtube.music
com.google.android.apps.youtube.music.setupwizard
com.google.android.keep
com.google.android.marvin.talkback
com.google.android.videos
com.google.android.youtube
com.lenovo.lcui.translator
com.lenovo.lsf
com.lenovo.lsf.device
com.lenovo.tab_p11_pro
com.lenovo.ue.device
com.motorola.demo
com.qualcomm.qti.simcontacts
com.steadfastinnovation.android.projectpapyrus
com.tblenovo.center
com.tblenovo.userguide
com.tblenovo.wallpaper
com.netflix.mediaclient

I wasn't able to see a few apps into UAD, dunno why
