### ISSUE TITLE
2 Google apps to add

### ISSUE THREAD

**Issue by veronicapfio** [0x192/Universal-Android-Debloater#116]
**Your phone:** moto E7i power

**Packages:**
```
com.google.android.apps.assistant
com.google.android.apps.searchlite
```
- [X] **I removed all those packages on my phone**
If not why. Leave the brackets blank and explain why.

## Document each package the best you can
**List**: `Oem` (manufacturer).
**Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features), `Unsafe` (this can bootloop the phone or break extremely important features).

###  com.google.android.apps.assistant 
**List**: Oem
**Removal**: Recommended
> Description. Link to its Playstore page if it exists.

### com.google.android.apps.searchlite
**List**: Oem
**Removal**: Recommended
> Description. Link to its Playstore page if it exists.

**Comment by KarlRamstedt** [comment]
I'll help out with this one.
These are 2 lite-versions of Google apps. Specifically search and assistant. Both should be perfectly fine to disable, just like their normal counterparts.

https://play.google.com/store/apps/details?id=com.google.android.apps.assistant
### com.google.android.apps.assistant
**List**: Google
**Removal**: Recommended
> Google Assistant Go (https://play.google.com/store/apps/details?id=com.google.android.apps.assistant)\nGo apps are lite-versions of their normal counterparts, made for low-RAM devices.

### com.google.android.apps.searchlite
**List**: Google
**Removal**: Recommended
> Google Go (https://play.google.com/store/apps/details?id=com.google.android.apps.searchlite)\nGo apps are lite-versions of their normal counterparts, made for low-RAM devices.

**Comment by veronicapfio** [comment]
Thank you!

**Comment by KarlRamstedt** [comment]
Added these to a pull in the process of being merged.
You can close this now.
