### ISSUE TITLE
com.samsung.android.app.appsedge

### ISSUE THREAD

**Issue by lazymonkey2** [0x192/Universal-Android-Debloater#124]
**Your phone**: samsung a50 android 11

**Describe the issue**
after disabling com.samsung.android.app.appsedge the split screen (multi window) doesn't work anymore

**You have a solution?**
don't disable the app.

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.

**Comment by KarlRamstedt** [comment]
Added this to a pull in the process of being merged.
You can close this now.

**Comment by lazymonkey2** [comment]
Thank you.

**Comment by Rudxain** [comment]
Can confirm, SM-A315G has the same issue.

I'm still impressed at the ability of Samsung devs to f-up simple stuff. Like, why the heck is this completely-unrelated edge-extension a hard-dependency of the Split-Screen feature? And why did S even implement their own SS? AOSP already has built-in support for multi-window. [This isn't the 1st time they do crap like this](https://rudxain.github.io/Samsung-rants/#blue-light-filter)
