### ISSUE TITLE
UAD is terminated

### ISSUE THREAD

**Issue by kbudack** [0x192/Universal-Android-Debloater#128]
**Describe the bug**
after each change on a SM-T545 the UAD is terminated.

**UAD log**
Upload the logfile generated by UAD.
[UAD_20220211.log](https://github.com/0x192/universal-android-debloater/files/8048861/UAD_20220211.log)

**Comment by 0x192** [comment]
You mean that UAD crashes?

Reading the logfile tells me that there is a permission issue when trying to uninstall the app for the `user 150` (Secure Folder). Unfortunately we can't do anything: 

> Samsung has restricted privileges of adb (shell) user from making changes to packages installed under user 150. There is nothing we can do. This is a design choice (probably to ensure bloat continues to float in the device). Rooting is the only solution to remove bloatware in such situations
[Firelord -- android.stackexchange](https://android.stackexchange.com/questions/243104/getting-java-lang-securityexception-shell-does-not-have-permission-to-access-u#comment324953_243104)

**Comment by KarlRamstedt** [comment]
@kbudack deselect the "Affect all the users of the phone (not only the selected user)" option in Settings if it's selected. As long as UAD isn't trying to uninstall from user 150, it shouldn't "terminate"?

@0x192 if "terminate" means crash in this case it might be worth looking into some basic error handling when UAD can't disable/uninstall certain packages. Just something as simple as:
```
try {
    Uninstall(package);
}
catch {
    ShowErrorMessage();
}
```
(psuedo-code to illustrate basic structure, I don't know the syntax of Rust)
And maybe parse the error message from the console to the GUI error popup for clarity?

**Comment by 0x192** [comment]
> if "terminate" means crash in this case it might be worth looking into some basic error handling when UAD can't disable/uninstall certain packages

FYI, UAD won't crash if an ADB command fail. The user will be able to see that the state of the package didn't change. 

I don't really know how to nicely integrate those error messages in the GUI and [Iced](https://github.com/iced-rs/iced/issues/704) doesn't have a popup widget yet.

@kbudack
No further information being provided, I close the issue. I will still see your reply if you come back.
