### ISSUE TITLE
“Clear and disable packages instead of uninstalling them” should stick between launches

### ISSUE THREAD

**Issue by AlessandroDiGioacchino** [0x192/Universal-Android-Debloater#130]
Title sounds pretty clear.
I don't want to uninstall packages because some features may be broken and the package that provides them may not be downloadable anymore, which is why “Clear and disable packages instead of uninstalling them” is a very useful option.
I once forgot to enable it, uninstalled some packages and had to restore my device in order to get them back. For this very reason I'm requesting such an enhancement.
Thank you.

**Comment by KarlRamstedt** [comment]
Wouldn't hurt to have this feature, but TBH, I think Disable+Clear should be the default instead of Uninstall, because Uninstall has ZERO practical advantages over Disable+Clear and even has several *disadvantages*.
This is one of the points I plan to bring up in a larger feedback post later.

**Comment by 0x192** [comment]
Device-specific persistent configuration is ready (b525e61) and will be available in `v0.6`!
