### ISSUE TITLE
How to start UAD GUI

### ISSUE THREAD

**Issue by aritorhamo** [0x192/Universal-Android-Debloater#132]
I have downloaded AOD GUI for Linux as a file named "uad_gui". What's missing is the information how to start the program. Double clicking the file doesn't do anything. Perhaps I should address the file somehow in the terminal, but I don't know how (I know how to give commands in the terminal, but I don't know the right command). I think it would be good to add this information to the Readme. Thanks!

**Comment by ghost** [comment]
For future reference, this is how you start UAD:  
```$ chmod +x uad_gui```
```$ ./uad_gui```

It would be useful to add to the README file for those who don't know.

**Comment by 0x192** [comment]
Please read the README guys! In the [`How to use it`](https://github.com/0x192/universal-android-debloater#how-to-use-it) section, it is written **in bold to read the FAQ**.

The very first question adresses your problem.

That being said, this permission problem is no longer needed on Linux with the latest version (`v0.4.1`). You just have to double-click on the executable. Are you sure you have the `v0.4.1`?

**Comment by aritorhamo** [comment]
> Please read the README guys! In the [`How to use it`](https://github.com/0x192/universal-android-debloater#how-to-use-it) section, it is written **in bold to read the FAQ**.

The section of the FAQ you are referring to is for MacOS. That's written in bold too...

> That being said, this permission problem is no longer needed on Linux with the latest version (`v0.4.1`). You just have to double-click on the executable. 

The first thing I tried before asking for advice here was to double-click the file. The next thing I tried was to change the permission (graphically, in Linux Mint) to enable execution of the file. Then I went to the terminal and gave the command "uad_gui".  That didn't work either (as I should have put "./" in front of that).

> Are you sure you have the `v0.4.1`?

It seems that I downloaded the program from a wrong place, GitLab, and that the version I have is the latest that was available there, 0.2.2. I guess that explains the problem I experienced.  Perhaps it would be a good idea to put a more clear (for normal, non-techie people) warning to GitLab that the versions available there are old and shouldn't be used (unless one has a specific reason to use them). The sites like GitLab and GitHub are pretty overwhelming to normal (again, non-techie) people like me, so something that’s easily noticed or understood by a techie may be missed or not understood by others. 

Anyway, the program seems to have worked for me despite the old version I used, as my phone (Xiaomi Redmi Note 4 with MediaTek chipset, so stuck with Android 6.0) actually works now better than before, probably at least partly because there's more memory available. I'll change for the latest version of UAD, of course, and see how that works. 

Thanks for your help, and thanks for everybody involved in creating it for a useful program!

**Comment by 0x192** [comment]
> The section of the FAQ you are referring to is for MacOS. That's written in bold too...

Yes. The FAQ only applies to the latest UAD release.

> It seems that I downloaded the program from a wrong place, GitLab, and that the version I have is the latest that was available there, 0.2.2. I guess that explains the problem I experienced

Oh! That's a very old version indeed.

> Perhaps it would be a good idea to put a more clear (for normal, non-techie people) warning to GitLab that the versions available there are old and shouldn't be used

You're right. There is a warning [in the README](https://gitlab.com/W1nst0n/universal-android-debloater) but not in the release section. I'll downright archive the project.

> The sites like GitLab and GitHub are pretty overwhelming to normal (again, non-techie) people like me, so something that’s easily noticed or understood by a techie may be missed or not understood by others.

Yeah I agree. I find Gitlab especially confusing for newcomers. From the next version `v0.5` UAD will be able to self-update to it will be a lot easier for the users to keep UAD updated :)

> Thanks for your help, and thanks for everybody involved in creating it for a useful program!

:heart:
