### ISSUE TITLE
Better selection and deselection of entries.

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#133]
**Describe the feature you want**
A clear description of what you want to happen.

Allow deselecting all entries. If I have a package list for example if I want to have a default selection I have to rename the list file, then restart the program. If I had a clear all selection button or similar it would be awesome.

Add option to select entries with Shift.

**Comment by 0x192** [comment]
> Allow deselecting all entries.

Already implemented (c604d86). It will be available in the next release (`v0.5`) :wink:

**Comment by ghost** [comment]
Awesome!
