### ISSUE TITLE
Won't launch on HP

### ISSUE THREAD

**Issue by lawson85** [0x192/Universal-Android-Debloater#135]
**Describe the bug**

This version crashes when launching on a HP Compaq 610 (https://support.hp.com/us-en/product/compaq-610-notebook-pc/3958407/document/c01767233). All drivers are updated.

UAD 0.4.1 crashes and says to find another version, with both the openGL and the other version

**Expected behavior**

To just open

**You have a solution?**
What to do to fix the issue.

Maybe have one version that checks compatibility and adapts to work

**UAD log**
Upload the logfile generated by UAD.

isn't one

**Comment by 0x192** [comment]
Are you sure there is no log? Do you remember their location changed? ([see FAQ](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles-))

Are you on Windows? 

What is the exact message written in the console when you launch UAD from a terminal?

**Comment by lawson85** [comment]
I have checked and there are no logs. 
This is the actual error for OpenGL and normal version:
![image](https://user-images.githubusercontent.com/52282566/154450730-e99bbca2-c021-42a8-a59d-e42ae9d0d741.png)


PC specs are:
Processor	Intel(R) Core(TM)2 Duo CPU     T5870  @ 2.00GHz   2.00 GHz
Installed RAM	2.00 GB

System type	32-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	21H1 - getting 21h2 via update assistant
Installed on	‎06/‎07/‎2021
OS build	19043.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by genodeftest** [comment]
From the specs it looks like you are using a 32-bit operating system but UAD is only built for `x86_64`, i.e. 64-bit windows.
