### ISSUE TITLE
Affect to clock of Removing Xiaomi Service Framework

### ISSUE THREAD

**Issue by aritorhamo** [0x192/Universal-Android-Debloater#136]
**Your phone**: 
Xiaomi Redmi Note 4 (MediaTek) with Android 6.0 and MIUI Global 10.2

**Describe the issue**
As a response to a feedback request, when com.xiaomi.xmsf, (Xiaomi Service Framework) is removed from my phone, alarms do work even when the phone is in the silent mode. Another related point is a little confusing. When I made the test, at first the timer was affected in the way that when the time was full, the button to stop the alarm sound was not visible. I had to close the whole application to stop the alarm sound. That was still the case after I restarted the phone. But now, an hour later, after another restart (but without removing or configuring anything), I noticed that the timer had started to work normally too.

**Comment by KarlRamstedt** [comment]
Added this to a pull in the process of being merged.
You can close this now.
