### ISSUE TITLE
Misleading "pulling packages from the phone" notice on startup.

### ISSUE THREAD

**Issue by uKER** [0x192/Universal-Android-Debloater#142]
If ADB is not found in the path (be it the actual executable's path, or the PATH environment variable), the program just starts up and sits at "Pulling packages from phone".

Same thing happens if you start up with no phone connected.

The second situation should be pretty obvious to the user, but the first one can be particularly annoying, as the user (having their phone connected) might not know about the ADB requirement, which is only revealed if you get to reading the log file.

While we're at it, it would be nice to have something in the FAQ to begin with saying that you need to have ADB running and available in your path prior to running UAD.

**Comment by VeH-c** [comment]
Just Putting UAD in the Platform-Tool folder works FYI. that's what i do. also i notice some issues with the ADB sever & the  "Pulling packages from phone" message my self.

**Comment by 0x192** [comment]
Many changes have occurred since the creation of this issue. I forgot to close it.

- [The README](https://github.com/0x192/universal-android-debloater#how-to-use-it) explicitly says that you need ADB in your PATH
- UAD has a dedicated loading screen if it doesn't find a device
