### ISSUE TITLE
PSA: Samsung - disabling com.sec.sve breaks WiFi calls

### ISSUE THREAD

**Issue by mzanibelli** [0x192/Universal-Android-Debloater#143]
**Your phone**: SM-G960F

**Describe the issue**
With WiFi calls enabled and supported by the carrier (French carrier SFR for me), when making a call to a capable or non-capable recipient, the call instantly drops as soon as the recipient picks up.

**You have a solution?**
Enable `com.sec.sve` again.

Just wanted to let know anybody having a hard time with this. I initially noticed this by doing a bissection of all my manually disabled packages before I stumbled upon UAD. I see that UAD recommends disabling this package, which in some case could prevent an interesting feature from working.

Cheers, and thanks for making this cool tool.

**Comment by KarlRamstedt** [comment]
Are you sure it's com.sec.sve that causes the issues? Documentation calls that package "SecVideoEngineService", which should have nothing to do with Wi-Fi/VOIP calls.
Wi-Fi/VOIP calls usually have to do with `.ims` packages. Have you disabled any of those?

**Comment by mzanibelli** [comment]
Hello!
No I'm pretty sure: I can reproduce the problem by disabling it, rebooting, initiating a WiFi call: it stops as soon as my recipient picks up. Simply fixed by re-enabling it and rebooting (the reboot seems required though).
I really don't know why, and I 100% agree with you regarding the description. Might aswell be an interaction specific on my device... Even though I really don't have much installed.

What I didn't do: reproduce the bug with logcat open. Could help understanding what happens! I'll try to provide that in a few days.

**Comment by 0x192** [comment]
@mzanibelli 

> What I didn't do: reproduce the bug with logcat open. Could help understanding what happens! I'll try to provide that in a few days.

Do you have some time for this? :slightly_smiling_face:

**Comment by mzanibelli** [comment]
Hey! I finally could have a look at this today
[Here](https://gist.github.com/mzanibelli/f10b65afa1ff5d449f28defb53f11421) is the logcat dump.
I don't understand much here, not an Android developer at all.
But... You can see those `SecVideoEngineManager: SVE service is not ready!`.
As for why it's such a critical issue... :shrug:

**Comment by ChemMixer** [comment]
Hi, bumping this thread because I have the same issue. I found [a thread here](https://gitlab.com/W1nst0n/universal-android-debloater/-/issues/87) and using the text file from the last comment thread as a reference. Lastly leaving com.sec.sve package alone makes WiFi calling working again. Phone must be rebooted with com.sec.sve installed to ensure the WiFi calling function working.

Please remove com.sec.sve from Recommended list because WiFi calling is quite an important function for daily use.

**Comment by pbirokas** [comment]
Hi, 
I can also confirm on a S21 FE. 
Disabling the com.sec.sve app, breaks the VoWifi.

**Comment by 0x192** [comment]
Thanks you for your feedback!

`com.sec.sve app` is already in the `Expert` list. I've added a note stating it **will** break wifi-calling (instead of **may** break)
