### ISSUE TITLE
Cannot import .vcf contacts into Samsung contacts app without native file manager being present

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#147]
**Your phone**: Samsung Galaxy A52s 5G

**Describe the issue**
A clear and concise description of what the problem is.

Cannot import contacts into default Samsung contacts app (com.samsung.android.app.contacts) without Samsung file manager (com.sec.android.app.myfiles) as of Android 12. Contact not uses the default .documentsui to pick files, but rather the file manager for some reason.

**You have a solution?**
What to do to fix the issue.

Have the file manager installed when trying importing .vcf contacts on Android 12.

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.

**Comment by KarlRamstedt** [comment]
I.e: you're saying move the Samsung file manager: [Recommended] -> [Advanced]?
Which package is the file manager for you?

**Comment by KarlRamstedt** [comment]
[com.sec.android.app.myfiles is already in advanced](https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L6111).
Are you using an old version of UAD?

You can close this issue.

**Comment by ghost** [comment]
@KarlRamstedt Looking back, I meant to include this issue in the description of the package maybe? Just a heads up to people trying to remove this. I assume the package is already in Advanced tab.

**Comment by AnonymousWP** [comment]
> @KarlRamstedt Looking back, I meant to include this issue in the description of the package maybe? Just a heads up to people trying to remove this. I assume the package is already in Advanced tab.

You should then create an issue for that with the right template: https://github.com/0x192/universal-android-debloater/issues/new?assignees=&labels=package%3A%3Adocumentation&template=update-apps-description-or-recommendation.md&title=
