### ISSUE TITLE
Cannot open contact entries in Samsung Contacts app without AOSP blocked number storage

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#148]
**Your phone**: Galaxy A52s 5G

**Describe the issue**
A clear and concise description of what the problem is.

Tapping on contact entries in native Samsung Contacts without com.android.providers.blockednumber being present gives "Contact not found." text on Android 12.

**You have a solution?**
What to do to fix the issue.

Have afformentioned package installed if you want to use Samsung Contacts.

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.

**Comment by KarlRamstedt** [comment]
com.android.providers.blockednumber is already in advanced. Are you using an old version of UAD? Or did you uninstall anything more than the Recommended list?

In any case, you can close this issue.

**Comment by ghost** [comment]
@KarlRamstedt Is there a better way for me to report connections and breakage between packages? Are you currently maintaining a "required" or similar dependency tree for packages?

**Comment by KarlRamstedt** [comment]
@Etim-Orb oh, I thought you were recommending moving something from Recommended to something else.
If you just wanna add info to an existing description _just say so_.
You don't even need to use an Issue template for that, just say it directly for max clarity. For example:

> Title: Change description of com.android.providers.blockednumber
> Add this info to the existing description:
> > Disabling results in "Contact not found" when tapping on contact entries in Samsung Contacts in Android 12.

**Comment by ghost** [comment]
@KarlRamstedt Are you currently utilizing the neededBy flag? Because if you do I can make a pull request with these dependecies, you only need to tell me how to do the formatting.

**Comment by KarlRamstedt** [comment]
NeededBy is used in less than 1% of entries. I've even recommended removing it to the owner of this repo, because it's rarely useful and even when it could be it's less flexible than just using the description.

If you want i can add this:
> Disabling results in "Contact not found" when tapping on contact entries in Samsung Contacts in Android 12 (according to issue#148).

 To my list and make a pull request with it at a later date.

**Comment by ghost** [comment]
@KarlRamstedt That would be nice, yeah.
