### ISSUE TITLE
Stuck on "Pulling apps from the phone. Please wait..."

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#149]
Device is Realme GT Neo2 with Realme UI 2.0 (A.06) EU rom.

**Comment by 0x192** [comment]
Come on! What do you expect me to do with this? 

I don't have the time to help users who don't even bother to follow any issue template.

PS: You have a problem with ADB. [Check the logs](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles).
