### ISSUE TITLE
Number of apps currently displayed

### ISSUE THREAD

**Issue by rhayy** [0x192/Universal-Android-Debloater#150]
An indicator that can tell the current state of the phone.

It would be great if the software show how many apps are listed using the filters (user selected, list all/aosp/carrier/..., package all/enabled/..., removal all/recommended/...).

While redacting this issue, I can do it by "Select[ing] all" and read the number in the "Export current selection" button. It would be more convenient to dynamically print it somewhere in the UI.

By the way, how can I un-select all (other than refreshing the device)?

**Comment by KarlRamstedt** [comment]
Oh, this is a great idea. Just literally putting a parenthesis after the list name in the drop-down menu would do it.
For example:
> Enabled (55)
Disabled (7)
Uninstalled (0)

Unselect all is not a feature in the current version, but it has already been suggested multiple times, most recently in #145.

**Comment by rhayy** [comment]
[Fixed](https://github.com/0x192/universal-android-debloater/commit/136a5bac86cfd5db18c57a1f310910c51b00c708)
