### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by drmcnelson** [0x192/Universal-Android-Debloater#152]
The documentation (Readme) is not sufficient to know how to use this.   Please be more complete and more specific.

For example, it says install ADB.  Install it on the phone or the computer?  How?  From where?   And then what?   Does the GUI just appear after that, automatically?   And by the way, what is ADB, is that your software?

Where you say turn on debug mode, you should provide a link to more information about how to do that.   Not everybody knows what this means.

If you want people to be able to use it,  please fix the documentation.

Thank you

**Comment by KarlRamstedt** [comment]
Uuuhhm.. Click on the Windows text or arrow; it's an expandable section, links are provided in there. ADB is addressed there.

As for Debug mode, the only thing missing is how to enable Developer options, which is very easy to find how to on Google, but it certainly wouldn't hurt to have in the description.

**Comment by drmcnelson** [comment]
Thank you, that helps.

I see now that the ADB is the android tools package, and the next step is to download the GUI.    To make things more clear, the list of OS's should be indented under the line that says install the ADB. 

Aside, I am using Fedora with the Cinnamon desktop. 

It looks like the download is an executable?  

Do I just connect the phone and run that executable from the shell?  

It would be good to list the dependencies for the executable.

**Comment by KarlRamstedt** [comment]
> Do I just connect the phone and run that executable from the shell?

I guess you could? Or double-click it in your file browser? Just try it, it's not exactly rocket-science.

> It would be good to list the dependencies for the executable.

... they are listed. Literally just ADB, aside from a basic graphics system(Vulkan or OpenGL, depending on which executable you download), which doesn't warrant mention as it's expected for a working computer anyway..

**Comment by 0x192** [comment]
> If you want people to be able to use it, please fix the documentation.

UAD is far from being stable. The last release is `v0.4.1`. I don't expect nor I want a complete beginner to use it yet.

>  To make things more clear, the list of OS's should be indented under the line that says install the ADB.

You're right about that. I'll change that.

> It looks like the download is an executable?
Do I just connect the phone and run that executable from the shell?
It would be good to list the dependencies for the executable.

It is in fact an executable with no specific dependencies besides ADB (listed in the README) and OpenGL/Vulkan for the graphics but as @KarlRamstedt explained, there is no point listing those dependencies as the they comes with your graphic drivers (OpenGL only on older hardware)

When UAD will reach `v1.0` I'll try to submit it in major distro repositories`. For now it's only available in the[ AUR the Arch-based users](https://aur.archlinux.org/packages?O=0&SeB=nd&K=universal-android-debloater&outdated=&SB=p&SO=d&PP=50&submit=Go).

**Comment by drmcnelson** [comment]
I'm about 45 years into working with computer

**Comment by 0x192** [comment]
> I'm about 45 years into working with computer

I didn't mean to put you down. I was talking about android debloating in general. One can't be expert in all fields :slightly_smiling_face:

**Comment by 0x192** [comment]
I've just updated the README.

**Comment by drmcnelson** [comment]
Perhaps.   I have studiously avoided the guts of android and look 
forward to buying a linux cell phone.
