### ISSUE TITLE
MIUI 12.5.4.0 update causes bootloop

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#154]
Poco x3 nfc
I will tell it from the beginning. So, my already debloated phone (around 60 packages) got a system update (MIUI 12.5.4.0, security update apparently) and I installed the update. Then the phone restarted itself to finish the update, but it entered bootloop. I tried fixes and etc. but didn't work, so I had to factory reset. After setting the phone up again, I debloated (around 30 packages) and restarted the phone again to see if the bootloop was due to debloated packages, and boom, another bootloop. After another factory reset, this time I only uninstalled the apps that showed in app drawer and play store and restarted the phone(I didnt uninstall built-in system packages etc.) . This time there wasnt bootloop.  So, if your phone is debloated, dont update it. And if you are going to update, make backup of your files, contacts etc.

HERE IS THE PACKAGE LIST THAT CAUSED THE BOOTLOOP AND THE ONE THAT DOESNT CAUSE BOOTLOOP IF YOU HAVE THE SAME ISSUE AFTER UPDATING

[safe to uninstall.txt](https://github.com/0x192/universal-android-debloater/files/8188379/safe.to.uninstall.txt)
[caused bootloop.txt](https://github.com/0x192/universal-android-debloater/files/8188381/caused.bootloop.txt)

DAMN xiaomi, you caused me to lose my contacts and 2fa

**Comment by lawson85** [comment]
Most of those are safe to remove. What you can do is use an online diff tool to compare the two files. 

Also you should be able to backup and restore contacts and so on from Google/SIM card.

**Comment by ghost** [comment]
yeah my contacts etc. weren't saved to google or sim card. Idk if I am the only one who had this problem. With the new update, every time I debloated my phone, it got stuck on bootloop. So, I reduced the packages this time and didn't have any issues. And yeah they were safe to remove before, I had like 60 packages uninstalled already.

**Comment by ghost** [comment]
Same here, after got February security update (MIUI v12.5.3.0).
Redmi 9 Lancelot.

Glad it's just my secondary phone.

**Comment by 0x192** [comment]
@gdnzz @chapters1000 

I checked the diff. Are you saying that removing **any** of the following packages causes bootloop on MIUI 12.5.4.0+ ?

```
com.android.dreams.basic
com.android.dreams.phototable
com.android.htmlviewer
com.android.providers.partnerbookmarks
com.milink.service
com.miui.backup
com.miui.bugreport
```
Can you both confirm this list ? The first 4 seem strange.

**Comment by lawson85** [comment]
I don't know if this helps: https://piunikaweb.com/2021/04/19/miui-12-miui-12-5-bloatware-can-now-be-removed-directly-from-browser

**Comment by ghost** [comment]
> @gdnzz @chapters1000
> 
> I checked the diff. Are you saying that removing **any** of the following packages causes bootloop on MIUI 12.5.4.0+ ?
> 
> ```
> com.android.dreams.basic
> com.android.dreams.phototable
> com.android.htmlviewer
> com.android.providers.partnerbookmarks
> com.milink.service
> com.miui.backup
> com.miui.bugreport
> ```
> 
> Can you both confirm this list ? The first 4 seem strange.

sorry... i can't.
just switched to lineageos.

**Comment by 0x192** [comment]
> sorry... i can't. just switched to lineageos. 

I mean... you were right! MIUI is a horror.

**Comment by camelCase1492** [comment]
Xiaomi Poco X3 Pro NFC, Android 11: Seems like updating MIUI does break some stuff. Updating from MIUI 12.5.5 to some MIUI 13.x did cause a soft brick and had to wipe data and return to 12.5.5. All of these (except `com.android.htmlviewer`) were removed successfully on MIUI 12.5.5, no issues when rebooting:

> ```
> com.android.dreams.basic
> com.android.dreams.phototable
> com.android.htmlviewer
> com.android.providers.partnerbookmarks
> com.milink.service
> com.miui.backup
> com.miui.bugreport
> ```

Wouldn’t recommend removing `com.android.htmlviewer` as it is required by some apps such as Reddit to open some websites in-app, also by settings to log in to a network when connecting to an open Wi-Fi

**Comment by ghost** [comment]
> @gdnzz @chapters1000
> 
> I checked the diff. Are you saying that removing **any** of the following packages causes bootloop on MIUI 12.5.4.0+ ?
> 
> ```
> com.android.dreams.basic
> com.android.dreams.phototable
> com.android.htmlviewer
> com.android.providers.partnerbookmarks
> com.milink.service
> com.miui.backup
> com.miui.bugreport
> ```
> 
> Can you both confirm this list ? The first 4 seem strange.

I can't test again, this is my main phone. But yeah, I shared the lists

**Comment by ghost** [comment]
Oh someone already addressed the issue, closing it #169

**Comment by gdnzz** [comment]
I also had the

**Comment by 0x192** [comment]
@camelCase1492 

Thanks for your help!

**Comment by mbrav** [comment]
> Wouldn’t recommend removing `com.android.htmlviewer` as it is required by some apps such as Reddit to open some websites in-app, also by settings to log in to a network when connecting to an open Wi-Fi

Yes, can confirm. Got a boot loop when removing `com.android.htmlviewer` a day ago.

**Comment by 0x192** [comment]
New Release [`v0.5`](https://github.com/0x192/universal-android-debloater/releases) is out! :rocket: 

This is a really big release with a huge review of the recommendations. There should be a lot less issues like this (even though this is really weird that `com.android.htmlviewer` causes a bootloop) and starting from `v0.5`, the debloat lists are directly downloaded from Github so you don't have to wait for a new release to use the latest debloat lists.

**Comment by mbrav** [comment]
@0x192 Thank you so much for developing this app, it is really useful and very well built! Just started using it a few days ago and am now considering staying with a debloated Mi 10 Lite for some time before unlocking and switching to a Custom ROM like lineageOS 19. Usually I start unlocking a new Xiaomi phone as soon as I get it, but your tool makes it possible to at least consider staying with MIUI, since it is one of the best official ROMS, except for the ridiculous amount of bloat, telemetry and spyware which your app helps to remove without crashing the phone.

Wish you and the team the best of luck! @KarlRamstedt @rar0ch

**Comment by KarlRamstedt** [comment]
I dunno if I'd call it a team, I just try to help out sometimes 😅
