### ISSUE TITLE
Copyable text from app description

### ISSUE THREAD

**Issue by UnrealKaraulov** [0x192/Universal-Android-Debloater#159]
Need Copyable text from app description (For copy it and using google translate to translate needed language)

**Comment by KarlRamstedt** [comment]
This issue is a duplicate of #43. You can close this.

This is something the author wants in UAD, but isn't supported by the GUI system.

**Comment by UnrealKaraulov** [comment]
> This issue is a duplicate of #43. You can close this.
> 
> This is something the author wants in UAD, but isn't supported by the GUI system.

This is not support by author, GUI system not guilty of it!

**Comment by KarlRamstedt** [comment]
...what? Go read issue 43, which I linked in my last comment. All info is there.
