### ISSUE TITLE
Two small changes please

### ISSUE THREAD

**Issue by groston** [0x192/Universal-Android-Debloater#160]
In the readme information, I was unable to find anything which tells one how to actually use the software! Everything about setting up the host is well described, but nothing about actually using this program.

In terms of the bloatware to be removed, on my phone, I see package that look like com.felicanetworks.* and I strongly suspect that these are bloatware. However, this tool does not remove them. I feel that these should be added (unless someone can explain why they are needed).

Thanks.

**Comment by KarlRamstedt** [comment]
> nothing about actually using this program

I'd say the functionality is pretty straight-forward. You click on disable/uninstall on the package you wanna.. disable/uninstall.
What part of using UAD is unclear to you?

> I see package that look like com.felicanetworks.* and I strongly suspect that these are bloatware. However, this tool does not remove them.

Are you saying it's not a part of the Recommended list?

Seems like it's a package related to RFID card reading. https://en.wikipedia.org/wiki/FeliCa
Might not be a good fit for Recommended as some could consider it important.

**Comment by groston** [comment]
Karl,
 
Thanks for a response, and a super-fast one at that.
 
With regard to the functionality: Perhaps my original statement was not stated clearly. Even though I have been writing code for 40+ years (seriously!), the language Rust is entirely new to me (and perhaps many others). While using the program appears to be straight-forward, I haven’t any idea how to get from the files I downloaded to a program that I can run on my PC. This is what I meant by ‘using the program”.
 
With regard to felicanetworks: My reading had suggested, to me, that it is bloatware. However, based on your comments, I did some more looking and am now not sure. But, you know this stuff much better than do I, so I will leave it alone.
 
----
 
Gerry Roston
 ***@***.***> ***@***.***
734-516-6715

**Comment by KarlRamstedt** [comment]
Er.. UAD is a GUI application, there's no coding involved in using it.
All the requirements are listed in the Readme. You basically just need ADB (from Android Platform-Tools, which is linked in the Readme). After you have ADB just run the UAD executable and connect your Android device.

**Comment by groston** [comment]
Maybe I am just being stupid, but I did not see anything that looks like an executable in the zip file https://github.com/0x192/universal-android-debloater/archive/refs/heads/main.zip ...
 
----
 
Gerry Roston
 ***@***.***> ***@***.***
734-516-6715

**Comment by KarlRamstedt** [comment]
You need to go to releases. Grab the normal version for your OS, only go for OpenGL if normal version(Vulkan) has issues for you.
https://github.com/0x192/universal-android-debloater/releases

Downloading the zip file of the repo will only get you the source code, which you'd need to build yourself to get an executable file.

**Comment by 0x192** [comment]
The [`How to use section`](https://github.com/0x192/universal-android-debloater#how-to-use-it) in the README seems pretty straightforward to me. What do you find confusing?

**Comment by KarlRamstedt** [comment]
@0x192 The only thing that wasn't immediately obvious to me was that the platform names(+arrow) are an expandable section. Aside from that I personally think it's good.

**Comment by 0x192** [comment]
The README now tells people to click on the spoiler to see the instructions (#249)
