### ISSUE TITLE
Additional packages to remove from Samsung phones

### ISSUE THREAD

**Issue by winniethepoohbear** [0x192/Universal-Android-Debloater#161]
Please consider adding a way to remove these apps. They come preinstalled after Samung and Google updates on new devices. 

**Your phone:** Samsung A20

**Packages:**
```
com.king.candycrushsodasaga
com.tripledot.solitaire
net.supertreat.solitaire
air.com.playtika.slotomania
com.handmark.expressweather
com.zhiliaoapp.musically
com.staplegames.blocksClassicSGGP
in.playsimple.tripcross
com.tripledot.woodoku
com.digitalturbine.toolbar
com.samsung.android.app.watchmanager
com.google.android.music
com.pandora.android
com.google.android.videos
com.google.android.apps.photos
com.samsung.android.oneconnect
com.sec.android.app.shealth
com.samsung.oh
...
```
- [X] **I removed all those packages on my phone**

## Document each package the best you can

com.digitalturbine.toolbar - Digital Turbine. Ads and used by carriers to install other apps

com.king.candycrushsodasaga - Game. Candy Crush Soda Saga
com.tripledot.solitaire - Game. Solitare
net.supertreat.solitaire - Game. Solitaire Grand Harvest
air.com.playtika.slotomania - Game. Slotomania™ Casino Slots Games
com.staplegames.blocksClassicSGGP - Game. Block Puzzle
in.playsimple.tripcross - Game. Crossword Jam
com.tripledot.woodoku - Game. Woodoku

com.handmark.expressweather - 1Weather app
com.zhiliaoapp.musically - TikTok app
com.pandora.android - Pandora app
com.samsung.oh - Samsung Members app
com.sec.android.app.shealth - Samsung Health app
com.samsung.android.app.watchmanager - Samsung Wearable app
com.samsung.android.oneconnect - Samsung SmartThings app
com.google.android.music - YouTube Music app
com.google.android.videos - Google TV app
com.google.android.apps.photos - Google Photos app

**Comment by 0x192** [comment]
Thanks for your help. 

I removed 8  packages from your list because there are already documented in [`uad_lists.json`](https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json). Here are the ones we need to add:
```
com.tripledot.solitaire
net.supertreat.solitaire
air.com.playtika.slotomania
com.staplegames.blocksClassicSGGP
in.playsimple.tripcross
com.staplegames.blocksClassicSGGP
in.playsimple.tripcross
com.tripledot.woodoku
com.digitalturbine.toolbar
com.pandora.android
```

**Comment by 0x192** [comment]
@winniethepoohbear 

I'm finally coming back to you! 

Can you upload the `com.digitalturbine.toolbar` APK please?

```bash
adb shell pm path com.digitalturbine.toolbar # return the path of the app
adb pull <path> # fetch the APK from the phone
```
