### ISSUE TITLE
No Mobile data network after debloat with UAD

### ISSUE THREAD

**Issue by SwiftyPop** [0x192/Universal-Android-Debloater#162]
**Your phone**: 
[Vivo V9](https://www.gsmarena.com/vivo_v9-9117.php)

**Describe the issue**
My phone recently debloated and now has no mobile data network; however, wi-fi works perfectly. The notice in the top notification read, "`SIM card is disabled I Emergency call only`." I tried to turn it on in the settings, but it turned off right away. As far as I recall, I eliminated all UAD recommended apps and Touchpal keyboard bloats (com.cootek.xx).

I believe UAD has removed more than 60 apps as a result of its use. Thanks :3

**You have a solution?**
I don't have any.

**UAD log**
[UAD_20220131.log](https://github.com/0x192/universal-android-debloater/files/8237486/UAD_20220131.log)
[UAD_20220312.log](https://github.com/0x192/universal-android-debloater/files/8237487/UAD_20220312.log)

**Comment by lawson85** [comment]
Maybe restore: com.qualcomm.qti.callfeaturessetting, com.qualcomm.qti.remoteSimlockAuth,

**Comment by SwiftyPop** [comment]
@lawson85 I restore those 2 app and after restart, it don't seem to fix it. I tried enable the SIM in settings but it turn off right away like before.

**Comment by lawson85** [comment]
If you look in your logs, there are loads that are in the unlisted 
category, I would strongly recommend restoring those packages. Also, you 
can use Logcat to determine the error

**Comment by 0x192** [comment]
Try restoring `com.qualcomm.qti.lpa` and reboot.

If this doesn't fix the issue, try restoring other Qualcomm packages (then OEM packages) until you find the faulty package(s).

Keep us informed!

**Comment by 0x192** [comment]
@SwiftyPop ?

**Comment by Mehdi-13** [comment]
i had the same issue on my mi 9t pro,
restoring qualcomm packages fixed this problem.

> Try restoring `com.qualcomm.qti.lpa` and reboot.
> 
> If this doesn't fix the issue, try restoring other Qualcomm packages (then OEM packages) until you find the faulty package(s).
> 
> Keep us informed!

**Comment by SwiftyPop** [comment]
@0x192 I apologise for the extremely delayed response, but I did format my phone at the time and tried this again; the problem doesn't appear to exist now. It could have been my mistaken choice of an unlisted app or something else.
