### ISSUE TITLE
UAD doesn't load completely

### ISSUE THREAD

**Issue by m-henzo** [0x192/Universal-Android-Debloater#163]
I've enabled developer option on phone, enabled usb debugging on phone, added adb to Path, disconnected from all accounts.

In CMD ive run 'adb devices' and my device is displayed but beside it it says "unauthorized".

[UAD_20220315.log](https://github.com/0x192/universal-android-debloater/files/8251268/UAD_20220315.log)

log says ADB not found.

not sure what to do as I have installed platform-tools_r33.0.0-windows.

Thank you in advance.

**Comment by lawson85** [comment]
When plugin in your device, change it to file transfer mode, make sure the USB debugging notification shows and try again. It will then ask you to grant access on the phone screen.

**Comment by m-henzo** [comment]
I had to change the usb settings on the device to get that pop-up to come up. Thank you!! :}
