### ISSUE TITLE
Unable to detect my phone after plugin to the USB Pocophone F1

### ISSUE THREAD

**Issue by rainings** [0x192/Universal-Android-Debloater#166]
**Describe the bug**
The tool never detect my phone when I plugin. I've done this:
1. Enable developer option
2. Enabled USB debugging
3. Select FTP transfer when plugin

I've tried both uad_gui-windows.exe and windows-opengl.exe still doesn't detect my phone.
I've tried the debloater tool below, it can detect my phone & works without any issue.
https://github.com/Szaki/XiaomiADBFastbootTools

**Environment**
**OS:** Windows 10 21H2 Build 19044.1586 
**Phone:** Xiaomi Pocophone F1 (Unlocked & Rooted)
**ROM:** Official Global Stable ROM 12.0.3.0.QEJMIXM [https://bigota.d.miui.com/V12.0.3.0.QEJMIXM/miui_POCOF1Global_V12.0.3.0.QEJMIXM_cf3fccffce_10.0.zip](ROM Download)
It just doesn't detect my phone when I plug it in.

**Comment by runninghamster0** [comment]
Please check that the folder containing adb.exe is added to your system path in Windows.
A guide:
https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

Also, make sure your phone is plugged in prior to launching the app, and that the computer is trusted for USB debugging.

**Comment by rainings** [comment]
@runninghamster0 I have Minimal ADB and Fastboot-v1.4.3 installed, do I still need to install another adb?
This is my system path in Windows.
![Screenshot_1](https://user-images.githubusercontent.com/7414544/158958396-e4a8237b-97fd-4116-8c7b-6d0a01fdc3a3.jpg)

> Also, make sure your phone is plugged in prior to launching the app, and that the computer is trusted for USB debugging.

Tried this, not working.

**Comment by runninghamster0** [comment]
> @runninghamster0 I have Minimal ADB and Fastboot-v1.4.3 installed, do I still need to install another adb?
> This is my system path in Windows.
> ![Screenshot_1](https://user-images.githubusercontent.com/7414544/158958396-e4a8237b-97fd-4116-8c7b-6d0a01fdc3a3.jpg)
> 
> > Also, make sure your phone is plugged in prior to launching the app, and that the computer is trusted for USB debugging.
> 
> Tried this, not working.
> 
> 

Minimal ADB & Fastboot installer places the ADB executable in the folder
`C:\Program Files (x86)\Minimal ADB and Fastboot\`
Add this location to your system path and it should work after that.

**Comment by rainings** [comment]
@runninghamster0 it works now! Excellent thx!
Not sure why the path was not added from the beginning. Maybe this app can include ADB to avoid this issue?
Or add this to Wiki if ppl face such issue know how to solve it
