### ISSUE TITLE
com.android.htmlviewer causes bootloop in MIUI 12.5.5.0

### ISSUE THREAD

**Issue by Matblanket** [0x192/Universal-Android-Debloater#169]
Poco X3 NFC (Xiaomi) Miui 12.5.5.0

My phone went into bootloop today after updating the os. So after resetting i ran the debloat recommended list. After debloating, trying to restart would again initiate the bootloop.

I narrowed it down to com.android.htmlviewer. I can confirm that uninstalling it in poco x3 will initiate a bootloop.

Let me know, if any additional testing is required.

**Comment by camelCase1492** [comment]
I too have a Poco X3 Pro NFC with MIUI 12.5.5
See my comment on issue [#154](https://github.com/0x192/universal-android-debloater/issues/154#issuecomment-1079001362)
`com.android.htmlviewer` is important for some apps that open a webpage in-app and also for settings to log in to an open WiFi such as that of an airport. Should not be removed IMO and should be listed as `Advanced`

**Comment by Matblanket** [comment]
Did uninstalling com.android.htmlviewer not cause a bootloop for you?
Your comment on the other issue makes it sound like it didn't.

**Comment by Matblanket** [comment]
Also, rebooting after uninstalling com.qualcomm.qcrilmsgtunnel will break calling through a sim card.

**Comment by camelCase1492** [comment]
> Did uninstalling com.android.htmlviewer not cause a bootloop for you?
> Your comment on the other issue makes it sound like it didn't.

I didn’t try uninstalling it as I’d lose functionality that I care about.

**Comment by ghost** [comment]
I had the same issue. Thanks for your efforts to find the package causing the problem.

**Comment by 0x192** [comment]
@Matblanket & @camelCase1492 

Thanks you! 

I moved `com.android.htmlviewer` to the `Expert` list and added a warning.

**Comment by FahadBinHussain** [comment]
> Poco X3 NFC (Xiaomi) Miui 12.5.5.0
> 
> My phone went into bootloop today after updating the os. So after resetting i ran the debloat recommended list. After debloating, trying to restart would again initiate the bootloop.
> 
> I narrowed it down to com.android.htmlviewer. I can confirm that uninstalling it in poco x3 will initiate a bootloop.
> 
> Let me know, if any additional testing is required.

I confirm the same on Xiaomi 11i HyperCharge, is there any way to fix this without reset?
