### ISSUE TITLE
Add android auto to debloat recommended

### ISSUE THREAD

**Issue by oczt** [0x192/Universal-Android-Debloater#172]
**Your phone:**  Pixel 3

**Packages:**
```
com.google.android.projection.gearhead
...
```
- [X] **I removed all those packages on my phone**
Just works

## Document each package the best you can
**List**: `Google`
**Removal**: `Recommended`

### \<package name\>
**List**: \<list\> 
**Removal**: \<recommendation list\>
> Description. [Link to its Playstore page if it exists.](https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead&hl=en&gl=US)

**Comment by 0x192** [comment]
This package is already in the [`uad_lists.jsont`](https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L17265=) and recommended to remove :slightly_smiling_face:
