### ISSUE TITLE
Games and Shelf apps in OP 9 Pro

### ISSUE THREAD

**Issue by DarkSkull91** [0x192/Universal-Android-Debloater#173]
**Your phone:** OnePlus 9 Pro

**Packages:**
```
com.oneplus.opshelf
com.oplus.games
```
- [x] **I removed all those packages on my phone**

## Document each package the best you can
**List**: `Oem` 
**Removal**: `Recommended`

They are useless and safe to remove, tested on my phone for about two weeks.

**Comment by 0x192** [comment]
Thanks for your report and sorry for the really late replay. It's finally merged :tada:
