### ISSUE TITLE
Debloating causing System space to fill-up

### ISSUE THREAD

**Issue by arafe-zawad-sajid** [0x192/Universal-Android-Debloater#175]
**My phone**: OnePlus 6 (A6000)

**The issue**
I used "Universal Android Debloater" to uninstall some bloats but instead of freeing up my space, it's actually hogging more space. Apparently, after uninstalling the bloats, the System space is getting filled up for some reason.

**Comment by 0x192** [comment]
This seems very unlikely because UAD only uses ADB commands and if those commands don't have the expected behavior on your phone, then you have bigger problems.

Can you backup this claim with some evidence? I can't really do anything with so few details anyway

**Comment by lawson85** [comment]
Try using this app to see what the issue is: https://play.google.com/store/apps/details?id=com.google.android.diskusage
You can also use SD maid to clean out your system: https://play.google.com/store/apps/details?id=eu.thedarken.sdm

**Comment by arafe-zawad-sajid** [comment]
Unfortunately, after that incident, I reset my phone and erased everything. And I haven't kept screenshots for it. 
But after the reset I used the debloater again and it worked fine this time. Faced no such issue as before.
