### ISSUE TITLE
Unable to uninstall any packages on Mi 9T Failure [-1000]

### ISSUE THREAD

**Issue by lzan98** [0x192/Universal-Android-Debloater#182]
Failure [-1000]

<img width="565" alt="Screenshot 2022-04-05 at 18 55 35" src="https://user-images.githubusercontent.com/66457036/161739128-e3108ab0-2e73-4277-b9da-f0c8eb82d7b6.png">

**Comment by 0x192** [comment]
Yeah I'm aware of this. That sucks. It's Xiaomi which prevents you to remove their crappy apps.

Does it works if you switch to disable mode? There is an option called `Clear and disable packages instead of uninstalling them` in the settings.

**Comment by lzan98** [comment]
Yup I googled and figured out it was a Xiaomi thing. Forgot to close this issue. Apologies.

Great work!
