### ISSUE TITLE
disabling Wi-Fi test bring exlamention mark on wifi icon and error in manual private DNS check 

### ISSUE THREAD

**Issue by giostark** [0x192/Universal-Android-Debloater#185]
**Your phone**: Note20U (samsung)  (android 12 UI4.1)

**Packages documentation to update:**
```
com.sec.android.app.wlantest
```
**Documentation change:** There is already linked the wiki

**package name:** Wlan Test (com.sec.android.app.wlantest)

**Current description** (the copy past from the linux desktop app dont work. The text is not selectable,  so please see the already existing description)
> Wlan Test   .....  /Wireless_LAN) 

**Proposed description**
> Wlan Test   .....  /Wireless_LAN)  
(add this)
Disabling this test will rise the exclamation mark on the WI-Fi icon and will show the message "Unable to connect to the host" in:
Settings - Connections - more connections settings - Private DNS - provider hostname.
The connection seems to work despite those esthetic errors.

**Comment by 0x192** [comment]
Thanks you for your contribution! :slightly_smiling_face:
