### ISSUE TITLE
Xiaomi debloating - the need to log in to the xiaomi account

### ISSUE THREAD

**Issue by jirafey** [0x192/Universal-Android-Debloater#190]
**Your phone**: \<phone model\>
Xiaomi (not my phone, no idea, anyways not important here)

**Describe the issue**
Xiaomi requires verification after debloating reccomended. Xiaomi account, phone number of the phone that is debloated/email and password. It may be really easy to forget the password. 

**You have a solution?**
Add info that a user before debloating should try to log in to the Xiaomi account that is used on the phone. :) There are workarounds here and there but one can easily not use the phone  anymore after debloating. It could be under the also chinese information in this repo :)

**UAD log**

- not important here

**Comment by 0x192** [comment]
> Add info that a user before debloating should try to log in to the Xiaomi account that is used on the phone.

Log in? You mean log out, no? Is it the same as #176?

**Comment by jirafey** [comment]
> > Add info that a user before debloating should try to log in to the Xiaomi account that is used on the phone.
> 
> Log in? You mean log out, no? Is it the same as #176?

Oh yes the screen with the xiaomi account. If this wont happen then the issue is closed :)
