### ISSUE TITLE
exporting current installed/enabled/disabled/uninstalled apps/processes.

### ISSUE THREAD

**Issue by jirafey** [0x192/Universal-Android-Debloater#191]
**Describe the feature you want**
A clear description of what you want to happen.
so i could just load the file there and it has all the things i enabled/disabled. If for some reason i want to safely boot the device wihtout bootloop, I want to reenable most of the normal things, then just load all the things i have.

or just being able to make a folder/profile with the things enabled/disabled

**Comment by 0x192** [comment]
Useful feature I agree. This is on the roadmap:  I want to save the state of all the phone's package in a file and be able to come back to this state easily with UAD.

Closing this issue in favor of #199 which is the same idea.
