### ISSUE TITLE
[UX] Improve export selection feature

### ISSUE THREAD

**Issue by jirafey** [0x192/Universal-Android-Debloater#192]
**Describe the bug**
it should create something or what is it supposed to do?

**Expected behavior**

A file with the seleciton.

**You have a solution?**
no

**UAD log**
Upload the logfile generat
[UAD_20220410.log](https://github.com/0x192/universal-android-debloater/files/8458687/UAD_20220410.log)
ed by UAD.

**Comment by 0x192** [comment]
I acknowledge that this feature is not really user-friendly right now. A `uad_exported_selection.txt` file is generated in the same directory as the UAD binary. 
When you start UAD it automatically selects the packages found in this file. 

I'll improve the UI to display the location file and explain the feature.

**Comment by onguarde** [comment]
second this, was clicking the export multiple times, nothing happened. Took some online searching and chance to find out that it's in the same directory.
