### ISSUE TITLE
BOOTLOOP: com.google.android.ext.services causes bootloop

### ISSUE THREAD

**Issue by jirafey** [0x192/Universal-Android-Debloater#194]
**Your phone**: \<phone model\>
samsung a52s 5g Android 12
**issue:**
EXPERT GOOGLE
bootloop after uninstalling the "com.google.android.ext.services"

# Current text

![Screenshot_14](https://user-images.githubusercontent.com/97115044/162616347-4d12acad-6eb2-44b7-92fd-714a0ea29444.png)

**UAD log**
[UAD_20220410.log](https://github.com/0x192/universal-android-debloater/files/8459029/UAD_20220410.log)
cannot uninstall 4 left google services wiothout the com.google.android.ext.services
[UAD_20220410.log](https://github.com/0x192/universal-android-debloater/files/8459072/UAD_20220410.log)

# Solution:

 Move to unlisted or:

 Add that it bootloops Android 12 samsung, (in the information in uad) with capslock of course!

# EDIT:
Just this com.google.android.ext.services with 5 unlisted google processes/apps is the full requirement for the phone not to bootloop(at least just google). I uninstalled system webview and pakcage installer, it works fine

# EDIT:
to replicate:
do not uninstall recommended
leave out of all google from advanced to expert:
system web view google, google package installer, com.google.android.ext.services
web view and package installer seems to just reappear in the uad after refreshing.
another:

uninstalling recommended seems to cause bootloop nonetheless (just 8 google apps enabled is not enough when you uninsrtall recommended i guess some depend on them and advanced and expert ones got confused.)

also add recommended: bootloop

These enabled: no bootloop. I guess I'm done for today. You can just warn someoene against uninstalling more than i have in google, just in case they don't want a bootloop.
Safe:

![rec](https://user-images.githubusercontent.com/97115044/162619619-e8e43ba9-9cc8-440d-8371-eec8436df9b8.png)
- shared google library needed to uninstall more google apps
![next reboot](https://user-images.githubusercontent.com/97115044/162620354-8196e9e4-7c74-4a4c-bb0c-5ed207e9f50d.png)
![Screenshot_16](https://user-images.githubusercontent.com/97115044/162620356-9df05934-e75d-424d-86cd-c8f269f46eca.png)

![oem ex](https://user-images.githubusercontent.com/97115044/162619622-9212a6a8-e8d9-4eef-bd95-5bd6b5f11294.png)
![oem adv](https://user-images.githubusercontent.com/97115044/162619623-fb223be2-cddb-489f-b2e4-872d84581dde.png)
![oem adv2](https://user-images.githubusercontent.com/97115044/162619624-112ebfd8-04c7-4d3f-b08d-683683be8e69.png)

Final: these are the stuff that i have enabled and mitigated the bootloop.

![fianl](https://user-images.githubusercontent.com/97115044/162622678-3733d6e8-da7c-410d-8fd9-015e40a849a7.png)
![fianl2](https://user-images.githubusercontent.com/97115044/162622685-973403e0-a315-42b1-bfa0-05e76a18393d.png)
![fianl3](https://user-images.githubusercontent.com/97115044/162622688-c2feb019-12fe-44d0-adb0-478be0d04902.png)
![fianl4](https://user-images.githubusercontent.com/97115044/162622692-21651acd-ebf3-45ac-bf6d-360c415fd897.png)
![fianl5](https://user-images.githubusercontent.com/97115044/162622694-f3abf71f-c443-4295-bbbd-e7928ebf171f.png)
![fianl6](https://user-images.githubusercontent.com/97115044/162622707-9d7a8bdf-ab5b-4798-a26b-3a235a2ea520.png)

![fianl7](https://user-images.githubusercontent.com/97115044/162622698-04a10a99-84e3-4d58-9de4-3ca5218841de.png)

![fianl8](https://user-images.githubusercontent.com/97115044/162622700-2a23e1e3-2e03-444c-bc53-2f51cd87f70e.png)
![fianl9](https://user-images.githubusercontent.com/97115044/162622703-4341852e-048f-4c36-acac-48fb19cc0193.png)
![fianl10](https://user-images.githubusercontent.com/97115044/162622705-c6161545-10eb-41ab-8471-c1301f57b78a.png)

Another thing disabling all the google ones without the mentioned com.google.android.ext.services not possible
Also wallpaper bloatware not possible to uninstall. Game optimization service and the themes are not possible to uninstall at least those that are enabled in the last 10 screenshots above
log for the last:
[UAD_20220410.log](https://github.com/0x192/universal-android-debloater/files/8459166/UAD_20220410.log)

**Comment by jirafey** [comment]
sorry for such a big thing here. I hope the that the ext will be tested for bootloop. Not sure if it will bootloop any other devices I don't want to risk anymore. Maybe that will be helpful for someone, you are welcome to close it.

**Comment by 0x192** [comment]
Not sure to understand all those edits.

Does only removing `com.google.android.ext.services` bootloop your phone? That the main point.

**Comment by jirafey** [comment]
> Not sure to understand all those edits.
> 
> Does only removing `com.google.android.ext.services` bootloop your phone? That the main point.

Well im pretty sure it did. I would say that just a maybe a bootloop is worth putting into the info. Now I do not remember it clearly but the moment I didnt have it the phone was in a bootloop its like 75% bootloop. Sorry I was really exhausted. This software should just warn the users about such a possibility. 

Though don't really know if it was the only thing that caused the bootloop I think I uninstalled more than just that.

**Comment by 0x192** [comment]
[This has already been reported in the old UAD in bash...](https://gitlab.com/W1nst0n/universal-android-debloater/-/issues/43 ) :facepalm:
