### ISSUE TITLE
Phone Not Detected

### ISSUE THREAD

**Issue by MintyHardship** [0x192/Universal-Android-Debloater#200]

**Comment by 0x192** [comment]
I no longer help users which don't even bother to follow the bug report template.

Did you really read the [How to use](https://github.com/0x192/universal-android-debloater#how-to-use-it=) section of the README? 

How do you think I can help you without logs?

**Comment by Arbiterz** [comment]
Yes I have read the FAQ Developer options are turned on, USB debugging is turned on and I don't have an OEM account connected to my phone. Plugging in the phone the computer detects that it is connected but not the UAD app. I should have included this with my original post.
