### ISSUE TITLE
Phone not found and scaling issue (WGPU)

### ISSUE THREAD

**Issue by Ki-er** [0x192/Universal-Android-Debloater#204]
**Describe the bug**
Displays no apps when phone is connected
Dropdown menu scaling issues with numbers

Edit: Note 20 Ultra is connected at the time of this bug
Edit Edit: Also happens with and without ADB Installed for samsung.

**Expected behavior**
The software should display apps to remove.

**You have a solution?**
N/A

**UAD log**
Upload the logfile generated by UAD.
[UAD_20220416.log](https://github.com/0x192/universal-android-debloater/files/8500084/UAD_20220416.log)
![byHimr89rk](https://user-images.githubusercontent.com/32241933/163678967-d6ce9255-7cd4-4d25-9639-1edc78ca69fc.gif)

**Comment by Ki-er** [comment]
This only happened with the default windows app, opengl loaded fine without clipping however no phone picked up
![2TOlWHr7d5](https://user-images.githubusercontent.com/32241933/163679885-c1c4d10b-9ad0-4879-bb02-1374f48ea8d1.gif)

**Comment by smtgpm** [comment]
did you add adb to your environement path ?

**Comment by 0x192** [comment]
Sorry for the very late reply!

The scaling issue is a bug in your Vulkan drivers or  [WGPU](https://github.com/gfx-rs/wgpu). Just use the OpenGL version :slightly_smiling_face: 

As for your phone detection issue, you need to add the ADB directory to your PATH as stated in the README (which is meant to be... read :roll_eyes:)

> Download [android platform tools](https://dl.google.com/android/repository/platform-tools-latest-windows.zip) and unzip it somewhere. [Add the folder to your PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/).
>
> [Install USB drivers for your device](https://developer.android.com/studio/run/oem-usb#Drivers)
>
> Check your device is detected:
>
>    ```
> adb devices
> ```

https://github.com/0x192/universal-android-debloater#how-to-use-it
