### ISSUE TITLE
Joyose on MIUI

### ISSUE THREAD

**Issue by CanerKaraca23** [0x192/universal-android-debloater#207]
**Describe the bug**
Joyose on MIUI, com.xiaomi.joyose is an essential package for game turbo feature also manages SMS features.

**Expected behavior**
-

**You have a solution?**
Remove this app from list or add a description like this: "Joyose is a system app that manages native support for SMS but it is also an essential for gaming and game turbo booster systems. Many have tried removing this app and some encountered issues like not receiving SMS texts on time, or performance issues during games and such. So, it is recommended that you leave this app alone."

**UAD log**
Upload the logfile generated by UAD.
-

**Comment by ll0r3nt3** [comment]
+1

**Comment by HiQual** [comment]
com.xiaomi.joyose does not cause any sms ( or other ) problems when removed from my RN10Pro or RN9Pro using latest EEA stable MIUI.

**Comment by ll0r3nt3** [comment]
> com.xiaomi.joyose does not cause any sms ( or other ) problems when removed from my RN10Pro or RN9Pro using latest EEA stable MIUI.

Only affect to game launcher and qualcomm options (antialising, limit gpu to frame, etc)

**Comment by jrafaelmdo** [comment]
+1
I can confirm that disabling or removing com.xiaomi.joyose affects GPU turbo functionally of the GAME turbo/launcher

Poco F2 pro, MIUI global 13.0.3 stable, android 12
