### ISSUE TITLE
Persistent selection highlight

### ISSUE THREAD

**Issue by 0x192** [0x192/Universal-Android-Debloater#209]
**Describe the feature you want:**

Currently there's nothing indicating which package you've selected in the list. The only highlights are when you hover and when you click, but it would be nice if there was a persistent one on the currently selected package.

Related issue : #145

**Comment by ghost** [comment]
Hello! Your list is great!
While reading, I have a question. Is it possible to remove com.qti.diagservices.
apparently responsible for some kind of diagnosis. I use Xiaomi with Miui and this package runs in the background quite often. Will battery life decrease after removing it?

**Comment by Vitaliy57** [comment]
Привет! Не понял, не найду файл для скачивания ABD одни пояснения. Зашёл на сайты GitHub, не вижу где файл который надо скачать, одни буквы и картинки, Help!
