### ISSUE TITLE
Cannot connect to google anymore, gmail crashes

### ISSUE THREAD

**Issue by smtgpm** [0x192/Universal-Android-Debloater#210]
**Your phone**: Realme X3 superzoom

**Describe the issue**
Hi all :)
So after uninstalling a bunch of recommended packages, I cannot connect to my google services anymore...
I restored all uninstalled apps and issue still remains... Gmail app also crashes nouw every time I open it
[EDIT] actually, a whole lot of apps don't open anymore.... What should I do ?? 

**You have a solution?**
What to do to fix the issue.

**UAD log**
[UAD_20220424.log](https://github.com/0x192/universal-android-debloater/files/8549521/UAD_20220424.log)

**Comment by lawson85** [comment]
I can't see that you've restored system webview, which will crash most apps. It's on the play store so you can always download it.

**Comment by smtgpm** [comment]
Ah damn i thought i selected everything back...
Well thanks for the support, i ended up doing a factory reset... But after the reset I deleted a whole bunch of stuff via the debloat tool and it works perfectly
