### ISSUE TITLE
weather app uninstall will trigger looping crash phone

### ISSUE THREAD

**Issue by smtgpm** [0x192/Universal-Android-Debloater#211]
Your phone: Realme X3 superzoom

Describe the issue
Hello again
So I have a realme phone, and I tried and uninstlla  bunch of stuff, and found out that the 
"com.coloros.weather2" app (https://apkcombo.com/fr/oppo-weather/com.coloros.weather2/) makes it so that once this is uninstalled, as soon as you change system layout settings (ie change theme to dark/light, or change layont size), the phones goes in a loop mode that nothing can fix unliess re-installing the weather app or completely wipe the phone. Bacially it turns the screen on and off, with nothing shown when screen is on except home picture
I did not test much else, but thougth it'd be worth mentionning.
I forked the repo to add that in the json  file, but I'm not so sure what is wanted here, should I add a unsafe description ? 
there is also another weather app in my list : "com.coloros.weather.service", this one uninstalled the weather app on my phone, and nothing seem to crash...

UAD log
here is my log file just in case:
[UAD_20220426.log](https://github.com/0x192/universal-android-debloater/files/8564268/UAD_20220426.log)

**Comment by runninghamster0** [comment]
@0x192 This is the same issue as #158. Taking into consideration both issues and the varying problems occurring from removing either package, we can add both into the 'Unsafe' list. For me removing `com.coloros.weather.service` caused the issue and `com.coloros.weather2` could be safely removed. Here it is vice-versa. In my opinion to be safe, we should add both into the 'Unsafe' list to cover for all the varying ColorOS derivatives.

**Comment by smtgpm** [comment]
Hi,

Oh I did look for any open issues that would be similar before opening mine... apparently I didn't look well enough... Thanks.
Weird that the behaviors are opposite though. I've opened a [PR ](https://github.com/0x192/universal-android-debloater/pull/226) setting both apps to unsafe.

**Comment by rafnov** [comment]
Anyone had the problem on Realme GT Neo2?
