### ISSUE TITLE
Unable to install the file

### ISSUE THREAD

**Issue by chiragnahata** [0x192/Universal-Android-Debloater#212]
No .exe file available to download

**Comment by MikeZeDev** [comment]
Click on assets on the release page. There are zip files.

**Comment by chiragnahata** [comment]
Ok thanks but it is not detecting my device Redmi 9 Prime India Chirag Nahata

**Comment by MikeZeDev** [comment]
This program is a convenient interface for the official android tools, so you have to take some steps before it works.

You need to install the official USB drivers for android, then the Command line tools which included ADB, you need to enable developer mode & usb debugging on your phone. https://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility/

After all is done, put UAD exe in adb.exe folder, and launch UAD.

Hum. I dont wanna be rude but you don't seem to be at ease with IT stuff. I really hope you wont break your phone. Read the application's descriptions carefully before removing any of them. And i suggest you to stick with the "Recommended" list ;)
