### ISSUE TITLE
uninstalling user dictionary may cause settings menu to crash

### ISSUE THREAD

**Issue by HT696** [0x192/Universal-Android-Debloater#216]
**phone**: Honor 8 Lite , EMUI:8.0.0.0

**Packages documentation to update:**
```
com.android.providers.userdictionary
...
```

### \<package name\>com.android.providers.userdictionary
**Removal**: 'Advanced' :arrow_right: 'Expert' 

**Current description**
>"Handles user dictionary for keyboard apps.\nContent providers encapsulate data, providing centralized management of data shared between apps.\nhttps://developer.android.com/guide/topics/providers/content-providers.html"

**Proposed description**
> "Handles user dictionary for keyboard apps.\nContent providers encapsulate data, providing centralized management of data shared between apps.\nhttps://developer.android.com/guide/topics/providers/content-providers.html\nmay cause settings menu to crash and become unaccessible"

p.s : after uninstalling the package reboot may be needed in order to reproduce the crashing

**Comment by lawson85** [comment]
I could be wrong but it looks like you can update to EMUI 9

**Comment by HT696** [comment]
> I could be wrong but it looks like you can update to EMUI 9

I can't (I had a typo, extra "P" in the model, which could make people confuse it with Huawei P8 Lite (instead of Honor) sorry about that)

**Comment by Rudxain** [comment]
My device is SM-A315G, that content provider can be easily disabled without commands (from the app settings itself). I even uninstalled it, then rebooted, and there's nothing broken (yet).

I think `Expert` may be an exaggeration, considering that most systems (old and new) allow disabling it, AFAIK
