### ISSUE TITLE
trailing # not added in secret dialer codes in description of some packages. bad formatting of description

### ISSUE THREAD

**Issue by charitra1022** [0x192/Universal-Android-Debloater#220]
**Your phone**: SM-G610F

**Packages documentation to update:**
```
com.sec.android.app.DataCreate
com.sec.android.app.factorykeystring
com.sec.android.app.hwmoduletest
com.sec.android.app.servicemodeapp
com.sec.android.app.wlantest
com.sec.factory.camera
```

## Documentation change

**List**: `Oem` (manufacturer)

### com.sec.android.app.DataCreate

**List**:  oem

**Current description**

> Automation Test\nAnother hidden test app. A lot of mention of samsung note \(memo\). Has access to basically everything on the phone\nRelated to these hidden menus \(accessible by typing these codes in the samsung dialer\) :\n- \*#3282\*727336\*\(Status of data usage\) \n- \*#273283\*255\*3282\*\(Data create menu\) \n- 273283\*255\*663282\* \(Backup all media files\)\n

**Proposed description**
> Automation Test\nAnother hidden test app. A lot of mention of samsung note \(memo\). Has access to basically everything on the phone\nRelated to these hidden menus \(accessible by typing these codes in the samsung dialer\) :\n- \*#3282\*727336\*# \(Status of data usage\) \n- \*#273283\*255\*3282\*# \(Data create menu\) \n- 273283\*255\*663282\*# \(Backup all media files\)\n

### com.sec.android.app.factorykeystring

**List**:  oem

**Current description**

> DeviceKeyString : Dialable hidden diagnostic/debug app\nDial \*#0283to open audio LoopbackTest control, dial \*#2663for TSP firmware update\n

**Proposed description**
> DeviceKeyString : Dialable hidden diagnostic/debug app\nDial \*#0283# to open audio LoopbackTest control, dial \*#2663# for TSP firmware update\n

### com.sec.android.app.hwmoduletest

**List**:  oem

**Current description**

> HwModuleTest, a hardware hidden test app \(dial \*#0\*to open it). \nFun low-level stuff to see in there\n

**Proposed description**
> HwModuleTest, a hardware hidden test app \(dial \*#0\*# to open it). \nFun low-level stuff to see in there\n

### com.sec.android.app.servicemodeapp

**List**:  oem

**Current description**

> SysDump hidden app\nLow-level debugging and diagnostics tools \(dial \*#9900to open it\)\n

**Proposed description**
> SysDump hidden app\nLow-level debugging and diagnostics tools \(dial \*#9900# to open it\)\n

### com.sec.android.app.wlantest

**List**:  oem

**Current description**

> wlan test\nHidden test app responding to the #232339\*and \*#232338\*secret codes\nFYI : wlan = wireless LAN (https://en.wikipedia.org/wiki/Wireless_LAN)\nNOTE: Disabling this test will rise the exclamation mark on the WI-Fi icon and will show the message \"Unable to connect to the host\" in Settings -> Connections -> More connections settings - Private DNS - provider hostname.\nThe connection seems to work despite those esthetic errors.

**Proposed description**
> wlan test\nHidden test app responding to the #232339\*# and \*#232338\*# secret codes\nFYI : wlan = wireless LAN (https://en.wikipedia.org/wiki/Wireless_LAN)\nNOTE: Disabling this test will rise the exclamation mark on the WI-Fi icon and will show the message \"Unable to connect to the host\" in Settings -> Connections -> More connections settings - Private DNS - provider hostname.\nThe connection seems to work despite those esthetic errors.

### com.sec.factory.camera

**List**:  oem

**Current description**

> Camera Test \(dial \*#34971539to open CameraFirmware Standard\)\n

**Proposed description**
> Camera Test \(dial \*#34971539# to open CameraFirmware Standard\)\n

**Comment by 0x192** [comment]
Fixed with #221
