### ISSUE TITLE
Software not opening after my laptop crashed

### ISSUE THREAD

**Issue by Naaveen-Kumar** [0x192/Universal-Android-Debloater#222]
**Describe the bug**
When I first launched, the UAD software, my laptop had a little bit of charge left (not even in battery saver mode), but when i started UAD and maximized it, the laptop just switched off immediately. I then switched on the charger and started the laptop. Now, UAD doesn't even start when I open the .exe file. I tried openGL version too and different version of UAD (0.4.1), but no luck.

Is there any way to make the software open now?

**Comment by lawson85** [comment]
Is it just UAD or do other software fail as well? Sounds like a driver issue. Intel has a driver updater, windows has one built into Windows update under advance settings, Lenovo has it's own system update and HP makes one too. 

Also try these built in features to fix bugs: https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chkdsk

Windows update assistant is useful too. 

I would suggest deleting all of UAD and it's logs and download latest version and try again. Make sure to have an internet connection. 

It may be wise to clean Windows up a bit with BleachBit which is an open source cleaner

**Comment by Naaveen-Kumar** [comment]
Hi, where do I find the UAD logs? Sorry it took me so long to reply.

**Comment by 0x192** [comment]
https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles

**Comment by Naaveen-Kumar** [comment]
Hi, please close the bug. Idk when i will get time to try the steps to fix the issue.
