### ISSUE TITLE
No action is taken on clicking uninstall. Device: vivo1609 

### ISSUE THREAD

**Issue by deep8405** [0x192/Universal-Android-Debloater#232]
**Your phone**: \<phone model\>

**Describe the issue**
A clear and concise description of what the problem is.

**You have a solution?**
What to do to fix the issue.

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.

**Comment by 0x192** [comment]
I have the impression that you didn't understand it was a template. 

>  Upload the logfile generated by UAD. You can hardly be helped without.

:roll_eyes:
