### ISSUE TITLE
App Name field to be added

### ISSUE THREAD

**Issue by charitra1022** [0x192/Universal-Android-Debloater#233]
When I created the pull request for an update, I studied the json file.

One thing that will make this app more versatile is **app name search and display**

One field **name** should be added to each app entry, and in the code, the name field should be displayed along with the package name of the app.

It will also allow the user to search an app directly via the app name.

I think, it can be difficult to implement everything at once, but it will be great if Names are displayed along with the package names in list view!

**Comment by charitra1022** [comment]
If you are planning to add this feature, then many developers like me will be available immediately to update the existing package list with app names!

My LinkedIn id - charitra1022

**Comment by 0x192** [comment]
I'm still not sure about this feature. I've had this idea in mind for a while but I don't like the idea that I either have to push all the APKs from the phone to the computer or install `aapt` on the phone.

See #59

**Comment by charitra1022** [comment]
> I'm still not sure about this feature. I've had this idea in mind for a while but I don't like the idea that I either have to push all the APKs from the phone to the computer or install `aapt` on the phone.
> 
> See #59

I totally understand what u are saying, and that's correct..
Getting app name directly from adb is a tough and worthless job.

But what I'm saying is to add another **field** in the app list json itself. (i.e., **uad_list.json**)
We can hard code the application names in that list, and later when we are able to get names from adb in future, we can refernce names from there, and not from list..

At least we can try this. This just requires another field to be added in the json file, and then access that field in the UI to **display** the name in app listings and can be used in app search.

Most of the app description contains names.. it won't be that difficult to implement it. 

And Apps that dont have accurate or specific names, can have **null** value instead of name, and a specific task can be implemented in the app logic to handle **null** names..

Hope I make some sense!
