### ISSUE TITLE
Submit UAD to the AUR

### ISSUE THREAD

**Issue by 0x192** [0x192/Universal-Android-Debloater#24]
https://wiki.archlinux.org/title/creating_packages

**Comment by 0x192** [comment]
In GitLab by @Asperatus on Sep 10, 2021, 19:47

It is probably also interesting to publish the project on crates.io as a binary so that you can download the software using `cargo`. It is quite common for Rust software to do so. FYI `uad` is an available crate name, you can probably use that instead of `uad_gui` for convenience.

It's a fast an easy way to have your software available on any OS and any Linux distribution (since `cargo` is cross-platform).

Here are useful resources you might want to take a look at

- https://rust-cli.github.io/book/tutorial/packaging.html
- https://doc.rust-lang.org/cargo/reference/publishing.html

**Comment by yochananmarqos** [comment]
@0x192 I added it to the AUR: [`universal-android-debloater`](https://aur.archlinux.org/packages/universal-android-debloater/)

Let me know if you'd like to help maintain it.

**Comment by 0x192** [comment]
Sorry for the late reply. I wanted to do it myself as a learning experience but I have to thank you for your time on this and for being the current maintainer.

I really need to spend some time on this so that I can understand the whole process. I've never created a PKGBUILD. It doesn't seem particularly difficult but I at least have to try writing my own. You seems to have a lot experience so I could compare mine with yours :)

I'll come back to you when I'll be ready to maintain it. Let's say for the `v0.4` release.

**Comment by 0x192** [comment]
@yochananmarqos 

Finally!

I now maintain 2 distinct packages:
- The default one with the Vulkan renderer:  [`universal-android-debloater-bin`](https://aur.archlinux.org/packages/universal-android-debloater-bin/)
- A compatibility build with an OpenGL renderer: [`universal-android-debloater-opengl-bin`](https://aur.archlinux.org/packages/universal-android-debloater-opengl-bin/)

They both provide `universal-android-debloater-bin` and conflict with each other. As soon as Iced supports choosing a renderer at runtime ([this is a planed feature](https://github.com/iced-rs/iced/issues/1199)) there won't the need of 2 packages anymore.

I can now maintain [`universal-android-debloater`](https://aur.archlinux.org/packages/universal-android-debloater/) if you want.

**Comment by yochananmarqos** [comment]
Both `-bin` packages need to provide and conflict with `universal-android-debloater`, nothing else. See [Package relations](https://wiki.archlinux.org/title/PKGBUILD#Package_relations).

I don't really see the need for two packages at all, especially since you'll have to merge one into the other later.

**Comment by 0x192** [comment]
> Both -bin packages need to provide and conflict with universal-android-debloater, nothing else. See Package relations.

You are totally right. I don't know why I did this. I had read the Package relations part of the wiki though. I fixed this. Thanks for the correction!

> I don't really see the need for two packages at all, especially since you'll have to merge one into the other later.

I don't see the point of installing 2 versions of UAD. Either you want the default one or the Opengl one. Not both. 

Yes a merge will be needed in the end.

**Comment by yochananmarqos** [comment]
> Either you want the default one or the Opengl one. Not both.

This is true, however how would one know which to use until the Vulkan one freezes their computer so they know they need to use the OpenGL one? :stuck_out_tongue_winking_eye:

**Comment by 0x192** [comment]
I had already tested and the software just doesn't start. This will not freeze the computer! :wink:
