### ISSUE TITLE
com.miui.wallpaper documentation update

### ISSUE THREAD

**Issue by TheEmbracedOne** [0x192/Universal-Android-Debloater#242]
**Your phone**: Xiaomi 11T

**Packages documentation to update:**
```
com.miui.wallpaper
```
## Documentation chage
**Current description**
> Mi Wallpaper

**Proposed description**
> Mi Wallpaper. Removing this might make it impossible to set a lock or home wallpaper, resulting in a black solid wallpaper.

**Comment by nixingyang** [comment]
For the record, it is `com.miui.miwallpaper` rather than `com.miui.wallpaper`. One should not uninstall it; otherwise, the wallpaper will not work properly.
