### ISSUE TITLE
OTA does or does not revert debloat?

### ISSUE THREAD

**Issue by kor3k** [0x192/Universal-Android-Debloater#251]
hello,

i have a question i didn't find in FAQ.

does OTA update restore debloated apps or not? or is it vendor/model dependent?

**Comment by AnonymousWP** [comment]
> hello,
> 
> i have a question i didn't find in FAQ.
> 
> does OTA update restore debloated apps or not? or is it vendor/model dependent?

No, it does not. Just when you update to a new Android version, there may be new apps that you'll have to disable.

**Comment by kor3k** [comment]
thank you
