### ISSUE TITLE
Allow building with Rust stable instead of nightly

### ISSUE THREAD

**Issue by triallax** [0x192/Universal-Android-Debloater#252]
**Describe the feature you want**
Lower the Rust version requirement to a stable Rust version. The dependency on Rust nightly prevents me from submitting UAD to package repositories such as https://github.com/void-linux/void-packages, which do not accept packages that require Rust nightly.

If you're okay with this idea, I'm fine with creating a PR myself, as long as it isn't too difficult (I'm not too familiar with Rust).

**Comment by 0x192** [comment]
Sorry for the very late reply. I'm a bit overwhelmed by the issues and pull requests.

I chose the nightly toolchain because I've been using some features not available in Rust stable. After all this time, they may have been stabilized. I missed some stable Rust changelog. I'll take a look.

> The dependency on Rust nightly prevents me from submitting UAD to package repositories such as https://github.com/void-linux/void-packages

It would be great to have this software available for packages managers but honestly I'm not sure that UAD is mature enough to land in the official repositories of Linux distributions. Maybe I'm a bit too hard on myself... I don't know.

PS : By the way, thanks you for your open-source contributions! :heart:  Especially NewPipe, being a user of this wonderful app.

**Comment by triallax** [comment]
> Sorry for the very late reply. I'm a bit overwhelmed by the issues and pull requests.

No problem, happens to the best of us. Maybe you can ask regular contributors to become collaborators to ease the load on you?

> I chose the nightly toolchain because I've been using some features not available in Rust stable. After all this time, they may have been stabilized. I missed some stable Rust changelog. I'll take a look.

All right, thank you very much.

> It would be great to have this software available for packages managers but honestly I'm not sure that UAD is mature enough to land in the official repositories of Linux distributions. Maybe I'm a bit too hard on myself... I don't know.

My two cents: I'm not sure either, but I think it's probably fine.

> PS : By the way, thanks you for your open-source contributions! ❤️ Especially NewPipe, being a user of this wonderful app.

You're welcome, and thank you for your work on UAD!

**Comment by AnonymousWP** [comment]
> No problem, happens to the best of us. Maybe you can ask regular contributors to become collaborators to ease the load on you?

I volunteer! I've been trying to help where I can by converting issues into PRs, as well as reviewing PRs and responding to issues.

**Comment by 0x192** [comment]
After a long wait, here we are, UAD now supports Rust Stable! :tada:

@mhmdanas 
 `v0.6` will be released before the end of 2022. From that, you can submit UAD to [void-packages](https://github.com/void-linux/void-packages) if you are still motivated to do so.

---

> I volunteer! I've been trying to help where I can by converting issues into PRs, as well as reviewing PRs and responding to issues.

Thanks for your help on the project but I'd only *consider* giving the `Collaborator` role for a invested contributor with Rust skills or for someone with reverse engineering skills which can improve the documentation the apps. :slightly_smiling_face: 

This role gives a LOT of permissions! It involves a lot of trust to give the `Collaborator` role  to someone.

**Comment by triallax** [comment]
> v0.6 will be released before the end of 2022. From that, you can submit UAD to [void-packages](https://github.com/void-linux/void-packages) if you are still motivated to do so.

Sure, I still am. I do have one question though: is it best to package the OpenGL version of UAD, or the Vulkan one? I think it's the earlier because it should run on more devices, right? Or is it possible to have both in one binary? (As you can perhaps tell, I'm not too knowledgeable about such things, so bear with me :) )
