### ISSUE TITLE
Typo in release name of noseflupdate

### ISSUE THREAD

**Issue by ericzolf** [0x192/Universal-Android-Debloater#256]
https://github.com/0x192/universal-android-debloater/blob/4f9a1d754795e4441a68d11b30f2706a7a3809ec/.github/workflows/release.yml#L33

Should read noselfupdate...

**Comment by 0x192** [comment]
Oops! Thanks for bringing this to me.

**Comment by OpenByteDev** [comment]
same error also in other workflows:

https://github.com/0x192/universal-android-debloater/blob/11f27c671cba278d71296cdef4c5a5dba06add5e/.github/workflows/build_artifacts.yml#L32
