### ISSUE TITLE
Samsung video player crashing and not play any video

### ISSUE THREAD

**Issue by ranjeetghotra** [0x192/Universal-Android-Debloater#261]
**Your phone**: Samsung SM-M315F

**Describe the issue**
I uninstalled all recommended packages then Samsung video player crashing

**You have a solution?**
Please move "com.samsung.android.smartmirroring" from recommended to advanced section
![WhatsApp Image 2022-06-08 at 9 12 58 PM](https://user-images.githubusercontent.com/51962996/172659760-4f786aa0-d2dd-4d61-8f55-0cc88d97cf06.jpeg)

**Comment by 0x192** [comment]
Thanks for your report!
