### ISSUE TITLE
com.miui.android.fashiongallery

### ISSUE THREAD

**Issue by QuangSE** [0x192/Universal-Android-Debloater#263]
**Your phone:** POCO F3 EEA MIUI V13.0.6.0.SKHEUXM

**Packages:**
```
com.miui.android.fashiongallery
```
- [ ✓] **I removed all those packages on my phone**

### \<com.miui.android.fashiongallery\>
**List**: `Oem`
**Removal**: `Advanced`
> Description.  [Mi Wallpaper Carousel](https://play.google.com/store/apps/details?id=com.miui.android.fashiongallery&gl=US) is basically a wallpaper slideshow for the lockscreen.

**Comment by 0x192** [comment]
Thanks for your report but this app[ is already in the list](https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L15402) :slightly_smiling_face: 

Make sure you are using the last version of UAD (`v0.5`)
