### ISSUE TITLE
AppCloud com.aura.oobe.samsung.gl

### ISSUE THREAD

**Issue by YaHa12** [0x192/Universal-Android-Debloater#265]
**Samsung Galaxy A32 5G**

**Packages:**
```
com.aura.oobe.samsung.gl
```
- [✓] **I removed all those packages on my phone**

**List**: `Oem`
**Removal**: `Recommended`,
> Description.
This preinstalled application install sponsored apps on your phone.

**Comment by ghost** [comment]
#278 is kind of a duplicate.
