### ISSUE TITLE
Description change for com.sec.android.app.myfiles due to unexpected behavior after uninstalling it

### ISSUE THREAD

**Issue by assarbad** [0x192/Universal-Android-Debloater#266]
**Your phone**: SM-G780G (Samsung S20 FE, 4G)

**Packages documentation to update:**
```
com.sec.android.app.myfiles
```
### com.sec.android.app.myfiles

**List**: `Oem` (manufacturer)
**Removal**: `Expert` (this can break important features)

**Current description**
> Samsung file manager app (https://play.google.com/store/apps/details?id=com.sec.android.app.myfiles)

**Proposed description**
> Samsung file manager app (https://play.google.com/store/apps/details?id=com.sec.android.app.myfiles)
>
> NOTE: After removing this, you will no longer be able to manage storage the same way as before; for example you will lose the ability to unmount or format the SD card from within the Settings app.

**Comment by 0x192** [comment]
Thanks for the report. This only affects newer phones. 

I'll update the description.
