### ISSUE TITLE
UAD not identifying phone

### ISSUE THREAD

**Issue by dannokiddo** [0x192/Universal-Android-Debloater#267]
Previously I tried with my OPPO A93, it detects the phone easily & all is well. But now, UAD does not detect my phone.

If anyone have the same issue or same device, is there anything I should do?

**Comment by KaiAtari** [comment]
Place the Debloater exe in the platform tools folder where ADB and other files are located.

**Comment by eleius** [comment]
Also make sure USB Debugging is still active in your phone's settings

**Comment by 0x192** [comment]
Please follow the issue template and upload your logs: https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles
