### ISSUE TITLE
com.sec.sve Breaks voWIFI / wifi calling on S22 Ultra T-Mobile (Unlocked Hardware)

### ISSUE THREAD

**Issue by hibby50** [0x192/Universal-Android-Debloater#270]
**Your phone**: S22 Ultra Unlocked

**Packages documentation to update:**
```
com.sec.sve
```
## Documentation chage
**List**: `Google`|`Misc`|`Oem` (manufacturer)|`Aosp`|`Pending`|`Carrier` (isp).
**Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features), `Unsafe` (this can bootloop the phone or break extremely important features).

### com.sec.sve
**List**:  Recommended :arrow_right: Expert

**Current description**
> SecVideoEngineService is arguably a Samsung video engine service (handle enconding/decoding ?) for displaying video trough Samsung apps. \n3 permissions : RECORD_AUDIO, CAMERA, INTERACT_ACROSS_USERS_FULL\nSafe to remove.\n

**Proposed description**
> SecVideoEngineService is arguably a Samsung video engine service (handle enconding/decoding ?) for displaying video trough Samsung apps. \n3 permissions : RECORD_AUDIO, CAMERA, INTERACT_ACROSS_USERS_FULL\nBreaks Wi-Fi Calling.\n

**Comment by Mark-Milkis** [comment]
Restoring the package on S20 FE on Verizon also restored Wifi calling on Verizon network

**Comment by hibby50** [comment]
Thanks for confirming Mark, It is worth noting, just for people's information, that I had to reboot after restoring it for the Wi-Fi calling to work again.
