### ISSUE TITLE
Oneplus

### ISSUE THREAD

**Issue by mk5566** [0x192/Universal-Android-Debloater#273]
**Your phone**: Oneplus Phone

**Packages documentation to update:**
```
com.oneplus.communication.data
```
## Documentation chage
**List**: Oem
**Removal**: Expert.

**Current description**
"Communication important data\nOdd name. No idea what it does.\nContains the \"OPRecorderService\", but I've never seen it run. Also contains a \"OneplusAuthorizationActivity\" that doesn't seem to do anything when activated."

**Proposed description**
"Oneplus phone app record app, if you want to use OOS native call recording this is the app make it work."

**Comment by 0x192** [comment]
Thanks you for your contribution! :slightly_smiling_face:
