### ISSUE TITLE
Removing com.google.android.deskclock leads to silent alarms and "Alarm" unavailable in sound settings

### ISSUE THREAD

**Issue by TheEmbracedOne** [0x192/Universal-Android-Debloater#277]
**Your phone**: Xiaomi 11T

**Packages documentation to update:**
`com.google.android.deskclock`

### com.google.android.deskclock
**Current description**
> AOSP Clock app
> Some OEMs (like Huawei & Xiaomi) use the same package name for their app.

**Proposed description**
> AOSP Clock app
> Some OEMs (like Huawei & Xiaomi) use the same package name for their app.
> On some phones, removing this makes it so alarms and notifications only vibrate and dont make any sound (via any installed app), and makes the "Alarm" section unavailable in "Settings > Sound & Vibration".

**Comment by AnonymousWP** [comment]
From what I'm seeing, the current description is:

> Google clock app (https://play.google.com/store/apps/details?id=com.google.android.deskclock)

And not what you stated as 'current description'.

**Comment by TheEmbracedOne** [comment]
@AnonymousWP I might have taken the description on a version that was not fully up to date then. Either way, the additional notes I propose adding to the description is still relevant and useful!

**Comment by AnonymousWP** [comment]
> @AnonymousWP I might have taken the description on a version that was not fully up to date then. Either way, the additional notes I propose adding to the description is still relevant and useful!

Right, so I'll leave the current description and just add your additional text to it.

**Comment by TheEmbracedOne** [comment]
Cheers @AnonymousWP
