### ISSUE TITLE
OnePlus Packages 

### ISSUE THREAD

**Issue by Rafee-M** [0x192/Universal-Android-Debloater#280]
**Your phone:** OnePlus 9RT
**Packages:**
```
com.oplus.wifibackuprestore
com.oplus.logkit
com.coloros.activation
com.oneplus.chargingpilar
```
- [Yes ] **I removed all those packages on my phone**

### com.oplus.wifibackuprestore
**List**: `Oem`
**Removal**: `Recommended`
> https://www.apkmirror.com/apk/oppo/wifibackuprestore-4/wifibackuprestore-4-1-0-release/wifibackuprestore-1-0-3-android-apk-download/

### com.oplus.logkit
**List**: `Oem`
**Removal**: `Advanced`
> Possibly collects and sends device logs or might be just internal?

### com.coloros.activation
**List**: `Oem`
**Removal**: `Advanced`
> Maybe contacts Oppo servers for some sort of verification?

### com.oneplus.chargingpilar
**List**: `Oem`
**Removal**: `Recommended`
> Attempts to find specific charging stations nearby

### com.nearme.statistics.rom
**List**: `Oem`
**Removal**: `Expert`
> Breaks the search function in the `Settings` app

### com.oplus.ocar
**List**: `Oem`
**Removal**: `Recommended`
> Related to Oppo's car app

**Comment by 0x192** [comment]
Thanks for your help! It's finally merged! :tada: 

I needed some time to improve the description of all these apps.
