### ISSUE TITLE
UAD can't find my adb connected devices

### ISSUE THREAD

**Issue by chidam333** [0x192/Universal-Android-Debloater#283]
## UAD can't find my adb connected devices
<hr>

**ADB devices**
When in cmd lind i type the abd devices it shows the device in the following format
List of devices attached
964858281*****C device 

(lol I don't know if it is safe to show the whole number hence erased the last five digits )

**UAD log**
Upload the logfile generated by UAD.
[UAD_20220701.log](https://github.com/0x192/universal-android-debloater/files/9028221/UAD_20220701.log)

**Comment by chidam333** [comment]
So sorry !!! I figured it out we are supposed to put this application inside package tools folder ! But yeah i do this it could be a nice if it is highlighted . Thank you for this beautiful application !! 🎉🎉

**Comment by 0x192** [comment]
Thanks for your kind words! :slightly_smiling_face: 

FYI, I advice users (in the `WINDOWS` [dropdown of the README](https://github.com/0x192/universal-android-debloater#how-to-use-it) that nobody seems to read) to add the directory to their PATH instead so they can use the adb command everywhere.

**Comment by chidam333** [comment]
Oh !! I was unaware that details tag are supported in the markdown 😳 i never thought of clicking it . Thanks for the information.
