### ISSUE TITLE
com.miui.gallery description update

### ISSUE THREAD

**Issue by 1datatec** [0x192/Universal-Android-Debloater#284]
**Your phone**: Mi 9

**Packages documentation to update:**
```
com.miui.gallery
```
Hi, uninstalling this breaks "send screenshot" functionality. You swipe 3 fingers and it shows screenshot preview with Send button. Uninstalling com.miui.gallery breaks this button.

**Comment by 0x192** [comment]
Thanks for your report! :slightly_smiling_face:
