### ISSUE TITLE
Stuck on Downloading latest UAD lists from github. Please wait...

### ISSUE THREAD

**Issue by gobeard** [0x192/Universal-Android-Debloater#286]
**Describe the bug**
Stuck on Downloading latest UAD lists from github. Please wait...
Documentation is stuck on checking for update.

**Expected behavior**
Expected to continue the process to show apps that can be uninstalled.

**You have a solution?**
What to do to fix the issue.
No solution found.

**UAD log**
Upload the logfile generated by UAD.
[UAD_20220703.log](https://github.com/0x192/universal-android-debloater/files/9034056/UAD_20220703.log)

**Comment by brokoler** [comment]
Same issue for me:
[UAD_20220703.log](https://github.com/0x192/universal-android-debloater/files/9034262/UAD_20220703.log)

**Comment by wantei** [comment]
I'm also having the same issue:
[UAD_20220703.log](https://github.com/0x192/universal-android-debloater/files/9034524/UAD_20220703.log)

**Comment by noygal** [comment]
Same issue for me as well...

**Comment by noygal** [comment]
The error I'm getting is:

```
WARN  [src/gui/mod.rs:102] Trying to download remote UAD list
thread '<unnamed>' panicked at 'Unable to parse: Error("invalid type: sequence, expected a string", line: 4210, column: 16)', src/core/uad_lists.rs:214:60
```

Look like issue with the json schema here: https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L4210

And related to this commit: https://github.com/0x192/universal-android-debloater/commit/f1b3ac40dffd17f44e91af90c13fc8d4756fc2bb

Now to it looks like to me like the issue is placing an array of strings instead of a single string.

**Comment by noygal** [comment]
Tested it locally after modifying the cached downloaded json, everything works fine, bloat eliminated 👏

**Comment by gobeard** [comment]
> Tested it locally after modifying the cached downloaded json, everything works fine, bloat eliminated 👏

Can you tell me how you did that?

**Comment by ericzolf** [comment]
Not sure this helps further, but I've called the following (Fedora 36):

```
$ RUST_BACKTRACE=full uad_gui-linux 
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
2022-07-03 14:37:49 WARN  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.4/src/gles/adapter.rs:450] Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.
2022-07-03 14:37:49 WARN  [src/gui/mod.rs:102] Trying to download remote UAD list
thread '<unnamed>' panicked at 'Unable to parse: Error("invalid type: sequence, expected a string", line: 4210, column: 16)', src/core/uad_lists.rs:214:60
stack backtrace:
   0:     0x55eb94e99288 - <unknown>
   1:     0x55eb94cc54fc - <unknown>
   2:     0x55eb94e6de90 - <unknown>
   3:     0x55eb94e9a1f5 - <unknown>
   4:     0x55eb94e9affa - <unknown>
   5:     0x55eb94e9ab72 - <unknown>
   6:     0x55eb94e9aae6 - <unknown>
   7:     0x55eb94e9aaa2 - <unknown>
   8:     0x55eb94cc3112 - <unknown>
   9:     0x55eb94cc96f2 - <unknown>
  10:     0x55eb94f244ca - <unknown>
  11:     0x55eb94c973ee - <unknown>
  12:     0x55eb94c75e40 - <unknown>
  13:     0x55eb94cdb974 - <unknown>
  14:     0x55eb94cdef39 - <unknown>
  15:     0x55eb94e9c4f5 - <unknown>
  16:     0x7fb7a608ce2d - start_thread
  17:     0x7fb7a6112620 - __GI___clone3
  18:                0x0 - <unknown>
```

**Comment by ericzolf** [comment]
> > Tested it locally after modifying the cached downloaded json, everything works fine, bloat eliminated clap
> 
> Can you tell me how you did that?

I guess, check `/home/myuser/.cache/uad` and remove the square brackets around the line `"neededBy": ["com.samsung.android.video"],` (all other entries are either a single string or `null`).
I'm not 100% that it solves the issue for me because UAD only finds a list of 10 _Unlisted_ software on Galaxy S10e/SM-G970F (but it's the first time I use it with this device, it might be another issue).

My procedure so far:
1. start UAD
2. click "no internet?"
3. edit the above file
4. refresh the UI (top left circling arrows)

**Comment by ericzolf** [comment]
Also on a Fairphone 3, same 10 unlisted apps, sounds fishy...
![image](https://user-images.githubusercontent.com/3105685/177040957-75b1ae71-34c7-4fef-980c-a09f1b2f9216.png)

**Comment by 0x192** [comment]
There is an issue in the `uad_list.json`. I'm on it!

**Comment by ericzolf** [comment]
The file format issue is gone but I still have only the 10 unlisted apps listed on my FP3. Shall I open a new issue or do you think it's the same issue, or even normal?

**Comment by 0x192** [comment]
It's not related but you are not the first person with it. It's a really weird problem. Let's move on there:  #86

**Comment by ghost** [comment]
The last 23 apps are missing the "dependencies" option. This might be the error.

**Comment by brokoler** [comment]
Not fixed for me, I still can't download the UAD lists:
[UAD_20220703.log](https://github.com/0x192/universal-android-debloater/files/9035062/UAD_20220703.log)

**Comment by 0x192** [comment]
@brokoler 

I no longer have any error on my side.

Can you launch it from a terminal and report the error? I'm realizing the error doesn't appear in the logfile.

**Comment by ghost** [comment]
Can't get it to work for me. Here is the log files if it helps:

2022-07-04 00:50:50 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-07-04 00:50:50 WARN  [src\gui\mod.rs:102] Trying to download remote UAD list
2022-07-04 00:50:53 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-07-04 00:50:55 ERROR [src\core\utils.rs:161] Can't open the following URL:

**Comment by brokoler** [comment]
> Can't get it to work for me. Here is the log files if it helps:
> 
> 2022-07-04 00:50:50 DEBUG [src\core\update.rs:178] Checking for UAD update 2022-07-04 00:50:50 WARN [src\gui\mod.rs:102] Trying to download remote UAD list 2022-07-04 00:50:53 DEBUG [src\core\update.rs:178] Checking for UAD update 2022-07-04 00:50:55 ERROR [src\core\utils.rs:161] Can't open the following URL:

Same for me, I don't see any different errors than this

**Comment by 0x192** [comment]
@yippieyip @brokoler 

Run the app from the command line please. I need the terminal output. This kind of error doesn't appear in the logfile. I'll change this behavior for next version.

**Comment by ghost** [comment]
Do you mean like this? 
![image](https://user-images.githubusercontent.com/79667085/177050657-3a1b5d26-81bc-47c9-a6ce-67d790a6faa4.png)

**Comment by 0x192** [comment]
Yes :+1:  

But run it like this instead :

```
./uad_gui-windows
```
EDIT: Well I'm not sure what I suggest above works on windows. What you've done doesn't seem to display `stdout` or `stderr` in the terminal...

**Comment by brokoler** [comment]
On Windows this just opens the GUI without any additional output in CMD, but I'm having the same issue on my Mac.

Please check my Mac Terminal output, I hope this helps:

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/57031979/177051673-925236dc-b6e0-49ba-b4f2-d4ae94b6a232.png">

**Comment by 0x192** [comment]
Thanks!

Grmbmbl ! :man_facepalming:

Obviously it doesn't work for you. I changed a line in the code and didn't pushed a new uad_gui release. Hotfix is coming!

**Comment by 0x192** [comment]
`0.5.1` is available : https://github.com/0x192/universal-android-debloater/releases
