### ISSUE TITLE
thread '<unnamed>' panicked

### ISSUE THREAD

**Issue by oussamabenkortbi** [0x192/Universal-Android-Debloater#290]
**Describe the bug**
Phone: Samsung F22
2022-07-03 19:41:59 WARN  [/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.12.2/src/device/mod.rs:4674] Surface does not support present mode: Mailbox, falling back to FIFO
2022-07-03 19:41:59 WARN  [src/gui/mod.rs:102] Trying to download remote UAD list
thread '<unnamed>' panicked at 'Unable to parse: Error("invalid type: sequence, expected a string", line: 2140, column: 16)', src/core/uad_lists.rs:214:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

<img width="892" alt="image" src="https://user-images.githubusercontent.com/34894866/177053097-f205e710-bac3-40c1-a62d-3897f7117d12.png">

**Comment by 0x192** [comment]
See #286

The hotfix is being build by the pipeline. The new release should be ready in a couple of minutes! :slightly_smiling_face:

**Comment by oussamabenkortbi** [comment]
Thanks, i will close this issue 👍🏼

**Comment by 0x192** [comment]
The hotfix is released but I forgot, in the rush, to bump the UAD version. :facepalm:
