### ISSUE TITLE
Instantly hangs up after WiFi call is connected

### ISSUE THREAD

**Issue by Amriky** [0x192/Universal-Android-Debloater#291]
Samsung A42 5G - US version without macro camera

**Describe the issue**
Instantly hangs up after WiFi call is connected

**You have a solution?**
Rebooted after restoring:
com.sec.modem.settings
com.sec.epdg
com.sec.epdgtestapp
com.sec.imslogger
com.sec.imsservice

Not sure which ones are actually critical to wifi calling

**Comment by 0x192** [comment]
I'm pretty sure it is ` com.sec.imsservice` and ` com.sec.epdg` which are respectively in the `Expert` list and the `Advanced` list. 

Their description explicitly says they are tied to VoWifi (Voice over Wifi). I've moved `com.sec.epdg` in the `Expert` list anyway.

What I plan to do in the future is to add labels (like `wifi-calling` for example) to packages to quickly identify needed packages to a specific feature.
