### ISSUE TITLE
Request to update uad_list 

### ISSUE THREAD

**Issue by 443Port** [0x192/Universal-Android-Debloater#292]
Samsung Galaxy S8 (My testing phone)

I found a few unlisted applications but for now I did 2 of them
{
    "id": "com.android.messaging",
    "list": "Oem",
    "description": "Android messaging app",
    "dependencies": null,
    "neededBy": null,
    "labels": null,
    "removal": "Advanced"
  },
  {
    "id": "com.android.screenshot",
    "list": "Oem",
    "description": "The android screenshot tool. Probably safe to remove.",
    "dependencies": null,
    "neededBy": null,
    "labels": null,
    "removal": "Recommended"
  }

**Comment by AnonymousWP** [comment]
> Samsung Galaxy S8 (My testing phone)
> 
> I found a few unlisted applications but for now I did 2 of them { "id": "com.android.messaging", "list": "Oem", "description": "Android messaging app", "dependencies": null, "neededBy": null, "labels": null, "removal": "Advanced" }, { "id": "com.android.screenshot", "list": "Oem", "description": "The android screenshot tool. Probably safe to remove.", "dependencies": null, "neededBy": null, "labels": null, "removal": "Recommended" }

It's better to make a Pull Request of your changes: https://github.com/0x192/universal-android-debloater/pulls

**Comment by AnonymousWP** [comment]
@443Port You don't need to close this issue, because my PR is still opened. My PR will also close this issue, so closing it only confuses the user as if it's fixed/solved while it's not.
