### ISSUE TITLE
Recommendation for com.xiaomi.scanner is wrong

### ISSUE THREAD

**Issue by grigorye** [0x192/Universal-Android-Debloater#293]
**Your phone**:  Xiaomi Poco X3 Pro

**Describe the issue**
Debloater recommends to uninstall com.xiaomi.scanner claiming that it "Lets you scan documents, crop, adjust scale and OCR". However, it's not the case, as it's a QR code scanner (from Xiaomi, yes). It does not scan documents or whatever. Attaching a couple of screenshots.

<details>
<summary>See images</summary>

![Screenshot_2022-07-04-23-25-24-147_com miui securitycenter](https://user-images.githubusercontent.com/803905/177218052-9f095cb4-d1a2-4671-83f3-386284ead2f9.jpg)

![Screenshot_2022-07-04-23-24-34-748_com xiaomi scanner](https://user-images.githubusercontent.com/803905/177218065-e50551f7-4619-4666-ac59-591746565b83.jpg)

</details>

Exclude it from the recommended lists. It does it's job well.

**Comment by 0x192** [comment]
Thanks for the report. I've updated the description but I still kept it in `Recommended` given the huge number of permission this simple QR code app including`ACCESS_FINE_LOCATION`, `CALL_PHONE`, `READ_CONTACTS`,`REQUEST_INSTALL_PACKAGES`, `QUERY_ALL_PACKAGES`, `FOREGROUND_SERVICE`, `INTERNET`

**Comment by ll0r3nt3** [comment]
In fact you don't need scanner app at all, you have google lens on most xiaomi by default, just open the stock camera and above there will be a google lens icon to scan qr.

Also stock camera app can scan qr codes without lens. There is also a way to scan documents, that application is really of little use.

**Comment by grigorye** [comment]
> In fact you don't need scanner app at all, you have google lens on most xiaomi by default, just open the stock camera and above there will be a google lens icon to scan qr.

Thanks for mentioning, I did not realize that. Yes, it works, but please see my comment below.

> Also stock camera app can scan qr codes without lens.

I did not figure it out yet. Can you give me a hint?

> There is also a way to scan documents, that application is really of little use.

While I can use Lens (including the shortcut in the camera app), from what I can see at the moment, QR code scanner app scans it faster/more reliably, probably because the whole workflow is tailored to do one thing, but do it well. For instance, it immediately goes into the scan mode, it "fixes" the url as soon as it finds the qr code and etc. At the end of the day, I feel like it's still more convenient.
