### ISSUE TITLE
Log?

### ISSUE THREAD

**Issue by mxmilkiib** [0x192/Universal-Android-Debloater#298]
**Describe the feature you want**
A log section to note what has been removed since the app started would be handy. I uninstalled something by accident and I'm not sure what it was.

**Comment by AnonymousWP** [comment]
> **Describe the feature you want** A log section to note what has been removed since the app started would be handy. I uninstalled something by accident and I'm not sure what it was.

[You already can.](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles) Furthermore, there's another way: simply select `Uninstalled` here:

![image](https://user-images.githubusercontent.com/50231698/178144785-b25ef8de-c826-400a-bc93-4564bcac7838.png)

In case you want to export it as log, select 'select all' and click 'export current selection'. See  https://github.com/0x192/universal-android-debloater#features as well.,
