### ISSUE TITLE
OnePlus Packages (2)

### ISSUE THREAD

**Issue by Rafee-M** [0x192/Universal-Android-Debloater#306]
**Your phone:** OnePlus 9RT
**Packages:**
```
com.oplus.athena
com.oplus.lfeh
com.oplus.stdid
com.oplus.crashbox
com.oplus.statistics.rom
com.oplus.appplatform
com.oplus.atlas
com.oplus.exsystemservice
```
- [Yes ] **I removed all those packages on my phone**

### com.oplus.athena
**List**: `Oem`
**Removal**: `Expert`
> This package kills background processes; removing it will solve delay issues but disable the virtual ram and 'close all' button in the 'recent apps' page

###  com.oplus.lfeh
**List**: `Oem`
**Removal**: `Recommended`
> Seems to be related to the the logging suite.  

###  com.oplus.stdid
**List**: `Oem`
**Removal**: `Advanced`
> Needed for tracking battery usage on per app basis

###  com.oplus.crashbox 
**List**: `Oem`
**Removal**: `Recommended`
> Sends system failure data to developers.

###  com.oplus.statistics.rom
**List**: `Oem`
**Removal**: `Advanced`
> Allows sending user data (can be opted out of). Breaks search functionality in the Settings app.

###  com.oplus.appplatform
**List**: `Oem`
**Removal**: `Advanced`
> Might be renamed package of com.heytap.appplatform which is related to Oppo's Heytap account services.

###  com.oplus.atlas
**List**: `Oem`
**Removal**: `Advanced`
> Should perform like a free antivirus

###  com.oplus.exsystemservice
**List**: `Oem`
**Removal**: `Expert`
> The screenshot function will stop working when the app is disabled.

**Comment by 0x192** [comment]
Thanks for your help! It's finally merged! :tada:

I needed some time to improve the description of all these apps.
