### ISSUE TITLE
ADB not found (even though it's in path and UAD is in the same folder)

### ISSUE THREAD

**Issue by vurtomatic** [0x192/Universal-Android-Debloater#309]
**Describe the bug**
On a Mac, double-clicking on UAD triggers ADB not found warning. The GUI shows no devices/emulators found.

**Expected behavior**
UAD to run.

**You have a solution?**
What to do to fix the issue.

**UAD log**
Log uploaded
[UAD_20220715.log](https://github.com/0x192/universal-android-debloater/files/9124966/UAD_20220715.log)

**Comment by 0x192** [comment]
Are you really sure adb is working? That's not what the logfile says.

To test if ADB is working (or accessible by UAD), from the UAD directory run this command:
```batch
adb devices
```
