### ISSUE TITLE
I am unable to install 'UAD'

### ISSUE THREAD

**Issue by Naman-1808** [0x192/universal-android-debloater#313]
**Describe the bug**

Hello, 
           I have Win7 32 Bit and i get the pop up stated below when i try to instal 'UAD'
"The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."
 
So pleases assist me up with a solution

a screenshot of pop up ![issue with UAD](https://user-images.githubusercontent.com/109581656/179709503-3e5122c2-2c97-4663-a052-59da7e82e4f0.PNG)

**Comment by VeH-c** [comment]
You probably have a 32 bit version of windows 7, and UAD is complied/made for a 64 bit OS
here is a couple articles on how too tell
https://www.lifewire.com/am-i-running-a-32-bit-or-64-bit-version-of-windows-2624475
https://support.microsoft.com/en-us/topic/determine-whether-your-computer-is-running-a-32-bit-version-or-64-bit-version-of-the-windows-operating-system-1b03ca69-ac5e-4b04-827b-c0c47145944b

32bit Windows means you can't use UAD, sorry, maybe try linux?

**Comment by Naman-1808** [comment]
Thanks for information I just want to know if It's for 32bit or not
