### ISSUE TITLE
Can't restore uninstalled apps on Android.

### ISSUE THREAD

**Issue by mizzunet** [0x192/universal-android-debloater#315]
I debloated several apps. Now, I want one app, `com.google.androd.webview` to be reinstalled.

But the following execution fails,
```
 adb shell cmd package install-existing --user 0 com.google.android.webview              ✔ 
/system/bin/sh: cmd: not found
```

Is there a way to reinstall it?

Thanks

Edit:
And I can't use `pm disable`, so I'd be able to `enable` it
```
adb shell pm disable com.android.externalstorage       ✔ 
Error: java.lang.SecurityException: Permission Denial: attempt to change component state from pid=3332, uid=2000, package uid=10006
```

**Comment by mizzunet** [comment]
I even tried reinstalling the package manually, taking the apk from `system`. It didn't show up there, though it was a 'suceess'

```
 ~  adb install -r WebViewGoogle/WebViewGoogle.apk                                    ✔  17s 
Performing Push Install
WebViewGoogle/WebViewGoogle.apk: 1 file pushed...skipped. 8.2 MB/s (113851021 bytes in 13.262s)
	pkg: /data/local/tmp/WebViewGoogle.apk
Success
```

**Comment by AnonymousWP** [comment]
> I even tried reinstalling the package manually, taking the apk from `system`. It didn't show up there, though it was a 'suceess'
> 
> ```
>  ~  adb install -r WebViewGoogle/WebViewGoogle.apk                                    ✔  17s 
> Performing Push Install
> WebViewGoogle/WebViewGoogle.apk: 1 file pushed...skipped. 8.2 MB/s (113851021 bytes in 13.262s)
> 	pkg: /data/local/tmp/WebViewGoogle.apk
> Success
> ```

Does this include downloading the APK from APKMirror, then installing it via your phone itself (without ADB)?

**Comment by 0x192** [comment]
What is your Android version? 

Try using this command instead: `adb shell pm install-existing --user 0 com.google.android.webview`

**Comment by mizzunet** [comment]
> What is your Android version?

It was Android 6

> Try using this command instead: adb shell pm install-existing --user 0 com.google.android.webview

Sorry I can't. The phone was pretty old, now it's completely dead because some issue with battery. So, I dumped it. I'm closing this issue as well.

**Comment by Rudxain** [comment]
Wait! I have a **very** similar problem with an SM-G532M (Android 6.0.1). UAD can't enable, nor restore, packs. I can only use ADB to uninstall disabled/enabled apps. It also happens with non-system built-in apps like OneDrive (`com.microsoft.skydrive`) and FB (com.facebook.katana)
