### ISSUE TITLE
flickering Problem

### ISSUE THREAD

**Issue by AhmedNazir** [0x192/Universal-Android-Debloater#317]
**Describe the bug**
UI is going to flickering when mouse coursor on this app.
**Expected behavior**
It should be stable to look
**You have a solution?**
No
**UAD log**

**Comment by AnonymousWP** [comment]
I think this means you need the other version: the OpenGL version. I had the same on my laptop. Go to assets and choose the OpenGL version. This should fix it.

**Comment by AhmedNazir** [comment]
> 

Thanks.

Different version is working finely.

**Comment by AnonymousWP** [comment]
> > 
> 
> Thanks.
> 
> Different version is working finely.

No problem. Can you then close this issue as solved?

**Comment by AhmedNazir** [comment]
### If UAD flickers then use `uad_gui-windows-opengl.exe `version
