### ISSUE TITLE
Save what packages I removed last time

### ISSUE THREAD

**Issue by DarkToaster69** [0x192/Universal-Android-Debloater#319]
Save what packages I removed last time.

**Comment by AnonymousWP** [comment]
> Save what packages I removed last time.

[You already can.](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles) Furthermore, there's another way: simply select `Uninstalled` here:

![image](https://user-images.githubusercontent.com/50231698/178144785-b25ef8de-c826-400a-bc93-4564bcac7838.png)

In case you want to export it as log, select 'select all' and click 'export current selection'. See  https://github.com/0x192/universal-android-debloater#features as well. Close the issue if this fixes your question.
