### ISSUE TITLE
ua-windows-0.1-i686.exe crash

### ISSUE THREAD

**Issue by 0x192** [0x192/universal-android-debloater#32]
In GitLab by @lawson85 on Sep 22, 2021, 13:04

This version crashes when launching on a HP Compaq 610 (https://support.hp.com/us-en/product/compaq-610-notebook-pc/3958407/document/c01767233). All drivers are updated. 

uad-windows-0.1-x86_64.exe crashes and says to find another version:

![image](https://{{overrideURL}}/414585797/30417cbb73ff0feadf02acc20abc6178.png{{overrideSuffix}})

**Comment by 0x192** [comment]
In GitLab by @W1nst0n on Sep 22, 2021, 17:57

This is an old laptop which doesn't support Vulkan so this is expected.

I have plan to release a OpenGL version for older computers (#29)

**Comment by 0x192** [comment]
In GitLab by @W1nst0n on Sep 25, 2021, 18:56

@lawson85 

The [OpenGL build](https://gitlab.com/W1nst0n/universal-android-debloater-rs/-/jobs/1622642046/artifacts/raw/target/x86_64-pc-windows-gnu/release/uad_gui-opengl.exe) should work on this computer :)

**Comment by 0x192** [comment]
In GitLab by @lawson85 on Sep 25, 2021, 19:17

![image](https://{{overrideURL}}/414585797/a9d6245aa5934932448f89b46b446573.png{{overrideSuffix}})

Again, Sorry

**Comment by 0x192** [comment]
In GitLab by @W1nst0n on Sep 25, 2021, 20:52

Huh? And [this one (i686)](https://gitlab.com/W1nst0n/universal-android-debloater-rs/-/jobs/1622642045/artifacts/raw/target/i686-pc-windows-gnu/release/uad_gui-opengl.exe) too?

**Comment by 0x192** [comment]
In GitLab by @lawson85 on Sep 26, 2021, 13:38

This does not throw the error but does not launch. uad log file is generated but has no content

<details><summary>...</summary>

On Saturday, 25 September 2021, 19:52:32 BST, W1nst0n (@W1nst0n) <gitlab@mg.gitlab.com> wrote:  
 
  
W1nst0ncommented:

Huh? And this one (i686) too?

—
Reply to this email directly or view it on GitLab.
You're receiving this email because of your account on gitlab.com.If you'd like to receive fewer emails, you canunsubscribefrom this thread oradjust your notification settings.

</details>

**Comment by lawson85** [comment]
0.4.1 neither openGL or normal opens, throws the same error
