### ISSUE TITLE
com.miui.miwallpaper after debloat the phone take more time to boot

### ISSUE THREAD

**Issue by ll0r3nt3** [0x192/Universal-Android-Debloater#321]
**Your phone**: \<Xiaomi Mi 10T Pro (Happen in miui 12.5 and 13\>

**Describe the issue**
After deleting the com.miui.miwallpaper application the phone always takes longer to start (approximately 15 seconds longer)

This has been happening from miui 12.5 to 13
**You have a solution?**
Dont debloat 

**UAD log**
No log

**Comment by AnonymousWP** [comment]
> **Your phone**: <Xiaomi Mi 10T Pro (Happen in miui 12.5 and 13>
> 
> **Describe the issue** After deleting the com.miui.miwallpaper application the phone always takes longer to start (approximately 15 seconds longer)
> 
> This has been happening from miui 12.5 to 13 **You have a solution?** Dont debloat
> 
> **UAD log** No log

What do you propose? A different description? A different `removal`?

**Comment by ll0r3nt3** [comment]
> What do you propose? A different description? A different `removal`?

Basically, put it in the app description and move it to the expert section.

**Comment by AnonymousWP** [comment]
> > What do you propose? A different description? A different `removal`?
> 
> Basically, put it in the app description and move it to the expert section.

What do you think about this? https://github.com/0x192/universal-android-debloater/pull/324

**Comment by ll0r3nt3** [comment]
> What do you think about this? #324

Nice, thx
