### ISSUE TITLE
windows 7 64

### ISSUE THREAD

**Issue by 2urtle** [0x192/Universal-Android-Debloater#322]
When trying to run .exe both normally and as administrator a window flashes on momentarily then nothing.

I have only just discovered this product after finding xiaomiADBfastboot tools and looking to see if I could get rid of apps on my motorola.

**Comment by ll0r3nt3** [comment]
Did you copy the .exe to the folder you downloaded? you should have more or less 18-19 files in that folder

**Comment by 2urtle** [comment]
My mistake I had not followed the instructions (possibly because it wasn't in big letters for me to find. lol)
but I have now and it still isn't running. Although I only have 16 files including uad exe. So I guess I am missing something.
![uad](https://user-images.githubusercontent.com/110163314/182840497-612a5be5-dd3a-45fc-8ae4-498bf9851df1.gif)
I have recently used the xiaomi debloater which worked on a redmi note 8 pro. I have many other android devices that might benefit from this. Including a new redmi note 10 which I haven't used yet other than to uninstall the apps it allows.

**Comment by 0x192** [comment]
Did you try the opengl version ([`uad_gui-windows-opengl.exe`](https://github.com/0x192/universal-android-debloater/releases/download/0.5.1/uad_gui-windows-opengl.exe))?

Upload [the logs](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles) please (this is asked in the issue template...). I can't help you without.
