### ISSUE TITLE
com.miui.home breaks menu button

### ISSUE THREAD

**Issue by 443Port** [0x192/Universal-Android-Debloater#325]
My phone model: Mi 11 Lite 5G

**Packages documentation to update:**
```
com.miui.home
```
## Documentation change
Change It from Advanced to Expert

There was a lot of stuff to fill out here that i didn't know...
So let me just get it straight:
Deleting this package breaks the menu button (i only tested it on my phone sooo i don't know if other people have this issue)

**Comment by 0x192** [comment]
So you installed another launcher, then removed `com.miui.home` and the menu button didn't work anymore? By menu button you mean apps menu?

Unfortunately, removing stock launchers often breaks some stuff even if using a 3-party one.

**Comment by 443Port** [comment]
> So you installed another launcher, then removed `com.miui.home` and the menu button didn't work anymore? By menu button you mean apps menu?

Yes it did not work. What  o mean by the app menu is like the menu with open apps

**Comment by RueleuR** [comment]
I can confirm this for the Xiaomi Mi 11 lite 5G. If you install an alternate launcher and remove com.miui.home than you will lose navigation gestures and the possibility in the settings to setup or change the startscreen too. - But I have to say with older MIUI like 12.5 with Android 10 on an Redmi 7a this app com.miui.home could be uninstalled without any mayor issues. There you will not lose the navigation features. So it depends for Xiaomi/Redmi/POCO devices on the MIUI and Android version which is installed.
