### ISSUE TITLE
Removing com.android.stk and com.google.android.setupwizard breaks mobile identity management

### ISSUE THREAD

**Issue by nixingyang** [0x192/Universal-Android-Debloater#327]
**Your phone**: irrelevant

**Packages documentation to update:**
```
com.android.stk
com.google.android.setupwizard
```

### com.android.stk
**Removal**: Recommended :arrow_right: Advanced

### com.google.android.setupwizard
**Removal**: Recommended :arrow_right: Advanced

Note that it might be necessary to update the documentation for `com.android.stk2` as well.

**Comment by ll0r3nt3** [comment]
what identity?

**Comment by nixingyang** [comment]
@ll0r3nt3 It is [mobile identity management](https://en.wikipedia.org/wiki/Mobile_identity_management).
