### ISSUE TITLE
S Finder description

### ISSUE THREAD

**Issue by c24w** [0x192/Universal-Android-Debloater#329]
**Your phone**: Samsung SM-X200

**Packages documentation to update:**
```
com.samsung.android.app.galaxyfinder
```

## Documentation change

**Current description**
> S Finder is a search application that allows you to find what you want in an instant by searching the content on your \nGalaxy smartphone and on the web as well. (https://www.samsung.com/global/galaxy/what-is/s-finder/)\nNOTE : Removing this seems to also remove the search bar in the settings and the dialer. Can someone confirm?\n

Regarding "Can someone confirm?":
 - Searching settings still works.
 - Can't confirm about the dialler, since I removed it and it doesn't want to come back 😬 
 - It breaks search in the home screen app 'drawer'.

**Comment by AnonymousWP** [comment]
Do you believe this is okay? https://github.com/0x192/universal-android-debloater/pull/331

**Comment by c24w** [comment]
I actually think uninstalling some other things broke the dialler, so I wouldn't be confident blaming this package. I haven't managed to restore the dialler to confirm.

Also, whilst searching settings works on my device, I wouldn't be surprised if it broke on other devices.

In other words: I'd only add a hint that this might break the app drawer, as well as the the dialler and settings search bars.

**Comment by 0x192** [comment]
Thanks for the report! :slightly_smiling_face: 

> I haven't managed to restore the dialler to confirm.

Restoring `com.android.phone` doesn't work?

**Comment by c24w** [comment]
The uninstall button is disabled for `com.android.phone`, so I guess I don't have it? I restored `com.samsung.android.dialer` and rebooted and it did reappear, momentarily, but then it vanished and is refusing to show itself!
