### ISSUE TITLE
com.motorolla.launcher3 removal will make Recent Apps screen unreachable on Android 12

### ISSUE THREAD

**Issue by Wilker-uwu** [0x192/Universal-Android-Debloater#330]
**Your phone**: XT2231-1 (Motorolla Moto G22)

**Packages documentation to update:**
```
com.motorolla.launcher3
```
## Documentation chage
**List**: `Oem` (manufacturer)  
**Removal**: `Advanced`

### com.motorolla.launcher3
**List**:  `Oem` (manufacturer) :arrow_right: `Oem` (manufacturer) (no change)
**Removal**: `Advanced` :arrow_right: `Expert` (this can break important features)

**Current description**
> Motorolla system Launcher  
It's basically the home screen, the way icons apps are organized and displayed.  
DON'T REMOVE THIS IF YOU DIDN'T INSTALL ANOTHER LAUNCHER !

**Proposed description**
> Motorolla system Launcher  
A default home screen program, provides a layout and display for app icons and listing.  
>   
> Removing this WILL make the Home screen unreachable if you haven't set up another launcher app as Default first.  
Removing this WILL make the Recent Apps screen unreachable, since it also seems to provide that screen (tested on Android 12, sample size 1)

**Comment by AnonymousWP** [comment]
What do you think of https://github.com/0x192/universal-android-debloater/pull/332?
