### ISSUE TITLE
Option to import / mark the application from a saved .txt file

### ISSUE THREAD

**Issue by SamsungUser2k22** [0x192/Universal-Android-Debloater#339]
Since universal android debloater has exports of saved applications to a .txt file on Windows, why not add an option to import saved applications from a .txt file. A great option, such as the android format, and you would like to remove bloatware applications in a few clicks (using the list in the txt file)

![1](https://user-images.githubusercontent.com/110987053/183920108-1adeeb8f-e9ee-4928-91c0-22c2c77b0aaa.jpg)
![2](https://user-images.githubusercontent.com/110987053/183920115-34248f75-4e3a-4af6-9e8a-dc5e86f4c861.jpg)
![3](https://user-images.githubusercontent.com/110987053/183920118-e14f83e3-6d63-46ce-8491-0f263cb05b32.jpg)
![4](https://user-images.githubusercontent.com/110987053/183920121-1e853647-b4e7-4e63-bb92-7cd636ea3da9.jpg)

**Comment by onguarde** [comment]
i second this idea, helps to manage and re-enable stuff more easily. can imagine it's really useful to get a custom debloat list for you Samsung S9 from the internet, then simply import into the app to debloat your app. 

honestly, the export feature should prompt for a filename. Especially if we're managing multiple lists of exported apps. Annoying to keep having to rename in explorer.

**Comment by 0x192** [comment]
The feature exists but is not user-friendly at all. This will drastically be improved in the next release! :slightly_smiling_face: 

See #192

**Comment by SamsungUser2k22** [comment]
Hi

Thank you for your response. But I understand that the import option for
selecting packages from a txt file will be in UAD? Because really, your
tool is good, but I miss this import option the most ...

Well, unless there is a method at the moment ... (similar, but there is),
and I just don't know about it ...

sob., 20 sie 2022, 07:46 użytkownik Tinker ***@***.***>
napisał:
