### ISSUE TITLE
Theme center not uninstalling

### ISSUE THREAD

**Issue by ghost** [0x192/universal-android-debloater#341]
**Bug Description**
The theme center package got removed with a click but com.samsung.android.themecenter is showing errors

**Expected behavior**
It should easily delete the package

**You have a solution?**
Typo error?

**UAD log**
```
[Advanced] pm uninstall --user 0 com.samsung.android.themecenter -> Failure [DELETE_FAILED_INTERNAL_ERROR] 2022-08-11 08:28:17 ERROR [src/core/utils.rs:228]  
[Advanced] pm uninstall --user 0 com.samsung.android.themecenter -> Failure [DELETE_FAILED_INTERNAL_ERROR] 2022-08-11 08:28:20 ERROR [src/core/utils.rs:228]
[Advanced] pm uninstall --user 0 com.samsung.android.themestore -> Success
```

As you can see com.samsung.themestore got deleted easily

**Comment by TubbyCat** [comment]
reconnect to adb server  
```sh
adb kill-server
adb start-server
```
try running commands again.
If fails as above:

```sh 
then run uninstall -k --user 0 (removes but keeps cache) 
if fail: 
pm list packages | cut -f 2 -d ":" | grep com.samsung.android.themecenter
and 
pm list packages | cut -f 2 -d ":" | grep com.samsung.android.theme 
```
may have to use different greps as exhibited above, to see if a package by that name even exists, or if it spelled differently than you thought. 

**if you want a better summary on how to use these commands, see:** 

https://github.com/TubbyCat/droid_debloat_and_note/blob/main/guides/adb-commands.md

**Comment by TubbyCat** [comment]
the package you are trying to remove may be restricted from removal by normal user. If this is the case you may have to disable instead of uninstall

**Comment by ghost** [comment]
Yup disabling worked instead of uninstalling it completely 

thank you very much

**Comment by Rudxain** [comment]
I can't even disable it on the SM-A315G. `adb` prints `Package com.samsung.android.themecenter new state: default` instead of "new state: disabled"

**Comment by Rudxain** [comment]
(Replying to https://github.com/0x192/universal-android-debloater/issues/651#issuecomment-1482513826 , by @MenarikanCerita. I commented here to avoid being off-topic)

> what OS you on now?

OneUI 4.1, Android 12.

> i disabled those apps while i'm on One UI 5 (android 13)

oh... it seems Samsung allowed disabling it

> there is no developer for M32 in XDA, no one doing mod on it.

Oh right, because it's too new 🙁

> So i'm very glad that there is someone who developed such tool for every devices, so i can optimized my devices by my own eventhough i'm not tech geek my self.

I agree with that

> sorry if OOT.

It's ok, don't worry

**Comment by MenarikanCerita** [comment]
> OneUI 4.1, Android 12.

maybe there is limitation in OneUI 4.1, mate.

> oh... it seems Samsung allowed disabling it

thats right, i think it's because the theme apps isn't had impact in system operation. i also disable some samsung features too, such as Routines,McAfee (security feature), and Samsung Keyboard. luckly nothing happened to my phone.

> Oh right, because it's too new 🙁

it dont think so, mate. my wife has A32, and i try to look at XDA forum for it, the result is not same as for M32. haha

> (Replying to [#651 (comment)](https://github.com/0x192/universal-android-debloater/issues/651#issuecomment-1482513826) , by @MenarikanCerita. I commented here to avoid being off-topic)

ok, thanks a lot, mate

**Comment by Rudxain** [comment]
> thats right, i think it's because the theme apps isn't had impact in system operation.

That's a reasonable hypothesis. I agree.

> i also disable some samsung features too, such as Routines,McAfee (security feature), and Samsung Keyboard. luckly nothing happened to my phone.

Nice!

> it dont think so, mate. my wife has A32, and i try to look at XDA forum for it, the result is not same as for M32. haha

Interesting 🤔. Perhaps the M32 isn't popular in the dev community?
