### ISSUE TITLE
Comments for two xiaomi Services com.miui.notification com.xiaomi.miplay_client

### ISSUE THREAD

**Issue by RueleuR** [0x192/Universal-Android-Debloater#345]
**Your phone**: \<Redmi Note 11 on Android 11 with MIUI 13\>

**Packages documentation to update:**
```
com.miui.notification
com.xiaomi.miplay_client
...
```
## Documentation chage
**List**: `Google`|`Misc`|`Oem` (manufacturer)|`Aosp`|`Pending`|`Carrier` (isp).
**Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features), `Unsafe` (this can bootloop the phone or break extremely important features).

### \<com.miui.notification\>
**List**:  \<current list\> :arrow_right: \<Xiaomi MIUI 13 Android 11\>
**Removal**: \<current recommendation list\> :arrow_right: \<Expert\>

**Current description**
> 
![image](https://user-images.githubusercontent.com/57115151/184555699-f889b6b4-fb43-4438-8c1f-0fd76f1ad911.png)

**Proposed description**
> Notifications are working without this app. It is possible to access the app notification setting with long pressing on the notification without the app. Notification settings in the settings menue will be broken without the app. The app is mandatory to enable notifications of apps that have been disabled before.

### \<com.xiaomi.miplay_client\>
**List**:  \<current list\> :arrow_right: \<Xiaomi MIUI 13 Android\>
**Removal**: \<current recommendation list\> :arrow_right: \<Advanced\>

**Current description**
> 
![image](https://user-images.githubusercontent.com/57115151/184555825-4af4379d-2852-4e5d-ab03-ab90c5dc3e8b.png)

**Proposed description**
> MiPlay Client provides Cast Services for Wireless Display feature. --> I can confirm this.

**Comment by 0x192** [comment]
Thanks for your report! The documentation has finally be updated! :tada:
