### ISSUE TITLE
Tablet Center app for Lenovo Tablet

### ISSUE THREAD

**Issue by DarkSkull91** [0x192/Universal-Android-Debloater#348]
**Your phone:** Lenovo Tablet P11 (TB-J606)

**Packages:**
```
com.tblenovo.center
...
```
* [Yes ] **I removed this package on my phone**

 ## Documentation change
### com.tblenovo.center
**List:** `Oem`
**Removal:** `Recommended`
 > **Description:** it's a useless dashboard.

**Comment by AnonymousWP** [comment]
> com.tblenovo.center

You didn't fill in the template correctly; it misses a description and `removal`. If you can fill in these details, I can create a PR for you. See below for template:

> **Your phone:** <phone model>
> 
> **Packages:**
> ```
> com.this.is.a.bad.application
> com.this.is.another.bad.application
> ...
> ```
> - [ ] **I removed all those packages on my phone**
> If not why. Leave the brackets blank and explain why.
> 
> ## Document each package the best you can
> **List**: `Google`|`Misc`|`Oem` (manufacturer)|`Aosp`|`Pending`|`Carrier` (isp).
> **Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features), `Unsafe` (this can bootloop the phone or break extremely important features).
> 
> ### \<package name\>
> **List**: \<list\> 
> **Removal**: \<recommendation list\>
> > Description. Link to its Playstore page if it exists.

**Comment by DarkSkull91** [comment]
Done.

**Comment by 0x192** [comment]
Thanks! I've also added `com.lenovo.ue.device` which is the annoying User Experience Program app
