### ISSUE TITLE
Unable to update the app from 0.5.0 to 0.5.1

### ISSUE THREAD

**Issue by AdiiSinha1234** [0x192/Universal-Android-Debloater#351]
**Describe the bug**
Unable to update the app from 0.5.0 to 0.5.1

**Expected behavior**
Showing me updating please wait from last 1 hour

**You have a solution?**
I restarted thje app multiple times

**UAD log**
No log file

**Comment by 0x192** [comment]
I cannot reproduce on Linux. What OS do you use?

I can't help if you don't upload the logfile. [There is always a logfile](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles).
