### ISSUE TITLE
No Keyboard?

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#353]
My phone is a Samsung S22+

My problem is that after I debloated my phone, I couldn't access my keyboard anywhere. It comes back only if I bloat everything again.

My Universal Android Debloater is on the latest version, 0.51 I think.

android.autoinstalls.config.samsung
com.amazon.appmanager
com.amazon.mShop.android.shopping
com.android.apps.tag
com.android.bips
com.android.bluetoothmidiservice
com.android.bookmarkprovider
com.android.calllogbackup
com.android.carrierdefaultapp
com.android.chrome
com.android.companiondevicemanager
com.android.dreams.basic
com.android.dreams.phototable
com.android.egg
com.android.hotwordenrollment.okgoogle
com.android.hotwordenrollment.xgoogle
com.android.htmlviewer
com.android.keychain
com.android.mtp
com.android.providers.calendar
com.android.providers.partnerbookmarks
com.android.simappdialog
com.android.stk
com.android.stk2
com.android.traceur
com.android.vending
com.android.wallpaper.livepicker
com.android.wallpapercropper
com.diotek.sec.lookup.dictionary
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.google.android.apps.maps
com.google.android.apps.messaging
com.google.android.apps.restore
com.google.android.apps.tachyon
com.google.android.apps.turbo
com.google.android.as
com.google.android.captiveportallogin
com.google.android.configupdater
com.google.android.documentsui
com.google.android.ext.shared
com.google.android.feedback
com.google.android.gm
com.google.android.gms
com.google.android.gms.location.history
com.google.android.googlequicksearchbox
com.google.android.gsf
com.google.android.ims
com.google.android.modulemetadata
com.google.android.networkstack
com.google.android.networkstack.permissionconfig
com.google.android.onetimeinitializer
com.google.android.overlay.modules.ext.services
com.google.android.overlay.modules.permissioncontroller.forframework
com.google.android.partnersetup
com.google.android.printservice.recommendation
com.google.android.projection.gearhead
com.google.android.setupwizard
com.google.android.syncadapters.calendar
com.google.android.syncadapters.contacts
com.google.android.tts
com.google.android.webview
com.google.android.youtube
com.google.ar.core
com.google.audio.hearing.visualization.accessibility.scribe
com.google.mainline.telemetry
com.hiya.star
com.knox.vpn.proxyhandler
com.microsoft.appmanager
com.microsoft.skydrive
com.monotype.android.font.foundation
com.monotype.android.font.samsungone
com.qti.snapdragon.qdcm_ff
com.qualcomm.location
com.qualcomm.qti.smq
com.qualcomm.timeservice
com.samsung.aasaservice
com.samsung.accessibility
com.samsung.android.aircommandmanager
com.samsung.android.allshare.service.mediashare
com.samsung.android.app.appsedge
com.samsung.android.app.camera.sticker.facearavatar.preload
com.samsung.android.app.clipboardedge
com.samsung.android.app.cocktailbarservice
com.samsung.android.app.dressroom
com.samsung.android.app.omcagent
com.samsung.android.app.reminder
com.samsung.android.app.routines
com.samsung.android.app.settings.bixby
com.samsung.android.app.spage
com.samsung.android.app.taskedge
com.samsung.android.app.watchmanagerstub
com.samsung.android.ardrawing
com.samsung.android.aremoji
com.samsung.android.aremojieditor
com.samsung.android.arzone
com.samsung.android.authfw
com.samsung.android.aware.service
com.samsung.android.bbc.bbcagent
com.samsung.android.beaconmanager
com.samsung.android.bixby.agent
com.samsung.android.bixby.service
com.samsung.android.bixby.wakeup
com.samsung.android.bixbyvision.framework
com.samsung.android.calendar
com.samsung.android.da.daagent
com.samsung.android.dqagent
com.samsung.android.dynamiclock
com.samsung.android.easysetup
com.samsung.android.fast
com.samsung.android.fmm
com.samsung.android.forest
com.samsung.android.game.gamehome
com.samsung.android.game.gametools
com.samsung.android.honeyboard
com.samsung.android.ipsgeofence
com.samsung.android.kidsinstaller
com.samsung.android.knox.analytics.uploader
com.samsung.android.knox.attestation
com.samsung.android.knox.containeragent
com.samsung.android.knox.containercore
com.samsung.android.knox.pushmanager
com.samsung.android.livestickers
com.samsung.android.location
com.samsung.android.mateagent
com.samsung.android.mdecservice
com.samsung.android.mdm
com.samsung.android.mdx
com.samsung.android.mdx.kit
com.samsung.android.mdx.quickboard
com.samsung.android.mobileservice
com.samsung.android.net.wifi.wifiguider
com.samsung.android.networkdiagnostic
com.samsung.android.provider.filterprovider
com.samsung.android.rubin.app
com.samsung.android.samsungpass
com.samsung.android.samsungpassautofill
com.samsung.android.samsungpositioning
com.samsung.android.scloud
com.samsung.android.sdk.handwriting
com.samsung.android.sdm.config
com.samsung.android.service.peoplestripe
com.samsung.android.shortcutbackupservice
com.samsung.android.smartcallprovider
com.samsung.android.smartface
com.samsung.android.smartmirroring
com.samsung.android.smartswitchassistant
com.samsung.android.stickercenter
com.samsung.android.svcagent
com.samsung.android.svoiceime
com.samsung.android.themestore
com.samsung.android.visionintelligence
com.samsung.android.wifi.softap.resources
com.samsung.desktopsystemui
com.samsung.faceservice
com.samsung.ipservice
com.samsung.klmsagent
com.samsung.knox.securefolder
com.samsung.mlp
com.samsung.safetyinformation
com.samsung.storyservice
com.samsung.systemui.bixby2
com.samsung.ucs.agent.ese
com.samsung.vvm
com.sec.android.app.apex
com.sec.android.app.applinker
com.sec.android.app.billing
com.sec.android.app.bluetoothtest
com.sec.android.app.camera
com.sec.android.app.chromecustomizations
com.sec.android.app.DataCreate
com.sec.android.app.desktoplauncher
com.sec.android.app.dexonpc
com.sec.android.app.factorykeystring
com.sec.android.app.hwmoduletest
com.sec.android.app.magnifier
com.sec.android.app.parser
com.sec.android.app.quicktool
com.sec.android.app.safetyassurance
com.sec.android.app.sbrowser
com.sec.android.app.SecSetupWizard
com.sec.android.app.servicemodeapp
com.sec.android.app.setupwizardlegalprovider
com.sec.android.app.soundalive
com.sec.android.app.wlantest
com.sec.android.cover.ledcover
com.sec.android.daemonapp
com.sec.android.desktopmode.uiservice
com.sec.android.diagmonagent
com.sec.android.easyMover.Agent
com.sec.android.easyonehand
com.sec.android.mimage.avatarstickers
com.sec.android.RilServiceModeApp
com.sec.android.widgetapp.easymodecontactswidget
com.sec.app.RilErrorNotifier
com.sec.bcservice
com.sec.enterprise.knox.cloudmdm.smdms
com.sec.enterprise.mdm.services.simpin
com.sec.epdgtestapp
com.sec.factory
com.sec.factory.camera
com.sec.hearingadjust
com.sec.hiddenmenu
com.sec.imslogger
com.sec.location.nsflp2
com.sec.modem.settings
com.sec.phone
com.sec.spp.push
com.sec.sve
com.sec.usbsettings
com.sec.vsim.ericssonnsds.webapp
com.sem.factoryapp
com.skms.android.agent
com.wsomacp
com.wssyncmldm

**Comment by ghost** [comment]
My wallpaper tab in settings is gone, please help!

**Comment by ll0r3nt3** [comment]
There will not be two threads to say the same
https://github.com/0x192/universal-android-debloater/issues/352

**Comment by VeH-c** [comment]
[Xertzion](https://github.com/Xertzion) reinstall all packages(Apps) then use the "Recommended" and not "Advanced" or "Expert" to avoid these issues. thanks!  

@0x192 close this please
