### ISSUE TITLE
Include non-system apps

### ISSUE THREAD

**Issue by claude-ws01** [0x192/Universal-Android-Debloater#362]
UAD not listing all packages, no matter the filters.

=== Summary of number of packages
- uad_exported_selection = 200
- adb shell cmd package list packages -e -u = 214
- adb shell cmd package list packages -3 -u = 14

=== Exported selection
Created with filters set to <All, All packages, All lists>.   
Whatever the filters, I never got over 200 entries, nor did I ever found "com.amazon.mp3" (my test search string).

=== Which ones are missing ?
Comparing the 200 and the 214 list gives me exactly the 14 list which is:
>com.amazon.mp3
>com.google.android.apps.chromecast.app
>com.google.android.apps.docs.editors.docs
>com.google.android.apps.docs.editors.sheets
>com.google.android.apps.docs.editors.slides
>com.google.android.apps.fitness
>com.google.android.apps.magazines
>com.google.android.apps.nbu.files
>com.google.android.apps.podcasts
>com.google.android.calculator
>com.microsoft.bing.wallpapers
>com.tblenovo.soundrecorder
>com.topjohnwu.magisk
>io.github.muntashirakon.AppManager

=== Specs
    Lenovo M10 tablet
    android 10 freshly installed with Lenovo's stock ROM
    UAD v0.5.1
    ADB Android Debug Bridge version 1.0.41 (Version 33.0.3-8952118)

=== UAD log === (there's nothing more)
2022-08-26 19:08:39 DEBUG [src\core\update.rs:178] Checking for UAD update
2022-08-26 19:08:39 WARN  [src\gui\mod.rs:102] Trying to download remote UAD list
2022-08-26 19:08:40 INFO  [src\gui\mod.rs:457] -----------------------------------------------------------------
2022-08-26 19:08:40 INFO  [src\gui\mod.rs:458] ANDROID_SDK: 29 | PHONE: Lenovo Lenovo TB-X306F
2022-08-26 19:08:41 WARN  [src\gui\views\list.rs:142] No custom selection imported: The system cannot find the file specified. (os error 2)

Thank you.

**Comment by 0x192** [comment]
That's because those are not system apps. You can directly uninstall them in the settings of your phone. :slightly_smiling_face: 

UAD will support them in the future. See #365

**Comment by claude-ws01** [comment]
"You can directly uninstall them in the settings of your phone."
So can I uninstall/disable ANY apps with "App Manager". 

So WHY use UAD ??
My 2 reasons:
1. I can do it from my Windows PC.
2. It is quick; I can select each apps I want to uninstall/disable, and GO.

Currently only processing "system" apps??? 
Are ALL uad_lists.json's 2223 entries "system" packages ???
11 of my 14 "non system" packages are in the uad_lists.json file !!!

Please do not waste time with BS answers.  You're not on FB but on Github (less simple users)
Thank you for acknowledging the issue.
Regards.

**Comment by 0x192** [comment]
There is no need to be aggressive.  May I also kindly remind you that I develop this software in my free time? 

> Please do not waste time with BS answers. You're not on FB but on Github (less simple users)

 That's not a BS answer. Of course, it would be quicker if you could uninstall them from UAD but userland apps were not a priority precisely because you can uninstall them without ADB or root (unlike system apps). 

> Are ALL uad_lists.json's 2223 entries "system" packages ???

All those packages have been seen installed as system apps. However, on some phones, some of them have been installed as user apps by the OEM (which is a good thing).

**Comment by claude-ws01** [comment]
"Aggressive" ?!  You are confusing firmness with aggresivity. (This is probably a generational thing, I don`t sugarcoat everything I say).
I'm well aware of your taking care of this software on your limited free time... so why waste it on unecessary explainations/justifications (which actually lead nowhere) ?

My only purpose here was to provide you with clear & detailed information about what I found.  Nothing more.  No requests.
If more information is required to support my original "issue description", by all means notify me.
Otherwise thank you for sharing UAD,
Have a good day,
Claude.

**Comment by 0x192** [comment]
> "Aggressive" ?! You are confusing firmness with aggresivity. (This is probably a generational thing, I don`t sugarcoat everything I say).

It was probably the typography (a lot of ??? !!!)

> I'm well aware of your taking care of this software on your limited free time... so why waste it on unecessary explainations/justifications (which actually lead nowhere) ?

Fair enough. I get you point. See my initial reply more as an acknowledgement of your issue. I didn't want to close the issue without a reply. It would be a bit rude.

Ok ok I stop replying! I'm wasting time haha!

Have a nice day too

**Comment by claude-ws01** [comment]
Thx
All good
Take care. ;)
