### ISSUE TITLE
Not able to use Debloater for OPPO F3

### ISSUE THREAD

**Issue by OmkarB03** [0x192/Universal-Android-Debloater#366]
Oppo F3 \CPH1609

**Describe the issue**
Whenever i use debloater it shows no emulators or devices found even though in CMD my device is show but Universal Debloater cannot detect it 

**You have a solution?**
No solution 

**UAD log**
Upload the logfile generated by
[UAD_20220901.log](https://github.com/0x192/universal-android-debloater/files/9467254/UAD_20220901.log)
 UAD. You can hardly be helped without.

**Comment by 0x192** [comment]
That's because UAD doesn't find ADB. You need to add ADB to your PATH. It's explained in the `How to use` section of the README : https://github.com/0x192/universal-android-debloater#how-to-use-it
