### ISSUE TITLE
On Moto G52, VPN and Data Roaming setting also get removed.

### ISSUE THREAD

**Issue by assmaster420** [0x192/Universal-Android-Debloater#367]
Motorola Moto G52 Android 12 (S1SR32.38-124-3)

**Describe the issue**
After removing all the recommended apps, VPN and Data Roaming settings are gone. Earlier, I used to restore everything and move on but now those settings are not appearing again.
Maybe there are other important settings which are also removed but so far I've only found these two.

Thank you so much for everything. 

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.
[UAD_20220820.log](https://github.com/0x192/universal-android-debloater/files/9468907/UAD_20220820.log)
[UAD_20220901.log](https://github.com/0x192/universal-android-debloater/files/9468908/UAD_20220901.log)

**Comment by 0x192** [comment]
> Thank you so much for everything.

Thanks you :slightly_smiling_face: 

> Earlier, I used to restore everything and move on but now those settings are not appearing again.

Are you saying you already have restored everything and it doesn't fix the problem? Because according to the log, the last executed commands were `pm uninstall`.

If you ask for help to know what package(s) to restore to fix the issue, you are better placed than me to success. It's possible that a Motorola package in the `Recommended` list can no longer be removed on Android 12. 

Maybe one of these 2? 
```
com.motorola.systemserver
com.motorola.vzw.pco.extensions.pcoreceiver
```

**Comment by assmaster420** [comment]
It's super weird for some reason. After removing all the recommended packages, sometimes VPN setting remains while sometimes it doesn't. Data Roaming is removed all the time.

For some reason, this time after restoring bloat, VPN settings came back and remained even after removing it all again. Can't provide logs this time as I ran Stacer. Sorry

These two aren't the ones. I restored them but nothing.

Also, why can't I remove Gboard? I know it's not in recommended but even after clicking uninstall or running ADB uninstall, it is not going. Like a piece of shit refusing to be flushed away.

Still thanks a lot for taking your time to help me out.

**Comment by AnonymousWP** [comment]
> Also, why can't I remove Gboard? I know it's not in recommended but even after clicking uninstall or running ADB uninstall, it is not going. Like a piece of shit refusing to be flushed away.

https://github.com/0x192/universal-android-debloater/issues/372#issuecomment-1236096244
