### ISSUE TITLE
Question: Which package(s) allow Samsung Pay to function?

### ISSUE THREAD

**Issue by GitHubQueenn** [0x192/Universal-Android-Debloater#368]
EDIT2: The issue was that the Galaxy Store app needed to be re-installed too.......For all that is holy, PLEASE add notes to the com.samsung.android.spayfw comments or wherever they're needed for this.

So, I uninstalled all of the "Recommended" section before realizing I could click on each package and read what it installs/uninstalls. I typed in "pay" and "wallet" into the search function, but no results are coming up but I no longer have Samsung Pay. Help? I thought the package name was "com.samsung.android.spayfw" but on the GUI, it doesn't show as uninstalled but I also can't restore it either. I just re-installed the Samsung Pay app and it opened to let me give it contacts/phone permissions but then it crashed and when I open it now, it instantly closes....Ok, now it's letting me open the app but when I go to add a card and type in the first 8 digits, I just get a blue circle loading symbol and it basically freezes at that each time. Ok, and now that I cleared data from Samsung Wallet app and open Samsung Pay app, it gets stuck on black screen that says "Samsung Wallet." Ok, now I got it past entering the last 8 CC numbers but when I tap "Next" after filling all my info, a pop-up appears for maybe half a second that says "Validating your card info..." then does nothing.

EDIT: Also, sorry for the "bug" tag. Not sure how to do a question label. And also, if I want to re-install Bixby, do I have to install every Bixby-related package name or could I only do minimal packages for it to work?

**Comment by 0x192** [comment]
Can you list what packages you restored from the `Recommended` list to make Samsung Pay work in the end?

> And also, if I want to re-install Bixby, do I have to install every Bixby-related package name or could I only do minimal packages for it to work?

I really don't know. You can try by yourself and report back. That will probably help others. I guess it depends on the Bixy features you want. However I think most Bixby packages are interdependent.

**Comment by GitHubQueenn** [comment]
> Can you list what packages you restored from the `Recommended` list to make Samsung Pay work in the end?
> 
> > And also, if I want to re-install Bixby, do I have to install every Bixby-related package name or could I only do minimal packages for it to work?
> 
> I really don't know. You can try by yourself and report back. That will probably help others. I guess it depends on the Bixy features you want. However I think most Bixby packages are interdependent.

Yeah, so the only one that needed to be restored was Galaxy Store. The other ones I tried restoring basically had descriptions like, "only needed for some Samsung apps" but they weren't the right ones anyway that I needed. So, just Galaxy Store.

**Comment by 0x192** [comment]
Thanks for your the feedback
