### ISSUE TITLE
i uninstalled system android packages

### ISSUE THREAD

**Issue by ayushman250** [0x192/Universal-Android-Debloater#375]
**vivo**: \<vivo y 71\>

**Describe the issue**
i accidentally uninstalled the android system package from my phone and my phone is struck on logo phase and its not starting not switching off. please help

**You have a solution?**
What to do to fix the issue.

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.

**Comment by heartlog** [comment]
@ayushman250 This is dumbest thing you can do...
Don't do things without knowing the outcome...

How do I factory reset an Android phone from a computer?
Step 1: Connect Android device to the program

First download and install the iskysoft data eraser software on your PC, then launch the software and use an Android USB cable to connect it to PC. When this is done, the software will display your phone information on its main interface.

Step 2: Select Erase Mode

Check the erase mode and select the one that best suits your requirements.

Step 3: Wipe Android Data Permanently

At this point, the program will wipe your android phone from PC.

As we all know phones hold all the important data such as documents, photos, videos, audios as well as some other confidential data. And no matter what we could encounter while using it. Likewise, there are many situations where you are required to factory reset and we can easily reset our phone to fix it and erase it.

However, if the Android phone was frozen or broken, there’s no doubt that it can't factory reset itself. As known for all, easily resetting the phone within the Settings app on Android directly or hard reset Android via Recovery Mode can fix issues like this. So to help you in yo

How do you do a factory reset on an Android?
As per my opinions:

Bit Intro About Hard Reset!! :-)

A Hard Reset also known as , A factory reset, also known as A Master reset, is a software restore of an electronic device to its original system state by erasing all of the information stored on the device in an attempt to restore the device's software to its original manufacturer settings.

You can try the following procedures:

How to factory reset your phone from the settings menu?

Tap the Settings icon from your home screen or app drawer.
Swipe up to scroll down to the bottom of the settings menu.
Tap Backup and reset.
Swipe up to scroll down.
Tap Factory data reset.
Tap Reset phone.
Tap Erase everything.
Your phone will reboot and you'll have to go through the initial start up again before you're able to restore your data.

How to factory reset your phone with hardware buttons?

If your phone is on, power it off.
Hold down the Power button, Volume up button, and Home button simultaneously. The phone will boot into recovery mode.
Use the Volume buttons to scroll through the menu.
Highlight Wipe data/factory reset.
Press the Power button to select.
Highlight and select Yes to confirm the reset.
Once the reset is complete, you will be bounced back to the same recovery mode menu. Press the Power button to select Reboot system now.
Your phone will power on and be reset to its factory settings. The next time you turn the phone on, you will go through the initial setup process as if it were a brand new phone. Once set up, you can go about restoring your data from wherever you had it backed up.

**Hope This Helps!**

**Comment by ayushman250** [comment]
thanks , i already did the same
