### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by Zibri** [0x192/Universal-Android-Debloater#376]
Where are backups normally kept for the function restore to work?

**Comment by AnonymousWP** [comment]
> Where are backups normally kept for the function restore to work?

You can just export and import your 'back-up' called `uad_exported_selection.txt`. It's in the same folder/location as where you downloaded UAD.

**Comment by JFMugen** [comment]
> > Where are backups normally kept for the function restore to work?
> 
> You can just export and import your 'back-up' called `uad_exported_selection.txt`. It's in the same folder/location as where you downloaded UAD.

_Sorry if this is a dumb question but how do we import? All I can see export option._

edit. just find it from #192

**Comment by AnonymousWP** [comment]
I think this issue should be closed now it's solved and answered.
