### ISSUE TITLE
[Pkg] com.samsung.discover

### ISSUE THREAD

**Issue by s-ankur** [0x192/Universal-Android-Debloater#378]
**Your phone:** Samsung M51 SamsungM32 Samsung F22

**Packages:**
```
com.samsung.discover
com.samsung.discover.sep

```
- [x] **I removed all those packages on my phone**

## Document each package the best you can

###com.samsung.discover
**List**:`Oem`
**Removal**: `Recommended`
> It shows up as a pane on OneUI home and prompts you to install all sorts of random apps. OneUI works perfectly fine if you uninstall these and simply removes the discover pane. 

### com.samsung.discover.sep
**List**:  `Oem`
**Removal**: `Recommended`
> Related to com.samsung.discover but doesnt seem to do much on its own. Safe to remove without any effect

**Comment by 0x192** [comment]
Thanks for you for your contribution! It's finally merged! :tada:
