### ISSUE TITLE
ringtone not working for Incoming calls

### ISSUE THREAD

**Issue by scrtdev** [0x192/Universal-Android-Debloater#383]
**Your phone**: \poco x3 pro a new compnoy by xiaomi\>

**Describe the issue**
ringtone not working in incomg calls

**You have a solution?**
no, but i only removed recommanded apps from list it suggested nothing else

**Comment by 0x192** [comment]
How do you think I can help you? You didn't even post your logfile... :/

In the end. You own the phone. Not me. You're better placed to find the package(s) to restore. 

Then, I could update the `uad_lists. json` so that everyone could benefit from your finding! :slightly_smiling_face:
