### ISSUE TITLE
[Samsung] Secret codes no longer work in Phone app

### ISSUE THREAD

**Issue by realies** [0x192/Universal-Android-Debloater#392]
Even after re-enabling debug/test apps such as `com.sec.android.app.servicemodeapp` and rebooting. There must be a dependency that is missing for secret codes to work.

Edit: It appears that secret codes depend on another `com.sec.*` package. However, I have not narrowed it down yet.

**Comment by 0x192** [comment]
You didn't upload the logfile so I don't know what packages your phone has but try restoring `com.sec.android.app.parser` if you have it.
