### ISSUE TITLE
no device foun/enulator found

### ISSUE THREAD

**Issue by DarkMystic16** [0x192/Universal-Android-Debloater#395]
**Your phone:** <LG V40 ThinQ Korean Version>

**Packages:**
```
com.cnass.service
com.cnass.main
com.android.networkstack.permissionconfig
com.lge.qhelp
com.lge.lgworld
com.cnass.terms
com.lguplus.tsmproxy
com.lguplus.mobile.cs
com.uplus.oemsearch
com.lguplus.appstore
com.skt.skaf.OA00018282
...
```
- [ ] **I removed all those packages on my phone**
If not why. Leave the brackets blank and explain why.

## Document each package the best you can
**List**: `Google`|`Misc`|`Oem` (manufacturer)|`Aosp`|`Pending`|`Carrier` (isp).
**Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features), `Unsafe` (this can bootloop the phone or break extremely important features).

### \<package name\>
**List**: \<list\> 
**Removal**: \<recommendation list\>
> Description. Link to its Playstore page if it exists.

**Comment by AnonymousWP** [comment]
You didn't follow the (right) template. You're facing an issue, but you chose the wrong template. Explain it in your issue.
