### ISSUE TITLE
Exe file removed

### ISSUE THREAD

**Issue by Spec-s** [0x192/Universal-Android-Debloater#411]
hello... i am trying to get this free software to debloat my phone but the ".exe" file has been removed from the file, can u please assist with this issue

**Comment by Bjebsys** [comment]
I'm having the same issue, can't seem to find the exe after downloading. Hope someone can help!

**Comment by AnonymousWP** [comment]
For Windows, the default is the Downloads folder. I don't see the issue, it's easy to find after downloading. It's just the directory that you chose, unless you're using the default of your browser.

**Comment by Bjebsys** [comment]
Yes, the zip folder downloads and extracts just fine, but there is no uad_gui-windows application file unless its hidden somewhere and I'm just missing in

**Comment by Bjebsys** [comment]
*it

**Comment by AnonymousWP** [comment]
> Yes, the zip folder downloads and extracts just fine, but there is no uad_gui-windows application file unless its hidden somewhere and I'm just missing in

I bet you're downloading the source code. You're supposed to download the exe here: https://github.com/0x192/universal-android-debloater/releases/tag/0.5.1

![image](https://user-images.githubusercontent.com/50231698/195573497-e7720638-0102-4fef-b310-a6f56055b940.png)
