### ISSUE TITLE
Settings App Breaks After Uninstalling Digital Wellbeing

### ISSUE THREAD

**Issue by thedepartedwhiplash** [0x192/Universal-Android-Debloater#412]
Pixel 6

**Describe the issue**
After uninstalling the Digital Wellbeing app (com.google.android.apps.wellbeing), the Settings app breaks and crashes immediately every time you try to open it. Restarting the phone and clearing the cache does nothing.

**You have a solution?**
Reinstalling Digital Wellbeing and simply *disabling* it works instead. Maybe a note/warning about this can be placed in the info box for this package.

**UAD log**
Not applicable.

**Comment by 0x192** [comment]
Thanks for your report!
