### ISSUE TITLE
Closing automatically

### ISSUE THREAD

**Issue by TAJ69** [0x192/Universal-Android-Debloater#413]
After I click the uninstall or the restore button, the program is closing instantly. Everything else works fine, I can't understand why is closing.
Update:
I tried with a Xiaomi, and it is OK. Only with my Samsung A52s 5G is closing.
Any idea? Somebody?

**Comment by barankrky** [comment]
Same problem.

**Comment by barankrky** [comment]
`2022-10-15 10:09:29 INFO  [src\gui\mod.rs:80] ANDROID_SDK: 30 | PHONE: samsung SM-A307FN
2022-10-15 10:09:30 WARN  [src\gui\views\list.rs:121] No custom selection imported: Sistem belirtilen dosyayı bulamıyor. (os error 2)
2022-10-15 10:09:33 INFO  [src\core\sync.rs:202] [Recommended] pm uninstall --user 0 com.android.carrierdefaultapp
2022-10-15 10:09:33 ERROR [src\core\sync.rs:207] [Recommended] pm uninstall --user 150 com.android.carrierdefaultapp -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150`

I think that's the problem. When you create Secure Folder or work profile, UAD can't uninstall any application under user 150. I'm gonna uninstall the Secure Folder profile and see what's happen.

**Comment by TAJ69** [comment]
I don't even know where to find these profiles, or delete one of them. Why I need the Work profile anyway? Because I don't have it in Accounts menu. But I am waiting your results :-)

**Comment by barankrky** [comment]
> I don't even know where to find these profiles, or delete one of them. Why I need the Work profile anyway? Because I don't have it in Accounts menu. But I am waiting your results :-)

![191698285-81db7790-c9b8-4bb1-a6e0-a5775a04c4d3](https://user-images.githubusercontent.com/53481486/195984618-c412ff45-10ab-4f99-bfc1-e61576d6612e.png)

Disable this option in UAD Settings.

See #386

**Comment by TAJ69** [comment]
Nice. Thank you very much. It's working. Work folder is still there somewhere, I don't have those apps what you wrote, and I still have User 150. But with that option disabled, UAD is not closing.
