### ISSUE TITLE
Please support adb wireless

### ISSUE THREAD

**Issue by dieptp** [0x192/Universal-Android-Debloater#419]
Hi there.
As I mentioned in the title. Please support adb wireless protocol (you can refer to **adb appcontrol** application)
Sorry my English is so bad. Hope you guys could undertand what I tent to say 
![image](https://user-images.githubusercontent.com/31943859/197140654-85c6ff81-696f-45dd-8dff-d195e48ae1ad.png)

**Comment by AnonymousWP** [comment]
> Hi there. As I mentioned in the title. Please support adb wireless protocol (you can refer to **adb appcontrol** application) Sorry my English is so bad. Hope you guys could undertand what I tent to say ![image](https://user-images.githubusercontent.com/31943859/197140654-85c6ff81-696f-45dd-8dff-d195e48ae1ad.png)

It does, see: https://github.com/0x192/universal-android-debloater/issues/287
