### ISSUE TITLE
description of allshare package contains duplicate of airtel.stubapp package

### ISSUE THREAD

**Issue by Dimittrikov** [0x192/Universal-Android-Debloater#422]
**Your phone**: Samsung A21s

**Packages documentation to update:**
```
com.samsung.android.allshare.service.mediashare
```
## Documentation chage
**List**: `Oem`.
**Removal**: `Recommended`.

### Samsung Allshare Service
**List**:  Oem :arrow_right: Oem
**Removal**: Recommended :arrow_right: Recommended

**Current description**
> My Airtel Stub app
> My Airtel is a customer service app designed for Airtel subscribers in Sri Lanka
> This pasckage isn't the app itself but only a stub. 
> It's basically a non-functional empty shell which often only redirect you to the PlayStore to download the full app
>
> Samsung Allshare service (now called SmartView).
> Used to stream content from your phone to a Samsung smart TV.
> https://www.samsung.com/us/apps/smart-view-2/
    

**Proposed description**
> Samsung Allshare service (now called SmartView).
> Used to stream content from your phone to a Samsung smart TV.
> https://www.samsung.com/us/apps/smart-view-2/

**Note**
> The duplication of airtel description does not seem to happen anywhere else
> Additionally, the airtel package itself does not seem to have probelms with its descritption

**Comment by AnonymousWP** [comment]
I have opened a Pull Request. You do not need to close the issue this time (preferably, re-open the one you closed).

I didn't include the note, because it doesn't add much to the description of a package, but rather to the GitHub issue itself. Check my commit to check what I did.

**Comment by Dimittrikov** [comment]
yeah the note was referring to the github issue, not the description
probably not the best way of formatting the info on my part
sorry for that i'm just not that used to this side of github in general

**Comment by AnonymousWP** [comment]
> yeah the note was referring to the github issue, not the description probably not the best way of formatting the info on my part sorry for that i'm just not that used to this side of github in general

No worries, I'm glad I interpreted it correctly and that it wasn't meant to be part of the description. You contributed to the project, which is already nice, so thanks for that. 😄

**Comment by 0x192** [comment]
Thanks for your report! :slightly_smiling_face:  

The issue has been fixed in 70f508e
