### ISSUE TITLE
Move com.sec.android.app.safetyassurance to Unsafe due to its relation with emergency features

### ISSUE THREAD

**Issue by skunkmommy** [0x192/Universal-Android-Debloater#426]
**Your phone**: Galaxy A12

**Packages documentation to update:**
```
com.sec.android.app.safetyassurance
```
## Documentation change
**List**: `Samsung`
**Removal**: `Recommended`

### \ com.sec.android.app.safetyassurance
**Removal**: Recommended :arrow_right: Unsafe

**Current description**
> Safety assurance is related to emergency features. It is especially used for SOS messages.
https://samsung.com/nz/support/mobile-devices/samsung-sos-smart-phone-emergency-message-guide

**Proposed description**
> Safety assurance is related to emergency features. It is especially used for SOS messages.
Due to it being used for emergency features, YOU SHOULD NEVER REMOVE THIS APP FROM YOUR PHONE.
https://samsung.com/nz/support/mobile-devices/samsung-sos-smart-phone-emergency-message-guide

**Comment by skunkmommy** [comment]
To be clear, it's not unsafe for the device if you remove this app: it's unsafe for the human to remove this app (again, it is tied to emergency features like SOS)

**Comment by AnonymousWP** [comment]
> To be clear, it's not unsafe for the device if you remove this app: it's unsafe for the human to remove this app (again, it is tied to emergency features like SOS)

My suggestion is to only change the description, because the `removal` status is merely for the safety of the device, not of a human-being.

**Comment by 0x192** [comment]
Thanks for your report. The packages has been moved to `Advanced` given the potential consequences of a mistaken removal if you rely on it.

> YOU SHOULD NEVER REMOVE THIS APP FROM YOUR PHONE.

Some people may want to remove this feature.
https://libreddit.spike.codes/r/samsunggalaxy/comments/tood77/is_there_a_way_to_disable_emergency_call_feature/
