### ISSUE TITLE
Removing com.lge.ime.solution.text casues the stock (com.lge.ime) keyboard to not work properly

### ISSUE THREAD

**Issue by ShellzJewelz** [0x192/Universal-Android-Debloater#427]
**LG G6**: \<LG-H870\>

**Packages documentation to update:**
```
com.lge.ime.solution.text
```
## Documentation chage
**List**: `Oem` (manufacturer)
**Removal**: `Recommended`.

### \<com.lge.ime.solution.text\>
**List**:  \<Recommended\> :arrow_right: \<Advanced\>
**Removal**: \<Recommended\> :arrow_right: \<Advanced\>

**Current description**
XT9
Text prediction and correction for the LG keyboard.
For your culture (if you're young): https://en.wikipedia.org/wiki/XT9

**Proposed description**
XT9
Text prediction and correction for the LG keyboard.
For your culture (if you're young): https://en.wikipedia.org/wiki/XT9
WARNING: On LG G6 (and maybe on other LG phones) removing this may cause the stock keyboard to stop inputing characters.

**Comment by ShellzJewelz** [comment]
The format of this update request was a bit confusing to me so I hope I filled it properly.

**Comment by 0x192** [comment]
Thanks for your report!
