### ISSUE TITLE
UPDATE com.samsung.android.forest, relevant for DEX users

### ISSUE THREAD

**Issue by giammi56** [0x192/Universal-Android-Debloater#430]
**Your phone**: SM-T720

**Packages documentation to update:**
```
com.samsung.android.forest
```
## Documentation chage
**List**: `Oem` (manufacturer).
**Removal**: `Recommended`.

**Proposed description**
WARNING FOR DEX USERS: uninstalling it makes the UI unstable, in particular the taskbar is not loaded and UI continue to crash.

**Comment by 0x192** [comment]
Thanks for your report!
