### ISSUE TITLE
Add com.miui.notes

### ISSUE THREAD

**Issue by h2559** [0x192/Universal-Android-Debloater#436]
Xiaomi POCO F4

Here is a direct link to the app which states the filename: com.miui.notes
https://www.apkmirror.com/apk/xiaomi-inc/miui-notes/

Here is a screenshot of the app from my phone:  
![N](https://user-images.githubusercontent.com/20052727/201471882-7aa9dc5c-746b-4220-b35d-b5eab35c0e62.jpg)

In the past I used your previous app (the written by someone else, that uses a Jar file) and it had the option to remove this app and it was safe to do so and I did and it had no problems for years. Please add it to the list so I can remove it again from my new Xiaomi phone. Thank you

Xiaomi | Notes

https://www.apkmirror.com/apk/xiaomi-inc/miui-notes/

**Comment by AnonymousWP** [comment]
It's already in the UAD, lol: https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L15636

**Comment by h2559** [comment]
> It's already in the UAD, lol: https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L15636

ok, before i made the topic i searched through the entire lists 3 times and did not find it. first, you need to move it to the Xiaomi section and label it properly with the "notes" title. second, which submenus do i search for so that I can find and uninstall the xiaomi notes? thank you.

<img width="1440" alt="Screen Shot 2022-11-12 at 5 54 11 AM" src="https://user-images.githubusercontent.com/20052727/201483970-6ad83747-bd3f-4e7f-a7da-1bc0b3441b6b.png">

**Comment by 0x192** [comment]
>  you need to move it to the Xiaomi section and label it properly with the "notes" title.

All apps developed by the manufacturer are in the [OEM](https://en.wikipedia.org/wiki/Original_equipment_manufacturer) list.

The exact package name for the Xiaomi Note app is `com.miui.notes`. You can find it with the search bar.

If you don't find it, it's maybe because the app is not enabled (in your screenshot you have the `Enabled` filter)

**Comment by h2559** [comment]
Ok, i did an exhaustive search 2 more times and i still do not see it.

This is what I see, it jumps from M to P, no N for notes. So can you tell me the exact steps to get com.miui.notes

<img width="1044" alt="Screen Shot 2022-11-12 at 11 46 20 AM" src="https://user-images.githubusercontent.com/20052727/201484984-c528b99d-cd22-4ed8-bbf8-47d2d2d69460.png">

**Comment by h2559** [comment]
here is one more, it skips N again

<img width="1048" alt="Screen Shot 2022-11-12 at 11 48 57 AM" src="https://user-images.githubusercontent.com/20052727/201485054-f4cc93bb-6c7c-4775-ad55-90d7346757e7.png">

**Comment by 0x192** [comment]
Mhm.... do you really have this app installed as a system app?

Can you run this on a terminal?

```bash
adb shell pm list packages -s | grep note
```

```bash
adb shell pm list packages | grep note
```

**Comment by h2559** [comment]
> Mhm.... do you really have this app installed as a system app?
> 
> Can you run this on a terminal?
> 
> ```shell
> adb shell pm list packages -s | grep note
> ```
> 
> ```shell
> adb shell pm list packages | grep note
> ```
<img width="592" alt="Screen Shot 2022-11-12 at 11 53 27 AM" src="https://user-images.githubusercontent.com/20052727/201485271-8a8835b8-0839-4253-8d81-b11890952adc.png">


Here is the result:

**Comment by 0x192** [comment]
Ok. The good news is that your note application is not a system app. This means you can fully uninstall it from the settings of your phone.

For now UAD only manages system apps. This is why you don't see your app. I will change this behavior in the future because it confuses new users.

Supporting user app is not trivial because, I have to make sure you can restore the app. Userland applications are fully removed from the phone when doing `adb pm uninstall` so UAD have to backup the apk before to be able to restore it.

**Comment by h2559** [comment]
Ohhhh, that is awesome. I gotta say, this is a new phone, but in my previous Xiaomi phone (which uses an older version of MIUI), notes was a system app, which means it had be be "uninstalled" via this USB cable method.
(for future reference in case you ever get a similar request, my old phone had the MIUI version 11.0.2, and my current phone has MIUI 13.0.5). 

I just deleted the app now, thanks!

**Comment by 0x192** [comment]
Yeah. It's always nice when manufacturers doesn't preinstall their apps as system apps!
