### ISSUE TITLE
It can't launch on M2

### ISSUE THREAD

**Issue by Suyama-Daichi** [0x192/Universal-Android-Debloater#443]
**Describe the bug**
I tried to launch UAD on Mac book Pro M2, but faced this error.
```
zsh: bad CPU type in executable: /Users/daichi/Downloads/uad_gui-noselfupdate-macos
```

**Expected behavior**
It launch correctly.

**You have a solution?**
Sorry, I haven't...

**UAD log**
It's not generated.

**Comment by 0x192** [comment]
Yeah... that's because this is a build for x64 CPU and MacBook Pro M1/M2 have an ARM CPU. See #334

**Comment by MikeSim1** [comment]
I added a comment to #334 with instructions for building this on M1 Macs, which should also work on M2.
