### ISSUE TITLE
no app installed for shared library files

### ISSUE THREAD

**Issue by EricMelo** [0x192/Universal-Android-Debloater#444]
OS: Debian 11

hello guys, uad for debian don't propperly, it says: 
`there is no app installed for shared library files`

and i do not have any application for open this
can u help?

**Comment by 0x192** [comment]
Mhm... I'll see why it does that. You doubled-click on the executable from a file manager right ?

A workaround would be to launch it from the terminal :

```bash
./uad_gui-linux

**Comment by EricMelo** [comment]
works again nice and well! thanks!
