### ISSUE TITLE
Few packages to add, and a suggestion

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#445]
**Your phone:** Poco x3 nfc,  MIUI 13.0.1,  

**Packages:**
cn.wps.xiaomi.abroad.lite
com.micredit.in
com.miui.android.fashiongallery

- [X] **I removed all those packages on my phone**

## Documentation of the packages
**cn.wps.xiaomi.abroad.lite**: Mi document viewer. Default document app for MIUI, it opens files like PDF. It is trash app though. There are better alternatives like MS Office. 

**com.micredit.in**: Mi credit app. It is some type of app to give loan to people from India and china I guess. No one uses it. 

**com.miui.android.fashion.gallery**: Mi wallpaper carousel https://play.google.com/store/apps/details?id=com.miui.android.fashiongallery&hl=en&gl=US
A lockscreen customization app. Displays a new photo every time you check your lockscreen. Haven't seen anyone using it.

------

**Removal**:  They are all safe to remove and don't break important features. 

**p.s.** My another suggestion is to move com.miui.cleaner to recommended list. This app is owned by cheetah mobile.  The Chinese company has already been caught in ad fraud and user data theft. Due to these issues, Play Store and App Store removed Clean Master in India. Hence, it is a spyware threat. Also, it doesn't break the phone or important features.

More info: https://www.gadgets360.com/apps/news/banned-security-app-clean-master-by-cheetah-mobile-collected-user-private-data-report-2189633

https://piunikaweb.com/2020/07/15/xiaomi-clean-master-app-by-cheetah-mobile-showing-up-on-your-phone-despite-ban-by-indian-govt-company-responds/

Can't do pull request bcs I dont know anything about coding etc. sorry for that

**Comment by AnonymousWP** [comment]
Thanks, I made a Pull Request. The `com.miui.cleaner` is absent. There's `com.miui.cleanmaster` and that one is already on the recommended list.
