### ISSUE TITLE
no devices/emulator found

### ISSUE THREAD

**Issue by Malaysiawow** [0x192/Universal-Android-Debloater#452]
i already connect to my pc and it not detect my phone

**Comment by kecskeszsoltistvan** [comment]
Similar problem here. To be more specific, my Lenovo tablet is not being noticed by the program.

**Comment by ominona01** [comment]
Ayuda, estoy en el mismo problema, será porque no tenemos Depuración USB inalambirca? Habrá otra solución?

**Comment by AnonymousWP** [comment]
Have you followed the steps correctly? https://github.com/0x192/universal-android-debloater#how-to-use-it. ADB needs to be in the correct folder, or add it to PATH.

**Comment by ParaplegicRacehorse** [comment]
![image](https://user-images.githubusercontent.com/7605896/205466819-b4e734b7-b970-4618-b0d9-b537e54fb714.png)

**Comment by ParaplegicRacehorse** [comment]
Samsung Galaxy A51

![Screenshot from 2022-12-03 14-42-38](https://user-images.githubusercontent.com/7605896/205466947-1fab1433-a7b9-4595-856a-47ffb5f7e156.png)

**Comment by Sandbox8888** [comment]
> Have you followed the steps correctly? https://github.com/0x192/universal-android-debloater#how-to-use-it. ADB needs to be in the correct folder, or add it to PATH.

Thanks. This solved it. I put universal android debloater executable in the same folder as the adb.exe. After that my device was found by universal android debloater.

**Comment by SpaceDevelopmentDC** [comment]
> Samsung Galaxy A51
> 
> ![Screenshot from 2022-12-03 14-42-38](https://user-images.githubusercontent.com/7605896/205466947-1fab1433-a7b9-4595-856a-47ffb5f7e156.png)

unlock the phone password

**Comment by AnonymousWP** [comment]
> > Samsung Galaxy A51
> > 
> > ![Screenshot from 2022-12-03 14-42-38](https://user-images.githubusercontent.com/7605896/205466947-1fab1433-a7b9-4595-856a-47ffb5f7e156.png)
> 
> unlock the phone password

He already said it has been solved.

**Comment by pjanardhan7u** [comment]
I am also getting the same problem for my vivo mobile

**Comment by ParaplegicRacehorse** [comment]
> > Samsung Galaxy A51
> > [[  Screenshot  ]]
> 
> unlock the phone password

Developer mode was enabled. Phone was unlocked. This was repeated multiple times with multiple different cables and even by wifi.

adb (and, therefore, debloater) can't find phone.

Weirdly, usb file sharing works just fine.

**Comment by NMQ1510** [comment]
![Debloater android](https://github.com/0x192/universal-android-debloater/assets/122730203/3c5594a1-f03e-4e88-bb1c-795dc1c29cad)
guys is there any step that I did wrong ?

**Comment by NMQ1510** [comment]
![Debloater android](https://github.com/0x192/universal-android-debloater/assets/122730203/dfc60957-9474-465b-9a23-0fd7c0881cd9)
samsung galaxy j2 prime 
Did I do wrong any steps ?

**Comment by ParaplegicRacehorse** [comment]
>  guys is there any step that I did wrong ?

Probably you are not doing anything wrong if you followed the instructions as published. Clearly `adb` can find the device but UAD can't do anything with it. This is clearly a bug in UAD; or, maybe, some OEM restriction specifically to prevent you from doing things to your own hardware that they disapprove of.

This bug exists for a multitude of individuals and devices.

Bug exists for some devices when the phone is:
* unlocked
* developer mode enabled
* USB-debug enabled
* detectable by android-debug-bridge

**Comment by NMQ1510** [comment]
How can i fix it


Vào 03:06 CN, 24 Th12 2023 Paraplegic Racehorse ***@***.***>
đã viết:

**Comment by ParaplegicRacehorse** [comment]
> How can i fix it

Either make the appropriate fix to the software yourself (can you program? I can't.) or wait for the dev to fix it.

**Comment by NMQ1510** [comment]
Ok, I'll check it out.

Vào 03:46 CN, 24 Th12 2023 Paraplegic Racehorse ***@***.***>
đã viết:

**Comment by aetherboundEsotericist** [comment]
> Samsung Galaxy A51
> 
> ![Screenshot from 2022-12-03 14-42-38](https://user-images.githubusercontent.com/7605896/205466947-1fab1433-a7b9-4595-856a-47ffb5f7e156.png)

This happened to me as well, phone was also unlocked. Disabling and re-enabling USB debug seems to work, so it's probably some weird authentication problem with the phone's USB debug mode. After that UAB could find the device.

First make sure your device is connected via USB. On your phone's dev options, revoke USB debug authorizations, then turn off USB debugging and turn it on again. Since it's connected via USB, It should ask you for permission to connect to your PC right away, allow it and it should work fine.

**Comment by jdahlblom** [comment]
> > Samsung Galaxy A51
> > ![Screenshot from 2022-12-03 14-42-38](https://user-images.githubusercontent.com/7605896/205466947-1fab1433-a7b9-4595-856a-47ffb5f7e156.png)
> 
> This happened to me as well, phone was also unlocked. Disabling and re-enabling USB debug seems to work, so it's probably some weird authentication problem with the phone's USB debug mode. After that UAB could find the device.
> 
> First make sure your device is connected via USB. On your phone's dev options, revoke USB debug authorizations, then turn off USB debugging and turn it on again. Since it's connected via USB, It should ask you for permission to connect to your PC right away, allow it and it should work fine.

This solved it for me.

**Comment by DustBytesBack** [comment]
I had the same problem. What worked for me was , i put the UAD in the same folder as adb 
![image_2024-09-05_152102182](https://github.com/user-attachments/assets/823055db-5653-47bc-b922-98b5627c3b76)

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/ygYJDf9YBn
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org
