### ISSUE TITLE
It does not work with Oppo Find X2 Pro

### ISSUE THREAD

**Issue by montajyan** [0x192/Universal-Android-Debloater#455]
I used this wonderfull tool for my Galaxy Note 8 and it recognized my phone without any problem and i could delete the apps what i did not want. But i tried it with Oppo Find X2 Pro and when i run this tool on the screen there is just a dynamic glitch. I could see the model number of the phone but i could not select it because dynamic glitch. I hope you can find a way to fix it. Thank you ver much for this awesome tool.

https://user-images.githubusercontent.com/119154016/204124843-9f4aea75-efe2-4e1f-b396-3c4017c21226.mov

![Screenshot 2022-11-27 082222](https://user-images.githubusercontent.com/119154016/204124847-d853de48-12ac-47d8-a759-654873f4c2cc.png)
![Screenshot 2022-11-27 082200](https://user-images.githubusercontent.com/119154016/204124848-eb33abcb-2a17-4a43-b652-084203516f79.png)

**Comment by AnonymousWP** [comment]
Which version are you using? If you're using [uad_gui-windows.exe](https://github.com/0x192/universal-android-debloater/releases/download/0.5.1/uad_gui-windows.exe), consider using [uad_gui-windows-opengl.exe](https://github.com/0x192/universal-android-debloater/releases/download/0.5.1/uad_gui-windows-opengl.exe) instead. It can solve the issue. In case it's vice-versa, apply the opposite thing.

**Comment by montajyan** [comment]
> Which version are you using? If you're using [uad_gui-windows.exe](https://github.com/0x192/universal-android-debloater/releases/download/0.5.1/uad_gui-windows.exe), consider using [uad_gui-windows-opengl.exe](https://github.com/0x192/universal-android-debloater/releases/download/0.5.1/uad_gui-windows-opengl.exe) instead. It can solve the issue. In case it's vice-versa, apply the opposite thing.

It worked, thanks :)
