### ISSUE TITLE
Universal android debloater

### ISSUE THREAD

**Issue by donimdaniels** [0x192/Universal-Android-Debloater#459]
**Your phone:** <phone model>

**Packages:**
```
com.this.is.a.bad.application
com.this.is.another.bad.application
...
```
- [ ] **I removed all those packages on my phone**
If not why. Leave the brackets blank and explain why.

## Document each package the best you can
**List**: `Google`|`Misc`|`Oem` (manufacturer)|`Aosp`|`Pending`|`Carrier` (isp).
**Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features), `Unsafe` (this can bootloop the phone or break extremely important features).

### \<package name\>
**List**: \<list\> 
**Removal**: \<recommendation list\>
> Description. Link to its Playstore page if it exists.

**Comment by AnonymousWP** [comment]
You're supposed to fill in the template, not just post the template alone.

**Comment by 0x192** [comment]
Huh? What are you trying to do?
