### ISSUE TITLE
Swipe up gesture doesn't work after removing OneUI launcher

### ISSUE THREAD

**Issue by CilekciGs** [0x192/Universal-Android-Debloater#483]
S20 FE 4G
**Describe the issue**
When you disable/remove the oneui launcher the swipe up(home/taskmanager) gesture will not work even if you have another launcher installed and set as default.
**You have a solution?**
Remove it from the advanced and add it to Expert

**Comment by btTeddy** [comment]
Correct.
Disabling ONE UI Launcher completely removes the functionality of swiping edges of the screen


Can we please have it moved to Unsafe as it brakes the basic functionality of the phone?

I believe this needs to be added:

```
  {
    "id": "com.sec.android.app.launcher",
    "list": "Oem",
    "description": "Samsung One UI Home launcher (homescreen) (https://play.google.com/store/apps/details?id=com.sec.android.app.launcher)\nIt is samsung Touchwiz default launcher\n WARNING: REMOVES SWIPE GESTURES.
BASIC FUNCTIONALITY DO NOT REMOVE THIS IF YOU DON'T USE ANOTHER LAUNCHER !\n",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Unsafe"
  },

```

**Comment by AnonymousWP** [comment]
By reading the `expert` removal, this indeed seems to be a better fit (usually, launchers are part of the `advanced` removal, as it even happens when another launcher is installed.

> Advanced -- Breaks obscure or minor parts of functionality, or apps that aren't easily enabled/installed through Settings/Google Play. This category is also used for apps that are useful (default keyboard/gallery/launcher/music app.) but that can easily be replaced by a better alternative.

> Expert -- Breaks widespread and/or important functionality, but nothing important to the basic operation of the operating system. Removing an Expert package should not bootloop the device (unless mentioned in the description) but we can't guarantee it 100%.

I opened a pull request and edited your description a bit. Let me know if this is okay.
