### ISSUE TITLE
Not working on a13 5g

### ISSUE THREAD

**Issue by Razor7100** [0x192/Universal-Android-Debloater#489]
Not working on samsung a13 5g

**Comment by Razor7100** [comment]
Please fix

**Comment by vdbhb59** [comment]
Same on Vivo Y35 V2205. Logs shows ADB not found, even though ADB is installed.
It works only when the application has been copied to the ADB folder and then run.

**Comment by AnonymousWP** [comment]
Have both of you followed [the instructions](https://github.com/0x192/universal-android-debloater#how-to-use-it)? And define "not working".

**Comment by Razor7100** [comment]
Nothing shows up when i press refresh and my phone is connected

**Comment by AnonymousWP** [comment]
> Nothing shows up when i press refresh and my phone is connected

That's why I asked: did you follow all the instructions I linked to? Include a log too.

**Comment by vdbhb59** [comment]
> Have both of you followed [the instructions](https://github.com/0x192/universal-android-debloater#how-to-use-it)? And define "not working".

Yes did that. As I said, nothing shows up unless copied over.

> > Nothing shows up when i press refresh and my phone is connected
> 
> That's why I asked: did you follow all the instructions I linked to? Include a log too.

There is no log generated honestly.

**Comment by AnonymousWP** [comment]
> > Have both of you followed [the instructions](https://github.com/0x192/universal-android-debloater#how-to-use-it)? And define "not working".
> 
> Yes did that. As I said, nothing shows up unless copied over.
> 
> > > Nothing shows up when i press refresh and my phone is connected
> > 
> > 
> > That's why I asked: did you follow all the instructions I linked to? Include a log too.
> 
> There is no log generated honestly.

This project is no longer maintained, see https://github.com/0x192/universal-android-debloater/issues/923
