### ISSUE TITLE
Multi-device support

### ISSUE THREAD

**Issue by amaanq** [0x192/Universal-Android-Debloater#49]
For future reference I hope - add multiple device support. I always have an emulator running in the background and tried to use this on my phone. Unfortunately this just results in a "adb.exe: more than one device/emulator" which can simply be fixed by listing devices with adb devices then running each command per device with "adb -s <devicename> <command>" so "adb shell pm list packages" becomes "adb -s emulator-5554 pm list packages" 

Thanks!

**Comment by 0x192** [comment]
>  I always have an emulator running in the background and tried to use this on my phone. 

I hadn't thought of that. I will add multi-device support in the next release.

**Comment by amaanq** [comment]
thanks! the app is amazing and super helpful to understand what all the random oem/carrier system apps did on my phone. i was always scared to remove them but not now and my phone lasts so long now! appreciate the work

**Comment by 0x192** [comment]
@amaanq

If you want to try out the new feature before the next release:

[Windows build](https://github.com/0x192/universal-android-debloater/suites/4137850662/artifacts/106036473) / [MacOS build](https://github.com/0x192/universal-android-debloater/suites/4137850662/artifacts/106036472) / [Linux build](https://github.com/0x192/universal-android-debloater/suites/4137850662/artifacts/106036471) (you need to be logged in to your Github account)

**Comment by amaanq** [comment]
thank you! let me check it out

**Comment by amaanq** [comment]
works perfectly when i have my emulator open with my phone plugged in, but my emulator doesn't show up in the device drop down menu, is that intended or a bug? if intended, why? I don't *need* to debloat my emulator but some ppl might want that feature (and I did use it to remove like 3 apps from my emulator before)

**Comment by 0x192** [comment]
> but my emulator doesn't show up in the device drop down menu, is that intended or a bug?

It's a bug. It works well with 2 devices but I couldn't test with an emulator. What's the output of:

```
adb devices
```
```
adb -s [id] shell "getprop ro.product.brand && getprop ro.product.model"
```

What happens if you only have your emulator? Does it show up?

EDIT: I think I know what's wrong. I'll upload a new build.

**Comment by 0x192** [comment]
New builds: [Windows build](https://github.com/0x192/universal-android-debloater/suites/4139901925/artifacts/106108286) / [MacOS build](https://github.com/0x192/universal-android-debloater/suites/4139901925/artifacts/106108285) / [Linux build](https://github.com/0x192/universal-android-debloater/suites/4139901925/artifacts/106108284) (you need to be logged in to your Github account)

**Comment by moneypython** [comment]
I also use multiple devices in my setup. Unfortunately this build is not rendering the drop down properly. I tried both Open gl and other executable. Windows 10.

![image](https://user-images.githubusercontent.com/4646325/143940574-95336787-9f22-4a7c-8ae0-1bcefc85b9e6.png)

**Comment by 0x192** [comment]
@moneypython 

I'm about to finally release `v0.4`! There has been a lot of changes since the last version you tried. This weird graphic bug probably comes from a dependency I use for the GUI. It should be fixed by now.

<s>Do you still have this problem with this [build](https://github.com/0x192/universal-android-debloater/files/7833910/uad_gui-windows.zip)?</s>

EDIT: `v0.4` [has been released](https://github.com/0x192/universal-android-debloater/releases)
