### ISSUE TITLE
Refreshing for packages will change the theme back to Lupin

### ISSUE THREAD

**Issue by rifqire** [0x192/Universal-Android-Debloater#50]
My steps:
1. Open UAD 0.3.0 (Windows)
2. Open settings and change Lupin theme to dark/light
3. Click the refresh package button
4. The app theme will change to Lupin

Closing the app and opening it again after changing theme will also change to Lupin

**Comment by 0x192** [comment]
Yeah I'm aware of this. Refresh button resets all settings to default (as a new phone could be plugged in). I initially did this because it simplifies the code but I agree the theme shouldn't be changed.
