### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by amaanq** [0x192/Universal-Android-Debloater#504]
**Describe the bug**
Fails to compile on (Arch) Linux 6.1.x

= note: clang-14: error: invalid linker name in argument '-fuse-ld=/usr/local/bin/mold'        

**Expected behavior**
It compiles

**You have a solution?**
Well, one fix is to link /usr/bin/mold to /usr/local/bin/mold, but I have no idea why it isn't checking for the linker in /usr/bin.
I suspect it comes from one of UAD's deps, but no idea which. I've never had this problem before in any Rust project.

**Comment by 0x192** [comment]
Huh. Weird. I also run Arch Linux.

I installed [`mold`](https://archlinux.org/packages/community/x86_64/mold/) from the Community repository and the binary was put in `/usr/bin/local`.

**Comment by amaanq** [comment]
Even weirder, I tried reinstalling mold but no dice, just a hard-coded ln -s has solved it so far

Ok, I just saw the local .cargo dir and noticed the rustflags you threw in, not a dep issue lol..either way is there a way to probe for a linker in multiple locations?

**Comment by 0x192** [comment]
Ok. I was wrong. Pacman doesn't install `mold` in `/usr/bin/local`. I remember the issue and I forgot to update the wiki.

Actually when mold is installed with the [`setup-mold`](https://github.com/rui314/setup-mold) Github Action, the binary is stored in `/usr/bin/local`. That why the `.cargo/config` file uses this path.

Looking back now, it would have been more logical to create the symbolic link during the Github CI and keep the `/usr/bin/` in the `.cargo/config`.

 > is there a way to probe for a linker in multiple locations?

I'll have a look. I'm not sure we can do that. I think I'll will just add the _ln -s_ in the CI workflow and change the `.cargo/config`

**Comment by amaanq** [comment]
I did look around a bit and it doesn't seem possible to be able to probe with a $(which mold) expansion or /usr{/local,} optional search either. So yeah running ln -s in the CI workflow would be great, thanks!

**Comment by 0x192** [comment]
Actually I've just used a relative path as `/usr/bin` and `/usr/local/bin` are already in the PATH anyway.

**Comment by amaanq** [comment]
nice, thanks!

**Comment by bitcoink188-cpu** [comment]
#1141 
#1092 
#1083 
#1141 
#993 
#1101 
#1100 
#781 
#130
