### ISSUE TITLE
System Manager

### ISSUE THREAD

**Issue by v1s7** [0x192/Universal-Android-Debloater#509]
**Your phone:** Huawei

**Packages:**
```
com.huawei.systemmanager
```

## Document each package the best you can
**List**: `Oem`
**Removal**: `Expert`

### com.huawei.systemmanager
> System Manager
Huawei's stock phone cleaner. Consumes a lot of battery power for useless "security" checks. Save to remove unless you need antivirus

**Comment by AnonymousWP** [comment]
Next time just create 1 issue for all packages instead of 1 issue per package. 😅

**Comment by v1s7** [comment]
> Next time just create 1 issue for all packages instead of 1 issue per package. 😅

Said on time, I was going to send 16 more packages separately...

**Comment by AnonymousWP** [comment]
You can keep this one open though, because when my PR gets merged, it'll close this issue.
