### ISSUE TITLE
com.huawei.parentcontrol can't be uninstalled/disabled

### ISSUE THREAD

**Issue by lawson85** [0x192/Universal-Android-Debloater#51]
It will not uninstall the package, the log is here: 

2021-10-14 12:59:57 INFO  [src\gui\mod.rs:80] ANDROID_SDK: 29 | PHONE: HONOR HRY-LX1
2021-10-14 12:59:58 WARN  [src\gui\views\list.rs:121] No custom selection imported: The system cannot find the file specified. (os error 2)
2021-10-14 13:00:04 ERROR [src\core\sync.rs:207] [Recommended] pm uninstall --user 0 com.huawei.parentcontrol -> Failure [DELETE_FAILED_INTERNAL_ERROR]

**Comment by 0x192** [comment]
You mean `com.huawei.parentcontrol`?

I can't do much about it. Huawei prevents to uninstall this package. You should be able to disable it though.

Can you to to **Tools > Parental control** and report back the user associated to the package:

```bash
adb shell ps -A | grep "com.huawei.parentcontrol"
```

If it doesn't show anything. This means that `com.huawei.parentcontrol` isn't actually running. Maybe try to launch some way.

**Comment by lawson85** [comment]
You mean com.huawei.parentcontrol? Yes I do.

adb shell ps -A | grep "com.huawei.parentcontrol" returns nothing

I regret enabling digital balance now, it was once disabled. I wonder if the ADB module updated and prevented this

**Comment by 0x192** [comment]
> You mean com.huawei.parentcontrol? 
> > Yes I do.

I didn't realize *digital wellbeing* was the name of the  `com.huawei.parentcontrol` package.

So disabling works?

**Comment by lawson85** [comment]
That was my mistake, it is called digital space. No it still will not uninstall. Also, pm disable throws the error 'not allowed to disable this package'

**Comment by 0x192** [comment]
Well. In that case we can't really do anything about this. Root is needed for uninstalling this specific package.

**Comment by Ethereal-Echoes** [comment]
I think you need to obtain some more advanced permissions, such as root
