### ISSUE TITLE
Samsung A52 5G not detected

### ISSUE THREAD

**Issue by jay5656** [0x192/Universal-Android-Debloater#519]
**Describe the bug**
My device does not show up despite adb showing it is detected.
![Screenshot 2023-01-20 220856](https://user-images.githubusercontent.com/71863420/213841189-908e3a69-ae8b-40e6-accc-3585c5b0d11e.png)

**UAD log**
[UAD_20230120.log](https://github.com/0x192/universal-android-debloater/files/10471400/UAD_20230120.log)

**Comment by AnonymousWP** [comment]
See https://github.com/0x192/universal-android-debloater/issues/517#issuecomment-1398407301.

**Comment by jay5656** [comment]
> See [#517 (comment)](https://github.com/0x192/universal-android-debloater/issues/517#issuecomment-1398407301).

But I've done those. Although I am confused where that guy found the "add android platform tools to path" as that was not in the "how to use" instructions?

**Comment by jay5656** [comment]
it works now, i had to add it to path my bad, i missed this step

**Comment by jay5656** [comment]
is UAD supposed to close everytime you click uninstall?

**Comment by AnonymousWP** [comment]
> is UAD supposed to close everytime you click uninstall?

https://github.com/0x192/universal-android-debloater/issues/377
