### ISSUE TITLE
Where I can find UAD? What root I need, where is it recorded?

### ISSUE THREAD

**Issue by AndrewUa2002** [0x192/Universal-Android-Debloater#538]

**Comment by AnonymousWP** [comment]
How do you expect any help with so little information? Tell us what you tried, explain your question in more detail and so forth. You don't need root, and what do you mean with "where is it recorded"? You just need to follow [the steps](https://github.com/0x192/universal-android-debloater#how-to-use-it) and you'll be able to use it.

**Comment by 0x192** [comment]
Seriously?

**Comment by AndrewUa2002** [comment]
I need UAD log
