### ISSUE TITLE
Error runing on Ubuntu 18.04

### ISSUE THREAD

**Issue by yeswap** [0x192/universal-android-debloater#55]
How to run uad on Linux? The README.md doesn't actually say. I tried making it executable and running like a shell script but got the following errors. ADB is installed and working.

~/Downloads$ ./uad_gui-linux 
2021-10-18 20:27:17 WARN  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.10.7/src/vulkan/instance.rs:514] create_instance: VkError(ERROR_INCOMPATIBLE_DRIVER)
2021-10-18 20:27:18 WARN  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.10.7/src/gles/egl.rs:400] 	EGL context: -robust access
2021-10-18 20:27:18 WARN  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.10.7/src/gles/egl.rs:413] unable to create GLES 3.x context: BadConfig

**Comment by 0x192** [comment]
The error say that [wgu](https://github.com/gfx-rs/wgpu) can't create a Vulkan instance. You need to make sure Vulkan is working on your computer. 

If you don't care (or your CPU/GPU is too old) you should just use [the OpenGL build of UAD](https://github.com/0x192/universal-android-debloater/releases/download/0.3/uad_gui-linux-opengl).

**Comment by yeswap** [comment]
Thanks for the reply. my PC is very old, CPU is Pentium T4400 with integrated graphics. I tried with the OpenGL build and got different errors.

~/Downloads$ ./uad_gui-linux-opengl 
thread 'main' panicked at '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/glow_glyph-0.4.0/src/pipeline.rs:287:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Looks like I have a missing dependency. Do you know which package provides the needed GLSL version?

Thanks

**Comment by 0x192** [comment]
This is an upstream issue. Very old hardware with only GLSL 1.20 is currently not supported by Iced (see[ #931](https://github.com/iced-rs/iced/issues/931))

Someone fixed the issue in their fork but it wasn't merged in Iced master branch. I'll see if @dvdsk can sync their fork with Iced master so that I can release a special build for you :)

**Comment by 0x192** [comment]
Does [this build](https://github.com/0x192/universal-android-debloater/files/7389066/uad_gui-linux-legacy.zip) work for you? 

If not, try [this one](https://github.com/0x192/universal-android-debloater/files/7389108/uad_gui-linux-legacy2.zip).

Don't forget to tell me what build worked for you.

**Comment by yeswap** [comment]
Thanks, both versions fail to run with the errors:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./uad_gui-linux-legacy)

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./uad_gui-linux-legacy2)

**Comment by 0x192** [comment]
Oh. Okay. Ubuntu 18.04 is stucked to `v2.27` glibc.

I need to compile UAD from a Ubuntu 18.04 docker image. I'll do it tomorrow.

Do you stay on Ubuntu 18.04 because it is still supported and you don't have any reason to upgrade? I advice you to upgrade to Ubuntu 22.04 LTS when it will be released. There has been a lot of performance improvement since 2018.

**Comment by yeswap** [comment]
> Do you stay on Ubuntu 18.04 because it is still supported and you don't have any reason to upgrade? I advice you to upgrade to Ubuntu 22.04 LTS when it will be released. There has been a lot of performance improvement since 2018.

Thanks, I stay on 18.04 because it's very stable on this hardware and everything I need works. I tried 20.04 but WiFi was broken. I spent a couple hours trying to fix it, gave up and went back to 18.04. I will try 22.04 next year.

**Comment by 0x192** [comment]
> I spent a couple hours trying to fix it, gave up and went back to 18.04. I will try 22.04 next year.

That's understandable.

----------
Hopefully it works now : [uad_gui-linux-legacy](https://github.com/0x192/universal-android-debloater/files/7400015/uad_gui-linux-legacy.zip)

**Comment by yeswap** [comment]
Success! Your latest version works on my ancient hardware and old distro. Thank you.

**Comment by 0x192** [comment]
Good news! Iced now [officially supports old hardware with only GLSL 1.20](https://github.com/iced-rs/iced/pull/1160)! This means I don't have to maintain a special build for those hardware anymore!
