### ISSUE TITLE
Android package

### ISSUE THREAD

**Issue by uspyou** [0x192/universal-android-debloater#58]

**Comment by 0x192** [comment]
?

If you are asking about an Android app. There is no plan for this.

**Comment by lawson85** [comment]
There is an app called Android system, which has the package name of 'android' maybe that is what is being referred to. DO NOT REMOVE IT YOU WILL BRICK YOUR DEVICE.

Otherwise if you want to debloat your device on your device you need Android 11+ and LADB.

**Comment by 0x192** [comment]
> There is an app called Android system, which has the package name of 'android' maybe that is what is being referred to.

You are probably right. I should probably add this package to the list with the `unsafe` flag. 
<br>
> Otherwise if you want to debloat your device on your device you need Android 11+ and LADB.

You can also access adb commands for your phone from [Termux](https://termux.com/) which package an ADB client ([see here](https://libreddit.kavin.rocks/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux/))
