### ISSUE TITLE
Samsung S23 Ultra

### ISSUE THREAD

**Issue by jcid2023** [0x192/Universal-Android-Debloater#602]
Connects fine but doesn't really show any apps to remove.

**Comment by BillOTei** [comment]
same here,
![image](https://github.com/0x192/universal-android-debloater/assets/2312874/305c05d9-825b-47b9-a78d-ce63203fb6ff)
![image](https://github.com/0x192/universal-android-debloater/assets/2312874/6d4ce76e-8305-44e7-b841-c7194d55835b)
any tips?

**Comment by nailyk-fr** [comment]
Working fine here : 

![image](https://github.com/0x192/universal-android-debloater/assets/16372405/4eacae2d-ca53-4575-aba7-ed26092861e5)

However, each setting `Recommended`, `Advanced` ... bootloop the device. 

Edit: Rooted s23ultra build `UP1A.231005.007.S918BXXS3BWK5`

**Comment by nailyk-fr** [comment]
This is the list I currently came-up with : 
[uad_exported_selection.txt](https://github.com/0x192/universal-android-debloater/files/13660228/uad_exported_selection.txt)


I believe it can be marked as 'safe'. 

Removing this : 
```
2023-12-11 14:31:35 INFO  [src/core/utils.rs:222] [Recommended] pm uninstall --user 0 com.sec.android.app.quicktool -> Success
2023-12-11 14:31:37 INFO  [src/core/utils.rs:222] [Advanced] pm uninstall --user 0 com.samsung.android.mdx.quickboard -> Success
```

made the device to end up in a boot-loop.
