### ISSUE TITLE
carrier IQ rootkit

### ISSUE THREAD

**Issue by dellwit** [0x192/Universal-Android-Debloater#620]
**Motorola**: \<G52\>

**Describe the issue**
The program found my phone Carrier IQ rootkit. Is this real or is it a bug in the program description? I am attaching a picture. Neither Bittdefender nor Voodoo Cariier IQ scanners found anything.

**You have a solution?**
What to do to fix the issue.

**UAD log**
Upload the logfile generated by UAD. You can hardly be helped without.
![Schránka 01](https://user-images.githubusercontent.com/126297230/221319946-aab5dbe2-cd03-4b3d-a28f-5946492b9260.jpg)

**Comment by lawson85** [comment]
It's installed yes but all you had to do was read the article linked

**Comment by dellwit** [comment]
Thank you for the reply, I have read the article, waiting for me to root my phone and remove it, a lot of work. I thought nowadays, operators don't put this rootkit in phones anymore?

**Comment by AnonymousWP** [comment]
Scan the file/APK with VirusTotal and see the outcome. Disabling should help too; no background activity and the process won't start.

**Comment by dellwit** [comment]
VirusTotal is clean 0/76, com.att.iqi - clean. The app is turned off on my phone, I wanted to turn it on using the uad program to uninstall it, but that doesn't work. Does that mean it's not a rootkit?

**Comment by dellwit** [comment]
app is name "Mobile Network Diagnostic"

**Comment by dellwit** [comment]
I rooted the phone and uninstalled the app with Uninstall System Apps, you can lock the thread

**Comment by AnonymousWP** [comment]
> I rooted the phone and uninstalled the app with Uninstall System Apps, you can lock the thread

You can close the issue yourself at the bottom of this page.
