### ISSUE TITLE
Samsung Galaxy Flip 4 - Adding eSIM not working after debloat

### ISSUE THREAD

**Issue by taddvambhu** [0x192/Universal-Android-Debloater#621]
Samsung Galaxy Z Flip 4

After debloating my phone with standard recommended package list, I was not able to add an eSIM. The whole process of adding the eSIM just gets stuck.
After restoring all uninstalled packages the eSIM can be added successfully.

Anybody has an idea which package/es could cause this issue?

Thanks for the great work!

**Comment by warlock5822** [comment]
Mine wasn't working even before the debloat :L
Sorry not very helpful.

**Comment by taddvambhu** [comment]
In that case, I am slightly better off than you ;-)

**Comment by MadnessASAP** [comment]
Having the same symptoms on a Samsung Galaxy S21 Utra (SM-G998W). Airlao eSIM worked after restoring all apps. Here's the list of apps that were disabled when it wasn't working.

[uad_exported_selection.txt](https://github.com/0x192/universal-android-debloater/files/10913290/uad_exported_selection.txt)

I haven't really searched it and I unfortunately dont have the time to binary search it for the culprit. But a diff between that list and what you had disabled may narrow down the problem.

**Comment by taddvambhu** [comment]
Hi, I have made an intersection of what was disabled on your phone and what was disabled on mine. That are the following packages, not really narrow enough though ;-) Still a rough hundered packages...

android.autoinstalls.config.samsung
com.android.bluetoothmidiservice
com.android.chrome
com.android.dreams.phototable
com.android.egg
com.android.providers.partnerbookmarks
com.android.traceur
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.google.android.apps.messaging
com.google.android.apps.tachyon
com.google.android.gm
com.hiya.star
com.knox.vpn.proxyhandler
com.monotype.android.font.samsungone
com.samsung.android.aircommandmanager
com.samsung.android.app.camera.sticker.facearavatar.preload
com.samsung.android.app.clipboardedge
com.samsung.android.app.cocktailbarservice
com.samsung.android.app.omcagent
com.samsung.android.app.reminder
com.samsung.android.app.routines
com.samsung.android.app.settings.bixby
com.samsung.android.app.spage
com.samsung.android.app.taskedge
com.samsung.android.app.watchmanagerstub
com.samsung.android.ardrawing
com.samsung.android.aremoji
com.samsung.android.aremojieditor
com.samsung.android.arzone
com.samsung.android.authfw
com.samsung.android.bbc.bbcagent
com.samsung.android.beaconmanager
com.samsung.android.bixby.agent
com.samsung.android.bixby.wakeup
com.samsung.android.bixbyvision.framework
com.samsung.android.da.daagent
com.samsung.android.dqagent
com.samsung.android.easysetup
com.samsung.android.fmm
com.samsung.android.forest
com.samsung.android.game.gamehome
com.samsung.android.game.gametools
com.samsung.android.ipsgeofence
com.samsung.android.kidsinstaller
com.samsung.android.knox.analytics.uploader
com.samsung.android.knox.attestation
com.samsung.android.knox.containercore
com.samsung.android.knox.pushmanager
com.samsung.android.mateagent
com.samsung.android.mdm
com.samsung.android.mdx
com.samsung.android.mdx.kit
com.samsung.android.mobileservice
com.samsung.android.net.wifi.wifiguider
com.samsung.android.networkdiagnostic
com.samsung.android.rubin.app
com.samsung.android.samsungpass
com.samsung.android.samsungpassautofill
com.samsung.android.samsungpositioning
com.samsung.android.scloud
com.samsung.android.sdk.handwriting
com.samsung.android.service.peoplestripe
com.samsung.android.shortcutbackupservice
com.samsung.android.smartcallprovider
com.samsung.android.smartswitchassistant
com.samsung.android.spayfw
com.samsung.android.stickercenter
com.samsung.android.svcagent
com.samsung.android.visionintelligence
com.samsung.faceservice
com.samsung.ipservice
com.samsung.klmsagent
com.samsung.safetyinformation
com.samsung.storyservice
com.sec.android.app.applinker
com.sec.android.app.billing
com.sec.android.app.chromecustomizations
com.sec.android.app.DataCreate
com.sec.android.app.factorykeystring
com.sec.android.app.hwmoduletest
com.sec.android.app.parser
com.sec.android.app.samsungapps
com.sec.android.app.SecSetupWizard
com.sec.android.app.servicemodeapp
com.sec.android.app.setupwizardlegalprovider
com.sec.android.daemonapp
com.sec.android.diagmonagent
com.sec.android.easyMover.Agent
com.sec.android.easyonehand
com.sec.android.mimage.avatarstickers
com.sec.app.RilErrorNotifier
com.sec.enterprise.knox.cloudmdm.smdms
com.sec.enterprise.mdm.services.simpin
com.sec.epdgtestapp
com.sec.factory.camera
com.sec.imslogger
com.sec.location.nsflp2
com.sec.modem.settings
com.sec.phone
com.sec.spp.push
com.wsomacp

**Comment by rscm** [comment]
did you found the package? I'm reading about them, one by one. If I find it I'll update the post.

**Comment by MadnessASAP** [comment]
I didn't narrow it down to one package but I believe I narrowed it down further. I'll see if I still have that list around later.

**Comment by rscm** [comment]
probably is knox the one needed

I disabled these and left the rest alone (after reading each one of them) and still have the capability to add an eSIM

[I use Google stuff/apps]

```
android.autoinstalls.config.samsung
com.android.bluetoothmidiservice
com.android.chrome
com.android.dreams.basic
com.android.dreams.phototable
com.android.egg
com.android.providers.partnerbookmarks
com.android.traceur
com.diotek.sec.lookup.dictionary
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.google.android.onetimeinitializer
com.google.android.printservice.recommendation
com.google.android.youtube
com.google.audio.hearing.visualization.accessibility.scribe
com.hiya.star
com.microsoft.appmanager
com.microsoft.skydrive
com.samsung.android.aircommandmanager
com.samsung.android.app.camera.sticker.facearavatar.preload
com.samsung.android.app.clipboardedge
com.samsung.android.app.cocktailbarservice
com.samsung.android.app.contacts
com.samsung.android.app.reminder
com.samsung.android.app.routines
com.samsung.android.app.settings.bixby
com.samsung.android.app.taskedge
com.samsung.android.app.watchmanagerstub
com.samsung.android.ardrawing
com.samsung.android.aremoji
com.samsung.android.aremojieditor
com.samsung.android.beaconmanager
com.samsung.android.bixby.agent
com.samsung.android.bixby.wakeup
com.samsung.android.bixbyvision.framework
com.samsung.android.dialer
com.samsung.android.dynamiclock
com.samsung.android.easysetup
com.samsung.android.fast
com.samsung.android.fmm
com.samsung.android.game.gamehome
com.samsung.android.game.gametools
com.samsung.android.kidsinstaller
com.samsung.android.mdx
com.samsung.android.messaging
com.samsung.android.rubin.app
com.samsung.android.samsungpass
com.samsung.android.samsungpassautofill
com.samsung.android.scloud
com.samsung.android.sdk.handwriting
com.samsung.android.service.peoplestripe
com.samsung.android.shortcutbackupservice
com.samsung.android.smartswitchassistant
com.samsung.android.stickercenter
com.samsung.android.visionintelligence
com.samsung.crane
com.samsung.faceservice
com.samsung.rcs
com.samsung.safetyinformation
com.samsung.storyservice
com.sec.android.app.chromecustomizations
com.sec.android.app.magnifier
com.sec.android.app.quicktool
com.sec.android.diagmonagent
com.sec.android.easyMover.Agent
com.sec.android.easyonehand
com.sec.android.mimage.avatarstickers
com.sec.android.widgetapp.easymodecontactswidget
com.sec.android.widgetapp.webmanual
com.sec.app.RilErrorNotifier
com.sec.imslogger
com.sec.modem.settings
com.sem.factoryapp
com.swiftkey.swiftkeyconfigurator
```

**Comment by MadnessASAP** [comment]
Well I can't find my further paired down list, but here's the intersection of our 3 lists. 

```
android.autoinstalls.config.samsung
com.android.bluetoothmidiservice
com.android.chrome
com.android.dreams.phototable
com.android.egg
com.android.providers.partnerbookmarks
com.android.traceur
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.hiya.star
com.samsung.android.aircommandmanager
com.samsung.android.app.camera.sticker.facearavatar.preload
com.samsung.android.app.clipboardedge
com.samsung.android.app.cocktailbarservice
com.samsung.android.app.reminder
com.samsung.android.app.routines
com.samsung.android.app.settings.bixby
com.samsung.android.app.taskedge
com.samsung.android.app.watchmanagerstub
com.samsung.android.ardrawing
com.samsung.android.aremoji
com.samsung.android.aremojieditor
com.samsung.android.beaconmanager
com.samsung.android.bixby.agent
com.samsung.android.bixbyvision.framework
com.samsung.android.bixby.wakeup
com.samsung.android.easysetup
com.samsung.android.fmm
com.samsung.android.game.gamehome
com.samsung.android.game.gametools
com.samsung.android.kidsinstaller
com.samsung.android.mdx
com.samsung.android.rubin.app
com.samsung.android.samsungpass
com.samsung.android.samsungpassautofill
com.samsung.android.scloud
com.samsung.android.sdk.handwriting
com.samsung.android.service.peoplestripe
com.samsung.android.shortcutbackupservice
com.samsung.android.smartswitchassistant
com.samsung.android.stickercenter
com.samsung.android.visionintelligence
com.samsung.faceservice
com.samsung.safetyinformation
com.samsung.storyservice
com.sec.android.app.chromecustomizations
com.sec.android.diagmonagent
com.sec.android.easyMover.Agent
com.sec.android.easyonehand
com.sec.android.mimage.avatarstickers
com.sec.app.RilErrorNotifier
com.sec.imslogger
com.sec.modem.settings
```

**Comment by cwaqrgen** [comment]
I found the culprit. "com.sec.phone".  I have not tried adding an eSIM as yet , but the service provider menu comes up allowing you to continue the activation process. Let me know if this solved the issue. I am on SG s21 Ultra (SM-G998U1) btw.

Com.sec.phone is a component of the Android operating system that handles telephone calls. It is responsible for managing the phone's hardware, maintaining the phone's software, and connecting the phone to the cellular network.

**Comment by taddvambhu** [comment]
THX for all your replies, but I gave the phone away... But it might help others sure!

**Comment by GenTEKS** [comment]
> I found the culprit. "com.sec.phone". I have not tried adding an eSIM as yet , but the service provider menu comes up allowing you to continue the activation process. Let me know if this solved the issue. I am on SG s21 Ultra (SM-G998U1) btw.
> 
> Com.sec.phone is a component of the Android operating system that handles telephone calls. It is responsible for managing the phone's hardware, maintaining the phone's software, and connecting the phone to the cellular network.

I found **com.sec.android.app.SecSetupWizard** also had to be enabled for adding ESIMs support to work.
