### ISSUE TITLE
com.miui.core

### ISSUE THREAD

**Issue by CYNAR2k** [0x192/Universal-Android-Debloater#632]
**Your phone**: Xiaomi Mi Note 10 Lite (toco) MIUI 13 EEA Stable Version 13.0.6
MIUI Optimizations ON

**Packages documentation to update:**
```
com.miui.core
```

### com.miui.core

Just wanted to give feedback that i was able to disable it with no problems with the adb commands. No bootloops or any major issue found so far. I also UNINSTALLED via the GUI debloater and i had no problems too. 
I had some errors when trying to disable it with your commands, i had to change to adb shell pm disable-user --user 0 com.miui.core
and "adb shell pm clear com.miui.core" didn't work.

**Comment by CYNAR2k** [comment]
I need to add that uninstalling "com.miui.core" will crash settings if you type anything on the search bar!!!! @AnonymousWP

**Comment by AnonymousWP** [comment]
Thanks, check my new commit. Good enough?

**Comment by CYNAR2k** [comment]
> Thanks, check my new commit. Good enough?

I think so :)

**Comment by AnonymousWP** [comment]
@CYNAR2k You don't need to close it. Once my pull request gets merged, it'll automatically close this issue, so please re-open it (see at the bottom of this page).
