### ISSUE TITLE
Motorola One 5G Ace isn't found by UAD, says ADB isn't found

### ISSUE THREAD

**Issue by Kxsumi** [0x192/Universal-Android-Debloater#634]
**Describe the bug**
Using the program, my phone isn't found. I have checked inside of Recovery and Fastboot. My phone is findable by ADB. I've also noticed the log file says it cannot find ADB, but I, by going to c:\platform-tools in my cmd prompt, can find it and my device.
![image](https://user-images.githubusercontent.com/96434998/222080744-7b560b30-472c-4723-880f-87b03e0c3ace.png)

**Expected behavior**
The program can find ADB and use it to connect to my device.

**You have a solution?**
None as of now.

**UAD log**
Upload the logfile generated by UAD.
[UAD_20230301.log](https://github.com/0x192/universal-android-debloater/files/10858499/UAD_20230301.log)

**Comment by lawson85** [comment]
Does it work if you follow these steps? https://github.com/0x192/universal-android-debloater/issues/442

**Comment by Kxsumi** [comment]
> Does it work if you follow these steps? #442

Negative, still says ADB cannot be found. This includes putting it in my own platform-tolls folder and the Minimal

**Comment by Kxsumi** [comment]
Update it seems a quick reinstall of all of my ADB tools and redoing the PATH fixed it. Not sure what the issue was.
