### ISSUE TITLE
Clicking Accessability crashes settings app if Samsung Keyboard (.honeyboard) is removed

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#64]
If com.samsung.android.honeyboard package is removed clicking on Accessibility settings entry will crash the settings app and wont work.

Samsung A52s 5G, One UI 3.1, Android 11. June 1 Google Play Sys. Update.

**Comment by 0x192** [comment]
Arg! This package wasn't meant to be in the recommended list.

I hope you had read the description correctly and had installed another keyboard with direct boot support before removing this package. 

I'll update the description and move the package into the Expert list. Thanks for letting me know! :+1:

**Comment by ghost** [comment]
@0x192 Yeah it's a new phone so I could start over multiple times. Accessibility functions were the only thing that broke to me up to now.

Also the split screen function does not work for me currently but I'm too lazy to check by categories to narrow down and figure out which package it is.

Does removing user dictionary kill the spelling correction list function? It did not work for me, I tried making it work with openboard and after reinstalling both user dictionary, Samsung .honeyboard and started screwing around in the keyboard settings suddenly it started working. I could remove the Samsung keyboard afterwards. I suppose the userdictionary package was the culprit.

Also correct me if I'm wrong but there is no "deselect all" function in the current version. That would be useful for someone with an exported list template so we can more easily bulk remove/restore packages without needing to place the export file somewhere else or rename it. I could create a separate issue if you'd like.

If you'd like me to help out just ask me but I don't really know anything about package reverse engineering. I've noticed there are a lot of pending packages tho.
