### ISSUE TITLE
App does not respond while disabling apps

### ISSUE THREAD

**Issue by Booteille** [0x192/Universal-Android-Debloater#65]
Hi.

On GNU/Linux Pop_OS! 20.04, the app stopped responding when I clicked to disable apps. I've just wait until it respond again and everything worked but it would be nice that the app does not freeze when debloating.

Thanks.

**Comment by 0x192** [comment]
Hi @Booteille,

Did you select a lot of apps and then click on `disable selection`? Did it freeze for a long time?

At the moment, for the sake of simplicity, ADB actions don't run in parallel to the UI meaning the UI needs to wait they end to be responsive again. 

I haven't investigated much yet, but I plan to either use asynchronous code or completely move the ADB actions to another thread.

**Comment by Booteille** [comment]
Yeah, exactly.

I think any it makes sense to move ADB to another thread!
