### ISSUE TITLE
Samsung Theme Center is also "Galaxy Themes Service"

### ISSUE THREAD

**Issue by Rudxain** [0x192/Universal-Android-Debloater#651]
**Your phone**: SM-A315G

**Packages documentation to update:**
```
com.samsung.android.themecenter
```
### com.samsung.android.themecenter

**Current description**
> Samsung theme center
> Runs at startup and enable you to download theme from samsung
> Safe to remove.

**Proposed description**
> Samsung theme center (AKA Galaxy Themes Service)
> Runs at startup and allows you to apply themes from com.samsung.android.themestore
> Safe to remove.

**Comment by MenarikanCerita** [comment]
i just tried to disable this, it works but still leaves some traces, such as the app icon. the icon can still be clicked, but when it opens it's just a loading page with no end.

**Comment by Rudxain** [comment]
@MenarikanCerita
> i just tried to disable this, it works but still leaves some traces

I think you should mention that at #341

**Comment by MenarikanCerita** [comment]
> @MenarikanCerita
> 
> > i just tried to disable this, it works but still leaves some traces
> 
> I think you should mention that at #341

My bad, mate. I tried it again, and apparently there is one another app that need to be uninstalled (i forget what is it, but it has "themes" word in it's name), and then the themes app is no more. Thanks everyone! :D

**Comment by Rudxain** [comment]
@MenarikanCerita 
> My bad, mate.

No problem!

> I tried it again, and apparently there is one another app that need to be uninstalled (i forget what is it, but it has "themes" word in it's name), and then the themes app is no more.

Wait, what?! How exactly did you do it? What's your device model?

**Comment by MenarikanCerita** [comment]
> @MenarikanCerita
> 
> > My bad, mate.
> 
> No problem!
> 
> > I tried it again, and apparently there is one another app that need to be uninstalled (i forget what is it, but it has "themes" word in it's name), and then the themes app is no more.
> 
> Wait, what?! How exactly did you do it? What's your device model?

hmmm, i just type "themes" in the search bar with the setting i set as "all", both for type and status, then i found there are two apps with "themes" word in their name, so i disabled those, then voila, the theme is gone now. 
here, i have some pics to proof it, but so sorry i just AFK, can't open my laptop. i'll updated as soon as possible.

ah, and my device is samsung M32. device that has no developer in forum. T_T

![Screenshot_20230323_183709_One UI Home](https://user-images.githubusercontent.com/128225835/227218947-78d57b94-d301-469b-af06-6392b006dff6.jpg)
![Screenshot_20230323_183729_Settings](https://user-images.githubusercontent.com/128225835/227218964-b28d83a5-76b6-40ae-9e28-7a98ce7dc283.jpg)

**Comment by Rudxain** [comment]
> there are two apps with "themes" word in their name

I only disabled the theme store, and the "themes" buttons disappeared. I want to disable "theme center", but the system doesn't let me do it. I'm conformed with only disabling 1, but I wish it was both.

> my device is samsung M32. device that has no developer in forum. T_T

What do you mean?

**Comment by MenarikanCerita** [comment]
> I only disabled the theme store, and the "themes" buttons disappeared. I want to disable "theme center", but the system doesn't let me do it. I'm conformed with only disabling 1, but I wish it was both.

ah, yes. i disabled both "theme center" and "theme store". what OS you on now? i disabled those apps while i'm on One UI 5 (android 13)

> What do you mean?

there is no developer for M32 in XDA, no one doing mod on it. So i'm  very glad that there is someone who developed such tool for every devices, so i can optimized my devices by my own eventhough i'm not tech geek my self. sorry if OOT.
