### ISSUE TITLE
Samsung M12 Built-In Camera App vanished

### ISSUE THREAD

**Issue by DartPower** [0x192/Universal-Android-Debloater#67]
Samsung M12 Built-In Camera App deinstalled after debloating.
How to return it? :smile:

**Comment by 0x192** [comment]
Samsung Camera `com.sec.android.app.camera` isn't  in the `Recommended` list. This means you used the `Advanded` list without even looking at the packages that will be removed... Why doing this? :skull:

Restoring a application is supposed to be easy but I'm not a UX designer so there is probably room for improvement. What do you find confusing when wanting to restore an app?

One way to to do it to filter by `Uninstalled` packages and with the `Oem` list to only display Samsung packages. You can also search `com.sec.android.app.camera` in the search bar. You will then be able to restore the package the same way you uninstalled it.

**Comment by DartPower** [comment]
![image](https://user-images.githubusercontent.com/2005369/142755041-6a04085e-87af-4917-bef7-5fee6feeb833.png)

**Comment by 0x192** [comment]
Oh! My bad. You are right. `com.sec.android.app.camera` was in the `Recommended` list in the `v0.3` build. I moved it to `Advanced` but I have not yet released a new build.

**Comment by wefalltomorrow** [comment]
> Oh! My bad. You are right. `[com.sec.android.app.camera](http://com.sec.android.app.camera)` was in the `Recommended` list in the `v0.3` build. I moved it to `Advanced` but I have not yet released a new build.

Is there a rough estimate on when the next build will be released?

**Comment by 0x192** [comment]
> Is there a rough estimate on when the next build will be released?

Things have not progressed as quickly as I would have liked, nor do I have the time I'd like to spend on this project these days.

I really want to release something before the new year. I can't promise anything because I have a lot of work and... Christmas is Christmas y'know... :relaxed:

There is too much important changes between the development version and the last release. In the future I will make sure to do smaller releases so I can publish them more regularly.

**Comment by anjannair** [comment]
![image](https://user-images.githubusercontent.com/22571613/148216052-65289253-6fe8-4253-aff8-6a1880358cd4.png)


To add to this issue this package also needs to be removed from the recommended list as the Samsung Camera stops functioning.
