### ISSUE TITLE
Update description of com.huawei.android.thememanager

### ISSUE THREAD

**Issue by butyoutried** [0x192/Universal-Android-Debloater#672]
**Your phone**: HONOR 8S KSA-LX9

**Packages documentation to update:**
```
com.huawei.android.thememanager
```

**Current description**
> Themes (https://play.google.com/store/apps/details?id=com.huawei.android.thememanager)
Lets you download and use Huawei themes.
Setting Wallpapers directly will no longer work, but the Wallpaper entry in the Settings app will still let you choose wallpapers.

**Proposed description**
> Themes (https://play.google.com/store/apps/details?id=com.huawei.android.thememanager)
Lets you download and use Huawei themes.
Setting Wallpapers directly will no longer work, but the Wallpaper entry in the Settings app will still let you choose wallpapers.
Without this package you may no longer be able to change a notification sound.

**Comment by amaanq** [comment]
You can submit a PR to do this yourself ;)
