### ISSUE TITLE
Sharing APKs

### ISSUE THREAD

**Issue by v1s7** [0x192/Universal-Android-Debloater#683]
**Your phone**: realme 8

**Packages documentation to update:**
```
com.heytap.usercenter
com.oplus.stdid
com.mediatek.mdmconfig
```

### com.heytap.usercenter
> [https://www.mediafire.com/file/j5qa46vy4my99bb/com.heytap.usercenter_EXP_8.24.16.apk/file]()

### com.oplus.stdid
>
[https://www.apkmirror.com/apk/oneplus-ltd/stdid/stdid-2-1-1-release/stdid-2-1-1-android-apk-download/]()
[https://www.mediafire.com/file/elc1n9s2u2e7bjz/com.oplus.stdid_1.1.0.apk/file]()

### com.mediatek.mdmconfig
> [https://www.mediafire.com/file/psqim939jr1pkny/MDMConfig_MDMConfig.apk/file]()

i extracted them from my android 12 phone to apks, so I don't know if it'll run on any other device

**Comment by AnonymousWP** [comment]
We already have all three packages, search in https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json. What do you want us to do with those APKs?

**Comment by Rafee-M** [comment]
They all say 

> APK NEEDED

**Comment by AnonymousWP** [comment]
Yes so that the fields can be determined and so that the APK can be analysed.

**Comment by Rafee-M** [comment]
Meaning the apks of those packages are needed to be analyzed with pithus?

**Comment by AnonymousWP** [comment]
Not necessarily Pithus, but maybe it helps to determine the description and removal. What I mean is that the APKs need to be analysed and/or removed in order to change the description. That's why the APK was/is needed.
