### ISSUE TITLE
Option/list to delete all gaps

### ISSUE THREAD

**Issue by Jipok** [0x192/Universal-Android-Debloater#687]
A good application and now it has become much easier to clean the phone. However, I'm surprised that there is no list of services from Google. And when I went through the lists, deleting everything related to Google services, I missed some packages. For example `com.android.vending` which is the play store, which is very non-intuitive and hard to remember, and the word google is also missing.
I understand that on some phones this may remove the main applications for sms and calls, but it's enough to add a warning about this and, for example, suggest installing alternatives in the form of SimpleMobileTools.
In my experience, clearing gaps has never broken a phone.

**Comment by AnonymousWP** [comment]
That's where the `aosp` list is for. How would a `gapps` list make much difference with that? Sure, it's not exactly the same, but I think it's not worth it for another extra list. Most of the gapps are in the `aosp` list, no?

**Comment by Jipok** [comment]
> That's where the aosp list is for.

Oh. It's so awkward. I don't remember being so screwed up in recent years. I somehow missed google(`com.android.vending` here) in the lists. Was it in older versions?

**Comment by AnonymousWP** [comment]
> > That's where the aosp list is for.
> 
> Oh. It's so awkward. I don't remember being so screwed up in recent years. I somehow missed google(`com.android.vending` here) in the lists. Was it in older versions?

Ah wait, it's in the `google` list.
