### ISSUE TITLE
Calling is broking

### ISSUE THREAD

**Issue by billyrl-code** [0x192/Universal-Android-Debloater#69]
After using recommend setting for Version samsung SM-A102U calling people dose not work. can you add a setting that will make it possible to call agen

**Comment by 0x192** [comment]
What exactly doesn't work? You are not talking about **Wifi/VoLTE** call right?

Upload the list of the packages you removed please.

Keep in mind you are the best placed to find the faulty package. You can restore all the packages and progressively uninstall `recommended` packages and test the calling feature until it breaks.

**Comment by billyrl-code** [comment]
the calling package does not detect that the sim card is in after i restart the phone after using recommend setting but i still can use mobile data and text
[All recommended.txt](https://github.com/0x192/universal-android-debloater/files/7655017/All.recommended.txt)

**Comment by lawson85** [comment]
You need to restore packages that relate to SIM, modem, mobile network and com.sec.phone

**Comment by billyrl-code** [comment]
ok thank you
