### ISSUE TITLE
Windows 10 21H2 LTSC- display issue

### ISSUE THREAD

**Issue by nen3i** [0x192/universal-android-debloater#699]
Hi,

I am using Windows 10 21H2 LTSC version and I am having display issues when using UAD. 

Lines show and dissapear on the screen and the text becames unreadeble. 
This happens when window is maximized or when is part of screen. 

I noticed that the issue dissapears when i search for something in the search bar.

https://imgur.com/a/Ub1Mw3R
https://screenrec.com/share/VFvX7Clowi

I noticed that this issue does not show when not using a LTSC version of Windows

**Comment by AnonymousWP** [comment]
Try the OpenGL-variant or the non OpenGL-variant: https://github.com/0x192/universal-android-debloater/releases/tag/0.5.1

**Comment by nen3i** [comment]
it works with OpenGL version

thanks

**Comment by AnonymousWP** [comment]
Then please close the issue as resolved.
