### ISSUE TITLE
Galaxy J330FN not being detected by UAD

### ISSUE THREAD

**Issue by haxerman123** [0x192/universal-android-debloater#703]
When i tried this program my J3 wasn't being detected at all. I have the samsung drivers for it but it still doesn't detect it. USB debugging is enabled and is working fine

**Comment by AnonymousWP** [comment]
Have you followed the installation steps? Maybe try moving UAD to the ADB folder.

**Comment by haxerman123** [comment]
> Have you followed the installation steps? Maybe try moving UAD to the ADB folder.

nope still didn't work. uad was always in my platform tools folder with adb.exe

**Comment by haxerman123** [comment]
> Maybe try [#634 (comment)](https://github.com/0x192/universal-android-debloater/issues/634#issuecomment-1450578054).

Thanks! It worked
