### ISSUE TITLE
device not found

### ISSUE THREAD

**Issue by Poi9912** [0x192/universal-android-debloater#704]
**Device not found via USB**

Launching UAD gives me the *no devices/emulators found* error, reinstalled the motorola USB drivers resulting in the same error and launched the app as administrator.

![image](https://user-images.githubusercontent.com/55921738/233527019-25b7f8dd-74d2-4bc1-8f35-b99e0d32a783.png)

Launched ADB shell connection with no problem.

![image](https://user-images.githubusercontent.com/55921738/233527223-f664b919-7b79-4e5b-bf19-790a8a9bdeb0.png)

Connected the phone direectly to AndroidStudio with no problem

![image](https://user-images.githubusercontent.com/55921738/233527302-17ba18cb-79c4-496f-ab5d-cf03182f354b.png)

I don't know if some of my settings on my pc can affect the behaviour of UAD, my windows settings:

Windows 11 Pro 22H2
System version 22621.1555
Windows Feature Experience Pack 1000.22640.1000.0
Developer mode Enable
HyperV Enable
WSL2 and WSA installed

**UAD log**

[UAD_20230420.log](https://github.com/0x192/universal-android-debloater/files/11291838/UAD_20230420.log)

Thaks for the help in advance!

**Comment by Poi9912** [comment]
Solved the issue, I had to turn off windows Core Isolation and restart my pc, don't know exactly why tbh

**Comment by akashkukreti** [comment]
dosen't works for me same issue sowing in the cmd  as attached devices but not in the uad

**Comment by AnonymousWP** [comment]
> dosen't works for me same issue sowing in the cmd  as attached devices but not in the uad
> 

Did you add ADB to PATH?
