### ISSUE TITLE
Live Caption no longer working.

### ISSUE THREAD

**Issue by Littlemac123** [0x192/universal-android-debloater#705]
I have tried searching google but its been not working

After running recommended removal on my verison samsong s20 FE 5g Live Caption setting disapeared and i been looking for what system app it was 

https://www.cnet.com/tech/mobile/googles-live-caption-works-on-the-galaxy-s20-heres-how-to-use-it/

How can so much articals online about this be so utterly useless! I just need to know the app ID at least!

**Comment by Rafee-M** [comment]
It's Android System Intelligence `com.google.android.as`. You can easily resotre it using UAD

**Comment by AnonymousWP** [comment]
So what's your suggestion/issue actually? Do you think we should change the removal or anything? @Littlemac123

**Comment by Littlemac123** [comment]
![Screenshot_2023-05-29_00-44-33](https://github.com/0x192/universal-android-debloater/assets/39867553/1d9ff2a3-b961-4f67-b97d-69fb1d3acdd6)
![Screenshot_2023-05-29_00-44-22](https://github.com/0x192/universal-android-debloater/assets/39867553/54ec52ab-51f2-454e-9370-c90c87409052)
Wrong i have it re enabed and its still not a feature i can use anymore like in the past. I think disabling it ones actually broke it maybe?

**Comment by Littlemac123** [comment]
Ohhh my bad that was the wrong app. Okay its fixed ♥ ill close it now. Sorry i used this for tech support basically
