### ISSUE TITLE
Bottom box text isn't selectable

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#71]
App sometimes provides urls that explain the explanation of an app etc. in the below box, but the text in that box isn't selectable. I think it should be selectable, so we can directly copy it and paste to browser. Windows 

![IMG_20211125_181334](https://user-images.githubusercontent.com/76991571/143466193-80a72fe9-1f84-497c-9afb-003e30ceb236.png)

**Comment by 0x192** [comment]
Yeah I know. I can't do much unfortunately. This is not yet natively supported by Iced. 

See #43
