### ISSUE TITLE
There has to be a way!
Debug system apps without root/pc

### ISSUE THREAD

**Issue by Logan1127** [0x192/universal-android-debloater#712]
I'm out of options. Day and night for weeks now I've tried everything to no avail. I've reached the end of the road, and it's scary!

**Comment by AnonymousWP** [comment]
> I'm out of options. Day and night for weeks now I've tried everything to no avail. I've reached the end of the road, and it's scary!

What you want to do? I only read something vague about debugging system apps without root/pc. What does it have to do with UAD?

**Comment by Logan1127** [comment]
Nothing about UAD. I'm new to git hub I may have posted in the wrong place. I thought it - [x] was an open forum for all topics.

**Comment by Logan1127** [comment]
I'm new to all of this, prior to about a week ago, I had never typed a command. Now I find myself with serious device security issues. I need all the help I can get.

**Comment by AnonymousWP** [comment]
> Nothing about UAD. I'm new to git hub I may have posted in the wrong place. I thought it - [x] was an open forum for all topics.

Mate why are you opening an issue about something completely unrelated in this repository then? Even if you don't understand how GitHub works: how did you end up here? Anyway, better close this issue as this has nothing to do with UAD.

**Comment by Logan1127** [comment]
I'm here looking for help.

**Comment by Logan1127** [comment]
Geeky Tools | Your weapon against the bad hackers...Is Someone Maliciously Spying On You Through Your Cell Phone? https://play.google.com/store/apps/details?id=com.secretcodes.geekyitoolsSent from my Galaxy
