### ISSUE TITLE
UI is broken

### ISSUE THREAD

**Issue by UmeshSairam66** [0x192/universal-android-debloater#717]
When a device is connected to the software it crashes and also breaks the screen
![image](https://user-images.githubusercontent.com/126087644/235472239-ca51dc2e-c8a7-452e-af9d-04229d67b6fd.png)
![image](https://user-images.githubusercontent.com/126087644/235472392-50dfc92d-11e6-4fee-b0fd-c214dbde7b72.png)
![image](https://user-images.githubusercontent.com/126087644/235472497-2b5b8cfb-7ebb-4f02-a822-5237705fc675.png)
![image](https://user-images.githubusercontent.com/126087644/235472614-72f4018f-c3c0-4bba-ba33-40a03706f71d.png)

**Comment by AnonymousWP** [comment]
Try the other version (either OpenGL version or non-OpenGL version).

**Comment by UmeshSairam66** [comment]
OpenGL version seems to work good for me.
Thanks...
