### ISSUE TITLE
Xiaomi App vault package

### ISSUE THREAD

**Issue by Morenofael** [0x192/universal-android-debloater#720]
**Your phone model**: Redmi Note 10 Pro, MIUI Global 13.0.16 stable

**Packages documentation to update:** 

```
com.mi.android.globalminusscreen
com.mi.globalminusscreen
...
```

## Documentation Change

**List**: `OEM` (manufacturer)
**Removal**: `Recommended`

### \<com.mi.android.globalminusscreen\>

**List**: \<unlisted\> :arrow_right: \<oem\>
**Removal**: \<unlisted\>
:arrow_right: \<recommended\>

### Current description

> [No description]

### Proposed description

> Xiaomi App vault. Safe to remove.

**Comment by AnonymousWP** [comment]
`com.mi.android.globalminusscreen` is present already: https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L15906. Also, it's not unlisted as you're claiming.

The other one has been added by me in an open PR: https://github.com/0x192/universal-android-debloater/pull/561
