### ISSUE TITLE
I clic on uninstall button and nothing happens, apps still installed

### ISSUE THREAD

**Issue by Pelix1000** [0x192/universal-android-debloater#722]
I do all the steps with Universal Android Debloater, but when I clic uninstall button on an application then nothing happens, app is not uninstalled, issue is on an Alcatel 1 Android 11

**Comment by ronys2** [comment]
i am having the same issue.

**Comment by AnonymousWP** [comment]
Uninstalling doesn't work on such Android versions. Try disabling instead.

**Comment by Pelix1000** [comment]
> Uninstalling doesn't work on such Android versions. Try disabling instead.

Thank you!

**Comment by AnonymousWP** [comment]
If it worked for you, close this issue as completed.
