### ISSUE TITLE
How do I open the UAD GUI?

### ISSUE THREAD

**Issue by deeeseee** [0x192/universal-android-debloater#724]
Sorry, I'm not very tech-savvy, but I'm trying to install the UAD GUI on my Linux machine (32-bit Zorin OS 15.3). I followed the instructions to install ADB located [here](https://github.com/0x192/universal-android-debloater#how-to-use-it) and then I downloaded the tar.gz file for the GUI from [here](https://github.com/0x192/universal-android-debloater/releases).

Once I get the tar.gz file, I extract it to my desktop, which gives me a file called "uad_gui-linux". The file has no extension, so my OS doesn't know what program to use to open it. When I double-click on it, it asks me which program to use to open it. Pardon my ignorance, but how do I actually open the GUI?

**Comment by devCanario** [comment]
open a terminal in Linux go to the folder where the app is and put "./uad_gui-linux" or the name of the file without the ", essentially put the ./ before the name and press enter

**Comment by deeeseee** [comment]
> open a terminal in Linux go to the folder where the app is and put "./uad_gui-linux" or the name of the file without the ", essentially put the ./ before the name and press enter

When I do that, I receive the following message: 
`bash: ./uad_gui-linux: cannot execute binary file: Exec format error`

Thanks for trying to help! Do you have any other suggestions?

**Comment by devCanario** [comment]
you need to have linux in a x64 version looks like your linux is x32 or arm procesor 
run this command to see your arch 
lscpu | grep Architecture
needs to be something like this  "Architecture:        x86_64"

**Comment by deeeseee** [comment]
> you need to have linux in a x64 version looks like your linux is x32 or arm procesor run this command to see your arch lscpu | grep Architecture needs to be something like this "Architecture: x86_64"

Oh, that's the problem! I do have a 32-bit system. (I had looked for the system requirements of UAD but couldn't find it.)

Thanks for the help!
