### ISSUE TITLE
Can anybody give me some insight on what this is exactly? What can be done about it? This is the second laptop and like 8th phone that's been severely infected within the last month.

### ISSUE THREAD

**Issue by Logan1127** [0x192/universal-android-debloater#728]
![IMG_20230508_043628174.jpg](https://user-images.githubusercontent.com/130795631/236787514-dbae07e2-7b60-4bd9-889c-3c3b76f02767.jpg)

**Comment by AnonymousWP** [comment]
How is this even related to UAD? It isn't. Close your issue and stop opening irrelevant issues man. Ask on a forum or something, but not here.
