### ISSUE TITLE
Chase banking app not working

### ISSUE THREAD

**Issue by zany130** [0x192/universal-android-debloater#734]
**Your phone model**:
Samsung Galaxy S23 TMobile USA
**Describe the issue**
Chase banking app does not work after uninstalling webview(bromite doesn't fix it)

**UAD log**
Upload the logfile generated by UAD. It would be difficult to help you without it.
[UAD_20230514.log](https://github.com/0x192/universal-android-debloater/files/11472865/UAD_20230514.log)

**Comment by xip0enix** [comment]
Have you rooted your phone? As I know, you can't change the webview on stock phones (see: https://github.com/bromite/bromite/wiki/Installing-SystemWebView#installation-without-root). Webview is a necessary app for the system to work well. Uninstalling it will cause errors in other apps too.

**Comment by zany130** [comment]
yup that was the cause I thought there was another removal messing it up but I just needed to reboot after restoring stock webview
