### ISSUE TITLE
uninstalling com.miui.guardprovider breaks apk installation

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#74]
If you uninstall this package, you can't install APKs anymore; you should definitely add it to app description. I tested it myself, and it is also seen here https://forum.xda-developers.com/t/accidentally-removed-com-miui-guardprovider-and-now-i-cant-install-apks-manually.4014311/

**Comment by 0x192** [comment]
[This is already documented]( https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L15737). But I made the warning clearer.

**Comment by FrederikSchack** [comment]
I can confirm that uninstalling guardprovider breaks installation with F-droid, AuroraStore and APKMirror apps on my Poco X3.
