### ISSUE TITLE
com.motorola.paks protected by ADB -- Moto G ...etc. phone

### ISSUE THREAD

**Issue by equwal** [0x192/universal-android-debloater#741]
**Describe the bug**
If you have the adb program installed then you can't uninstall the OEM bloatware pack. And that is the point of this program, especially with a naughtly OEM like motorolla.

Phone -- Moto G Power (2022) Tonga XT2165-5 US/RETUS ; Android 11.

**Expected behavior**
Uninstall the bloat.

**You have a solution?**
Use the F-Droid De-Bloater APK, or the sDebloater magisk module with entry PAKS. Block it at runtime.

**UAD log**
2023-05-19 20:34:08 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 0 com.motorola.paks -> Failure: package is protected

**Comment by Cima899** [comment]
## NON-ROOT USER

1) First download what is needed for debloat.

## SHIZUKU

https://github.com/RikkaApps/Shizuku/releases/download/v13.5.4/shizuku-v13.5.4.r1049.0e53409-release.apk

## Related video to install it

https://youtu.be/CWJF4ow1lHA?si=UBF4diHCvRH5R5Dq


## HAIL

https://github.com/aistra0528/Hail/releases/download/v1.8.1/Hail-v1.8.1.apk



2) Install both apps and grant all permissions.
 
(set HAIL as administrator)

Open Shizuku and Hail, from the Hail settings panel choose shizuku disable as the working method.

Secure Shizuku permissions


3) Restart your phone


4) Reactivate shizuku and open hail.

select the app and disable it,
filter your search to frozen/disabled apps and select by holding.

Press uninstall and you're done.


Thanks to:
 Rikka and Astra who are members here 🙏👽

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/ygYJDf9YBn
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org

**Comment by equwal** [comment]
closing now for no reason

**Comment by tojestzart** [comment]
@Cima899  dont work/ dont understand single word what you said, proper solution is this https://xdaforums.com/t/fishy-device-admin-app-paks-found-in-motorolas-new-moto-g72.4530189/#post-89597067
@Obegg still newest version cant remove trought adb (moto g31)
