### ISSUE TITLE
Add com.motorola.gamemode to the list

### ISSUE THREAD

**Issue by equwal** [0x192/universal-android-debloater#742]
MOTO G POWER (2022) TONGA XT2165-5 US

but any phone with Motorola GameBlode

**Packages:**

```
com.motorola.gamemode
```

- [ X] **I removed all those packages on my phone**

## Document each package the best you can

`OEM`, I think. You know: bloatware pack.

**Removal**: `Recommended`

Nobody wants or needs their shitty game overlay or whatever. I never opened it.

### GameMode

**List**: \<oem\>
**Removal**: `Recommended`

> Description. A gamer themed bloatware app.

**Comment by AnonymousWP** [comment]
So it's an overlay? Check the description I've given in the PR.

**Comment by AnonymousWP** [comment]
Why are you closing the issue? That's not needed; my PR will close this issue once it gets merged, so please re-open it.
