### ISSUE TITLE
Loading taking longer than usual

### ISSUE THREAD

**Issue by notsam3000** [0x192/universal-android-debloater#753]
**Your phone model**: Oppo A5 2020

**Describe the issue**
All the loading screens/general loading in the android or in any app is taking more time than usual after debloating

**You have a solution?**
What to do to fix the issue.

**UAD log**
Upload the logfile generated by UAD.
[uad.log](https://github.com/0x192/universal-android-debloater/files/11565629/uad.log)

**UAD Exported Selection**
All things I removed :
[uad_exported_selection.txt](https://github.com/0x192/universal-android-debloater/files/11565659/uad_exported_selection.txt)

**Comment by AnonymousWP** [comment]
Check whichever disabled package has a description related to performance.

**Comment by notsam3000** [comment]
> Check whichever disabled package has a description related to performance.

Thanks but I somehow fixed it by factory reseting and deleting everything again. It works fine now :)
