### ISSUE TITLE
Google Chrome Now Required Dependency for Passkeys

### ISSUE THREAD

**Issue by thedepartedwhiplash** [0x192/universal-android-debloater#756]
**Pixel 7 Pro**:

**Describe the issue**
The `com.android.chrome` package is required to create and store [passkeys](https://fidoalliance.org/passkeys/) on your Pixel phone (Don't know if this issue occurs with other phones). Without it, scanning the passkey QR code does nothing.

Steps To Recreate/Demonstrate (Example):
- Go to https://myaccount.google.com/signinoptions/passkeys to add a passkey for your Google Account. 
- Click on 'Create a passkey'
- Click on 'Use another device'
- In the pop-up, click 'Use a different phone or tablet'. You should see a QR code now. Try to scan it on a Pixel phone with Google Chrome disabled/uninstalled. It won't do anything.
- Re-enable or install Google Chrome. Now try scanning the QR code again. The expected behavior should occur now and you should be able to create and store the passkey.

**You have a solution?**
Update the package description to say that you need to keep it enabled if you want to take advantage of passkeys for passwordless authentication.

**UAD log**
Not applicable here.

**Comment by AnonymousWP** [comment]
In that case, can you file an issue with [this template](https://github.com/0x192/universal-android-debloater/issues/new?assignees=&labels=package%3A%3Adocumentation&projects=&template=update-apps-description-or-recommendation.md&title=) instead?

**Comment by thedepartedwhiplash** [comment]
Sure, I was a bit unsure which template to use between that and this one but I went with this one just in case. Sorry about that.
