### ISSUE TITLE
Not showing any devices

### ISSUE THREAD

**Issue by Gelaxiz** [0x192/universal-android-debloater#765]
Im just trying to test this thing (UAD) but it doesnt show any devices and i did everything the README said

![image](https://github.com/0x192/universal-android-debloater/assets/130848366/eae3bde7-4e45-4eea-8a97-6f0f52f53160)
![Untitled](https://github.com/0x192/universal-android-debloater/assets/130848366/7ad8536b-8a76-4e62-9248-3641f46819da)

phone sumung a22 5g

**Comment by mnkhrw** [comment]
Have you set up adb devices?

**Comment by Gelaxiz** [comment]
i think so

**Comment by AnonymousWP** [comment]
Have you even followed the instructions? "I think so" doesn't sound too confident.

**Comment by Gelaxiz** [comment]
Yeah

**Comment by Gelaxiz** [comment]
![SmartSelect_20230606_184131_Samsung Internet](https://github.com/0x192/universal-android-debloater/assets/130848366/87d2373d-ccb3-4c67-9a8b-1f302e8afbfc)
 I think i lost the track here

**Comment by AnonymousWP** [comment]
> ![SmartSelect_20230606_184131_Samsung Internet](https://user-images.githubusercontent.com/130848366/243751531-87d2373d-ccb3-4c67-9a8b-1f302e8afbfc.jpg) I think i lost the track here

Just move UAD to the ADB installation directory.

**Comment by Gelaxiz** [comment]
i removed windows so i cant do it anymore

**Comment by Gelaxiz** [comment]
i removed windows and installed linux so i cant do it anymore
