### ISSUE TITLE
Import/Export custom selection

### ISSUE THREAD

**Issue by 0x192** [0x192/universal-android-debloater#8]
In GitLab by @W1nst0n on Aug 22, 2021, 02:24

Allow the user to export their current package selection to a file (`uad_exported_selection.txt`) so that UAD can automatically select the packages from this file upon startup.

**Comment by 0x192** [comment]
In GitLab by @W1nst0n on Sep 25, 2021, 11:04

changed title from **{-Export JSON phone packages list-}** to **{+Import/Export custom selection+}**

**Comment by 0x192** [comment]
In GitLab by @W1nst0n on Sep 25, 2021, 11:04

changed the description

**Comment by 0x192** [comment]
In GitLab by @W1nst0n on Sep 25, 2021, 11:22

mentioned in commit 2476a59423accbbac8b7dcfaf910fa4c833b3b9e

**Comment by 0x192** [comment]
In GitLab by @W1nst0n on Sep 25, 2021, 11:23

changed the description

**Comment by Funny-Klutz** [comment]
Please provide a confirmation dialog for the export as well. I just tried this function and for a moment I thought it was not working.
