### ISSUE TITLE
Samsung Galaxy A31 unlisteds

### ISSUE THREAD

**Issue by Rudxain** [0x192/universal-android-debloater#811]
**Your phone model:** SM-A315G

**Packages:**

```
com.android.cameraextensions
com.android.cts.ctsshim
com.android.internal.systemui.onehanded.gestural
com.android.theme.font.notoserifsource
com.debug.loggerui
com.google.android.as.oss
com.google.android.nearby.halfsheet
com.google.android.overlay.gmsconfig.geotz
com.google.android.safetycenter.resources
com.mediatek.cellbroadcastuiresoverlay
com.mediatek.frameworkresoverlay
com.mediatek.FrameworkResOverlayExt
com.mediatek.MtkSettingsResOverlay
com.mediatek.SettingsProviderResOverlay
com.mediatek.systemuiresoverlay
com.mediatek.systemuiwmshellresoverlay
com.samsung.adaptivebrightnessgo
com.samsung.android.app.updatecenter
com.samsung.android.ConnectivityOverlay
com.samsung.android.ConnectivityUxOverlay
com.samsung.android.gru
com.samsung.android.mdagent
com.samsung.android.mtp
com.samsung.android.peripheral.framework
com.samsung.android.privacydashboard
com.samsung.android.providers.factory
com.samsung.android.visualars
com.samsung.android.wallpaper.res
com.samsung.android.wcmurlsnetworkstack
com.samsung.android.wifi.h2e.resources
com.samsung.android.wifi.p2paware.resources
com.samsung.cmfa.AuthTouch
com.samsung.phone.overlay.common
com.sec.android.app.ve.vebgm
com.sec.android.soagent
```

- [ ] **I removed all those packages on my phone**
      Some are unsafe.

## Document each package the best you can

> to-do: add more

### com.google.android.as.oss

**List**: `Google`
**Removal**: `Recommended`

> Private Compute Services.
> https://play.google.com/store/apps/details?id=com.google.android.as.oss
> Seems to be a dependency of System Intelligence

### com.samsung.android.visualars
**List**: `OEM`
**Removal**: `Recommended`

> Smart Touch Call.
> It has a Settings activity with 1 setting, the title is "Use Smart Touch Call" and description is "Get voice and Screen interactive service when you call a customer service"

Removed recently.

### com.sec.android.app.ve.vebgm
**List**: `OEM`
**Removal**: `Recommended`

> Samsung Editing Assets. Seems to be a dependency of Video Editor/Trimmer Lite, not "Photo Editor". Its ID seems to stand for "Video Editor BackGround Music": https://www.bloatware.info/doku.php?id=com.sec.android.app.ve.vebgm

I removed this, nothing broke.

**Comment by AnonymousWP** [comment]
Can you add some documentation/description etc. to it as well?

**Comment by Rudxain** [comment]
> Can you add some documentation/description etc. to it as well?

Yes. I'm currently busy, so I'll do it later

**Comment by Rudxain** [comment]
@AnonymousWP So far, I've added 2. I'll continue adding info (gradually/incrementally) in the following weeks.

**Comment by AnonymousWP** [comment]
> @AnonymousWP So far, I've added 2. I'll continue adding info (gradually/incrementally) in the following weeks.

Wouldn't waste your time on a dead project if I were you to be honest. I also stopped putting effort into this.

**Comment by Rudxain** [comment]
> dead project

You mean UAD?

> I also stopped putting effort into this.

I understand. There are other alternatives to UAD, and they may be better maintained. There's also the fact that it's easier to debloat using Shizuku API (or `adb` on Termux), since it doesn't require an external device. I've been considering making a fork of UAD as an APK.

But debloating on an external device is safer (although less secure and private), because breaking-changes can be easily reverted (like a glitched System UI)

**Comment by AnonymousWP** [comment]
> > dead project
> 
> You mean UAD?

Yes.

> > I also stopped putting effort into this.
> 
> I understand. There are other alternatives to UAD, and they may be better maintained. There's also the fact that it's easier to debloat using Shizuku API (or `adb` on Termux), since it doesn't require an external device. I've been considering making a fork of UAD as an APK.
> 
> But debloating on an external device is safer (although less secure and private), because breaking-changes can be easily reverted (like a glitched System UI)

Yes, see this project (and in particular, the issue): https://github.com/MuntashirAkon/android-debloat-list/issues/37?notification_referrer_id=NT_kwDOAv55krM3NjAyNjMyMzUwOjUwMjMxNjk4#issuecomment-1706078318. I still didn't contribute to it though, as it's a lot of work.

**Comment by Rudxain** [comment]
I've been living under a rock, lmao. Thank you for the info, I'm now up-to-date

**Comment by Rudxain** [comment]
Most of those packs are already listed [here](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/d1a7eb1cd6951080aa82b58f2100e639fdcb0d4e/resources/assets/uad_lists.json)
