### ISSUE TITLE
add com.miui.fm (radio app)

### ISSUE THREAD

**Issue by ghost** [0x192/Universal-Android-Debloater#85]
POCO X3 NFC

com.miui.fm

MIUI fm radio app. Tested it on my phone, safe to remove. 
![IMG_20211219_150406](https://user-images.githubusercontent.com/76991571/146674333-d7e3108b-7bdc-43d4-94fd-624617c1aa51.jpg)

**Comment by Dhyfer1** [comment]
And what do you say about the Gallery application next to it? Is it safe to remove it?

**Comment by ghost** [comment]
> And what do you say about the Gallery application next to it? Is it safe to remove it?

Yeah, it is safe to remove, but I don't recommend uninstalling. it is better than other gallery apps

**Comment by Dhyfer1** [comment]
It's ok, have you tried uninstalling the File Manager app, do you think it's safe to uninstall it? I would like to replace it with a better alternative, and the new file explorer I will leave as a system app.

Another application that I don't know if it is safe to uninstall is the Compass application, have you tried uninstalling that app? I don't know if uninstalling it could render the map and navigation apps unusable. I'm not sure.

**Comment by ghost** [comment]
> It's ok, have you tried uninstalling the File Manager app, do you think it's safe to uninstall it? I would like to replace it with a better alternative, and the new file explorer I will leave as a system app.
> 
> Another application that I don't know if it is safe to uninstall is the Compass application, have you tried uninstalling that app? I don't know if uninstalling it could render the map and navigation apps unusable. I'm not sure.

Maps and navigation work fine without the compass app.

**Comment by 0x192** [comment]
I don't exactly remember when but `com.miui.fm` has been added since the opening of this issue. :slightly_smiling_face: 

https://raw.githubusercontent.com/0x192/universal-android-debloater/main/resources/assets/uad_lists.json
