### ISSUE TITLE
Device: ADB was not found error

### ISSUE THREAD

**Issue by ZMOT7S** [0x192/Universal-Android-Debloater#88]
I'm getting ADB was not found error when trying to use the program. I can detect my phone as normal using ADB in cmd prompt. I tried the normal version and the OpenGL version. Both give the same error. I have tried different USB cords and ports as well. 

https://i.imgur.com/NwG0rtm.png

Phone: Google Pixel 3A XL
Android: Latest Android 12 update
PC OS: Windows 10

**Comment by 0x192** [comment]
Sorry for the late reply. I really can't explain why you have this error. 

Except a weird Windows PATH issue, I can't really help...

1) Try to run it again like now (yeah it's silly but with Windows we never know...)
2) You can try to run it from the directory where ADB was installed.

**Comment by Theluga** [comment]
yes, it solved running in the same directory.

**Comment by 0x192** [comment]
> yes, it solved running in the same directory.

This means ADB isn't in your path ([Add the folder to your PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/))

**Comment by MuhamedUsman** [comment]
On windows I did the same, put the adb and the uad in the same folder and everything worked fine.
![Screenshot (1)](https://user-images.githubusercontent.com/105865001/170890248-2183f3d6-8058-4b73-87bb-8e12c16f5afa.png)
e

**Comment by Dipesh-Saw** [comment]
> On windows I did the same, put the adb and the uad in the same folder and everything worked fine. ![Screenshot (1)](https://user-images.githubusercontent.com/105865001/170890248-2183f3d6-8058-4b73-87bb-8e12c16f5afa.png) e

Thank You very much 😊😊😊
