### ISSUE TITLE
Don't remove com.miui.home

### ISSUE THREAD

**Issue by vitoramaral10** [0x192/universal-android-debloater#906]
**Your phone model**:

**Packages documentation to update:**

```
com.miui.home
```

## Documentation Change

**List**: `OEM` (manufacturer).
**Removal**: `Unsafe`.

### Proposed description

> DON'T REMOVE THIS PACKAGE, IT MANAGES OPEN APPLICATIONS

**Comment by janos-r** [comment]
Was it part of the recommended or unsafe group?

**Comment by vitoramaral10** [comment]
Expert, but this package crash recent apps.

**Comment by vitoramaral10** [comment]
Expert, but this package crash recent apps.

**Comment by vitoramaral10** [comment]
Expert, but this package crash recent apps.
