### ISSUE TITLE
DELETE_FAILED_DEVICE_POLICY_MANAGER

### ISSUE THREAD

**Issue by Drjacky** [0x192/universal-android-debloater#927]
```bash
ERROR [src/core/utils.rs:228] [Unlisted] pm uninstall --user 0 com.example -> Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]
```

**Comment by Frigyes06** [comment]
Try disabling?

**Comment by Drjacky** [comment]
> Try disabling?

Disabling doesn't work either. It was the same error or something like the package is protected.

**Comment by Frigyes06** [comment]
Yeah, some packages won't let you delete them. It's like that. Also please see #923 for future issues
