### ISSUE TITLE
Search for screen name

### ISSUE THREAD

**Issue by FrederikSchack** [0x192/Universal-Android-Debloater#93]
Thanks for a very nice app and especially the information collected in it. I don´t think there´s a better source of information regarding Android Packages, for the purpose.

It took me a while to figure out that Battery and Performance is called com.miui.powerkeeper, it would be helpful to be able to search for the screen name.

I was looking specifically for this app because I could see that it is trying to connect to the Internet all the time in NetGuard, but only with screen name, not the package name.

**Comment by FrederikSchack** [comment]
I realized that in netguard I can search for the screen name and get more details about the app/service, where I can also see the package name.

So very much nice to have feature for me and probably others too.

**Comment by 0x192** [comment]
You're not the first one to ask for this. The application name will be displayed in the `v0.5`. I really need to release the `v0.4` quickly. New features are frozen for this release.

#59 already tracks this feature request.
