### ISSUE TITLE
Mi Remote Controller

### ISSUE THREAD

**Issue by FrederikSchack** [0x192/Universal-Android-Debloater#94]
**Your phone:** Poco X3

**Packages:**
```
com.duokan.phone.remotecontroller
```
- [x] **I removed all those packages on my phone**

## Document each package the best you can
**List**: `Google`|`Misc`|`Oem` (manufacturer)|`Aosp`|`Pending`|`Carrier` (isp).
**Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features), `Unsafe` (this can bootloop the phone or break extremely important features).

### com.duokan.phone.remotecontroller
**List**: `Oem`
**Removal**: `Recommended`
> Description. 
A simple remote controller with way too many permissions. Didn´t observe any negative aspects of uninstalling it for a couple of days.
[Link to its Playstore page if it exists.](https://play.google.com/store/apps/details?id=com.duokan.phone.remotecontroller&hl=es_UY&gl=US)

**Comment by KarlRamstedt** [comment]
This is in the latest version of the list.
@FrederikSchack You can close this issue now.
