### ISSUE TITLE
an option to manual updated debloat list when UAD can't connected to the server (no internet?)

### ISSUE THREAD

**Issue by braboobssiere** [0x192/universal-android-debloater#940]
**Describe the feature you want**
^ title

**Comment by Obegg** [comment]
https://github.com/0x192/universal-android-debloater/issues/923

**Comment by xstable** [comment]
see #973 for detail description & Logs I got with the same error

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD discord server: https://discord.gg/ygYJDf9YBn
