### ISSUE TITLE
Removal of Simple-Mobile Tools from recommendation sections

### ISSUE THREAD

**Issue by im-notpua** [0x192/universal-android-debloater#954]
**Your phone model**: 

Any Xiaomi, Samsung, Pixel device

**Packages documentation to update:** 

```
com.touchtype.swiftkey.res.overlay
com.android.honeyboard
com.miui.gallery
com.google.android.inputmethod.latin
```

## Documentation Change

**List**: `Google`|`Misc`|`OEM` (manufacturer)

### Current description

> Simple (product) is a good FOSS, lightweight replacement for system default, https://f-droid.org/en/packages/(package-link)

The current description contains recommending certain apps from 'Simple-Mobile-Tools'.
But as of 2024, sadly the company behind this suite of applications has been bought by an Ad-company.
Here are some related articles [1](https://www.ghacks.net/2023/12/05/warning-simple-mobile-tools-sold-to-controversial-zipoapps-publisher/), [2](https://www.androidauthority.com/simple-mobile-tools-acquisition-3391041/), [3](https://vid.puffyan.us/watch?v=OGr4H7QLVRs). 

Which would mean we can no longer proudly recommend these applications to our privacy-focused user-base.

### Proposed description

Either remove these recommendations, or replace them with better ones like ['Unexpected Keyboard'](https://f-droid.org/en/packages/juloo.keyboard2), ['LeafPic-Revived'](https://f-droid.org/en/packages/com.alienpants.leafpicrevived).

**Comment by Obegg** [comment]
https://github.com/0x192/universal-android-debloater/issues/923

If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD discord server: https://discord.gg/ygYJDf9YBn

**Comment by im-notpua** [comment]
Alright Sure, I have opened and issue over at the [new repo](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/158)

**Comment by im-notpua** [comment]
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/158
