### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by DeadSecTr** [0x192/universal-android-debloater#959]
Dev gone?

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD discord server: https://discord.gg/ygYJDf9YBn

**Comment by shiftykey** [comment]
Can someone put this in the readme of this freakin' repo?

**Comment by Obegg** [comment]
No, because this project manager is not active
