### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Ketsuyumi** [0x192/universal-android-debloater#975]
**App crash**
App crashes after hitting uninstall package

**It should uninstall the package**
It doesn't

**Comment by Ketsuyumi** [comment]
I would upload crash log but idk how to find the file

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD discord server: https://discord.gg/ygYJDf9YBn
