### ISSUE TITLE
Honor supported?

### ISSUE THREAD

**Issue by Curione23** [0x192/universal-android-debloater#976]
I have a Honor branded device and since Huawei is very similar with Honor, will it work?

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/ygYJDf9YBn
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org
