### ISSUE TITLE
Unable to open the app in MacOS

### ISSUE THREAD

**Issue by vigneshrajarr** [0x192/Universal-Android-Debloater#99]
Bug: Unable to open the file in MacOS. The file is detected as TextEdit document. Tried both Normal and OpenGL versions.
Expected: To open the GUI directly.
UAD log: None.
UAD version : 3.0
Mac version : Catalina 10.15.3

**Comment by 0x192** [comment]
You haven't read the [README](https://github.com/0x192/universal-android-debloater#how-to-use-it) as far as I can see.

Please read the [FAQ](https://github.com/0x192/universal-android-debloater/wiki/FAQ#why-the-hell-cant-i-launch-this-app). There is the answer in it.

**Comment by vigneshrajarr** [comment]
I followed the mentioned FAQ before raising this issue. But not worked by right-clicking it.
Now tried giving the executable permission as specified for Linux and got it worked.

**Comment by 0x192** [comment]
Thanks for your feedback. I will update the FAQ.
