### ISSUE TITLE
Download ADB automatically

### ISSUE THREAD

**Issue by maverick74** [0x192/universal-android-debloater#999]
**Describe the feature you want**

Well, i don't know if this is possible but i think  that it would be useful specially for non-techies if:

- **After installing UAD, on the first run it would automatically download and install/extract ADB.**

This would simplify all the process to get UAD working and reduce it to a _**kind of**_ "_one installation process and you're ready to go_"

To a user it would be something like 

1. Install UAD, 
2. connect your phone to PC and 
3. remove the apps you want

(don't know if this is possible, however... just an idea ;). Feel free to close it as _nonsense_ if it feels like it! )

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/ygYJDf9YBn
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org

**Comment by maverick74** [comment]
> If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.
> 
> I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation Please open your issues and pull requests there, as well as use those builds.

Hi!!! 

I didn't noticed it, sorry!!!

I'll open the issue there, then.

Thank you :)

**Comment by maverick74** [comment]
i suppose i can close this...
